//! Topic cards and evaluation DAO for 3-day recap redesign.
//!
//! All tables are INSERT-only: snapshots, candidates, cards, job_stats,
//! eval_windows, story_judgments, and card_ratings.

#![allow(dead_code)]

use crate::error::{RecapError, Result};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sqlx::types::Json;
use sqlx::{PgPool, Row};
use uuid::Uuid;

/// 1. Snapshot of input state frozen at job execution time (reproject-safe).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecapCardSnapshot {
    pub job_id: Uuid,
    pub from_ts: DateTime<Utc>,
    pub to_ts: DateTime<Utc>,
    pub feed_ids: Vec<Uuid>,
    pub read_feed_ids: Vec<Uuid>,
    pub previous_job_id: Option<Uuid>,
    pub previous_cards: Value,
    pub params_version: String,
    pub params: Value,
    pub created_at: DateTime<Utc>,
}

/// 2. Candidates produced by selection phase prior to LLM generation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecapCardCandidate {
    pub id: Uuid,
    pub job_id: Uuid,
    pub rank: i32,
    pub cluster_fingerprint: String,
    pub size: i32,
    pub domains: Value,
    pub items: Value,
    pub scores: Value,
    pub centroid: Option<Vec<f32>>,
    pub created_at: DateTime<Utc>,
}

/// 3. Versioned topic cards selected and generated by recap pipeline.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecapCard {
    pub id: Uuid,
    pub job_id: Uuid,
    pub rank: i32,
    pub story_id: Uuid,
    pub continues_card_id: Option<Uuid>,
    /// Previous card IDs merged into this continuation (same ID space as continues_card_id).
    pub merged_from: Option<Vec<Uuid>>,
    pub headline_ja: String,
    pub what_ja: String,
    pub why_ja: Option<String>,
    pub genre: Option<String>,
    pub member_feed_ids: Vec<Uuid>,
    pub sources: Value,
    pub centroid: Option<Vec<f32>>,
    pub scores: Value,
    pub gates: Value,
    pub generation: Value,
    pub created_at: DateTime<Utc>,
}

/// 4. Pipeline execution stats and gate drop metrics.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecapCardJobStats {
    pub job_id: Uuid,
    pub items_fetched: i32,
    pub items_after_noise: i32,
    pub items_after_dedup: i32,
    pub clusters: i32,
    pub candidates: i32,
    pub cards_selected: i32,
    pub cards_dropped: Value,
    pub embed_ms: i64,
    pub cluster_ms: i64,
    pub llm_ms: i64,
    pub total_ms: i64,
    pub params_version: String,
    pub created_at: DateTime<Utc>,
}

/// 5. Evaluation windows referencing replay snapshots.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecapEvalWindow {
    pub id: Uuid,
    pub from_ts: DateTime<Utc>,
    pub to_ts: DateTime<Utc>,
    pub snapshot_job_id: Uuid,
    pub created_at: DateTime<Utc>,
}

/// Evaluation window with aggregate candidate and judgment counts.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecapEvalWindowSummary {
    pub id: Uuid,
    pub from_ts: DateTime<Utc>,
    pub to_ts: DateTime<Utc>,
    pub snapshot_job_id: Uuid,
    pub created_at: DateTime<Utc>,
    pub candidate_count: i64,
    pub judged_count: i64,
}

/// 6. Human golden judgments on candidate clusters (top / not_top / noise).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecapStoryJudgment {
    pub id: Uuid,
    pub window_id: Uuid,
    pub cluster_fingerprint: String,
    pub decision: String,
    pub rated_at: DateTime<Utc>,
}

/// 7. Human ratings on generated topic cards (0/1/2 + defect flags + comment).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecapCardRating {
    pub id: Uuid,
    pub card_id: Uuid,
    pub score: i16,
    pub flags: Vec<String>,
    pub comment: Option<String>,
    pub rated_at: DateTime<Utc>,
}

/// Summary of a cards job from recap_jobs.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CardsJob {
    pub job_id: Uuid,
    pub status: String,
    pub trigger_source: String,
    pub created_at: DateTime<Utc>,
}

/// Summary of a cards job from recap_jobs with aggregate card and rating counts.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CardsJobSummary {
    pub job_id: Uuid,
    pub status: String,
    pub trigger_source: String,
    pub kicked_at: DateTime<Utc>,
    pub card_count: i64,
    pub rated_count: i64,
}

/// Summary of a previous card for novelty matching and continuation tracking.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PreviousCardSummary {
    pub id: Uuid,
    pub story_id: Uuid,
    pub centroid: Vec<f32>,
}

/// Information about the latest completed cards job and its cards.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PreviousCardsJob {
    pub job_id: Uuid,
    pub to_ts: DateTime<Utc>,
    pub cards: Vec<PreviousCardSummary>,
}

/// Pure validation helper for judgment decisions.
#[must_use]
pub fn is_valid_decision(decision: &str) -> bool {
    matches!(decision, "top" | "not_top" | "noise")
}

/// Pure validation helper for card rating scores (0, 1, 2).
#[must_use]
pub fn is_valid_score(score: i16) -> bool {
    (0..=2).contains(&score)
}

/// Trait for Cards & Evaluation data access operations.
pub trait CardsDao: Send + Sync {
    fn insert_card_snapshot(
        &self,
        snapshot: &RecapCardSnapshot,
    ) -> impl std::future::Future<Output = Result<()>> + Send;

    fn get_card_snapshot(
        &self,
        job_id: Uuid,
    ) -> impl std::future::Future<Output = Result<Option<RecapCardSnapshot>>> + Send;

    fn insert_card_candidates(
        &self,
        candidates: &[RecapCardCandidate],
    ) -> impl std::future::Future<Output = Result<()>> + Send;

    fn get_card_candidates(
        &self,
        job_id: Uuid,
    ) -> impl std::future::Future<Output = Result<Vec<RecapCardCandidate>>> + Send;

    fn get_candidates_for_window(
        &self,
        window_id: Uuid,
    ) -> impl std::future::Future<Output = Result<Vec<RecapCardCandidate>>> + Send;

    fn insert_cards(
        &self,
        cards: &[RecapCard],
    ) -> impl std::future::Future<Output = Result<()>> + Send;

    fn get_cards_for_job(
        &self,
        job_id: Uuid,
    ) -> impl std::future::Future<Output = Result<Vec<RecapCard>>> + Send;

    fn insert_job_stats(
        &self,
        stats: &RecapCardJobStats,
    ) -> impl std::future::Future<Output = Result<()>> + Send;

    fn get_job_stats(
        &self,
        job_id: Uuid,
    ) -> impl std::future::Future<Output = Result<Option<RecapCardJobStats>>> + Send;

    fn insert_eval_window(
        &self,
        window: &RecapEvalWindow,
    ) -> impl std::future::Future<Output = Result<()>> + Send;

    fn get_eval_window(
        &self,
        window_id: Uuid,
    ) -> impl std::future::Future<Output = Result<Option<RecapEvalWindow>>> + Send;

    fn list_eval_windows(
        &self,
    ) -> impl std::future::Future<Output = Result<Vec<RecapEvalWindowSummary>>> + Send;

    fn insert_story_judgment(
        &self,
        judgment: &RecapStoryJudgment,
    ) -> impl std::future::Future<Output = Result<()>> + Send;

    fn latest_judgments_for_window(
        &self,
        window_id: Uuid,
    ) -> impl std::future::Future<Output = Result<Vec<RecapStoryJudgment>>> + Send;

    fn insert_card_rating(
        &self,
        rating: &RecapCardRating,
    ) -> impl std::future::Future<Output = Result<()>> + Send;

    fn latest_rating_per_card(
        &self,
        job_id: Uuid,
    ) -> impl std::future::Future<Output = Result<Vec<RecapCardRating>>> + Send;

    fn list_cards_jobs(
        &self,
        limit: i64,
    ) -> impl std::future::Future<Output = Result<Vec<CardsJobSummary>>> + Send;
}

pub struct CardsDaoOps;

impl CardsDaoOps {
    pub async fn insert_snapshot(pool: &PgPool, s: &RecapCardSnapshot) -> Result<()> {
        sqlx::query(
            r"
            INSERT INTO recap_card_snapshots (
                job_id, from_ts, to_ts, feed_ids, read_feed_ids,
                previous_job_id, previous_cards, params_version, params
            ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
            ",
        )
        .bind(s.job_id)
        .bind(s.from_ts)
        .bind(s.to_ts)
        .bind(&s.feed_ids)
        .bind(&s.read_feed_ids)
        .bind(s.previous_job_id)
        .bind(Json(&s.previous_cards))
        .bind(&s.params_version)
        .bind(Json(&s.params))
        .execute(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to insert recap_card_snapshot: {e}")))?;
        Ok(())
    }

    pub async fn get_snapshot(pool: &PgPool, job_id: Uuid) -> Result<Option<RecapCardSnapshot>> {
        let row = sqlx::query(
            r"
            SELECT job_id, from_ts, to_ts, feed_ids, read_feed_ids,
                   previous_job_id, previous_cards, params_version, params, created_at
            FROM recap_card_snapshots
            WHERE job_id = $1
            ",
        )
        .bind(job_id)
        .fetch_optional(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to get recap_card_snapshot: {e}")))?;

        match row {
            Some(r) => {
                let previous_cards: Value = r.try_get::<Json<Value>, _>("previous_cards")?.0;
                let params: Value = r.try_get::<Json<Value>, _>("params")?.0;
                Ok(Some(RecapCardSnapshot {
                    job_id: r.try_get("job_id")?,
                    from_ts: r.try_get("from_ts")?,
                    to_ts: r.try_get("to_ts")?,
                    feed_ids: r.try_get("feed_ids")?,
                    read_feed_ids: r.try_get("read_feed_ids")?,
                    previous_job_id: r.try_get("previous_job_id")?,
                    previous_cards,
                    params_version: r.try_get("params_version")?,
                    params,
                    created_at: r.try_get("created_at")?,
                }))
            }
            None => Ok(None),
        }
    }

    pub async fn insert_candidates(pool: &PgPool, candidates: &[RecapCardCandidate]) -> Result<()> {
        if candidates.is_empty() {
            return Ok(());
        }
        let mut tx = pool
            .begin()
            .await
            .map_err(|e| RecapError::Db(format!("failed to begin tx: {e}")))?;
        for c in candidates {
            sqlx::query(
                r"
                INSERT INTO recap_card_candidates (
                    id, job_id, rank, cluster_fingerprint, size,
                    domains, items, scores, centroid, created_at
                ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
                ",
            )
            .bind(c.id)
            .bind(c.job_id)
            .bind(c.rank)
            .bind(&c.cluster_fingerprint)
            .bind(c.size)
            .bind(Json(&c.domains))
            .bind(Json(&c.items))
            .bind(Json(&c.scores))
            .bind(c.centroid.as_deref())
            .bind(c.created_at)
            .execute(&mut *tx)
            .await
            .map_err(|e| RecapError::Db(format!("failed to insert candidate: {e}")))?;
        }
        tx.commit()
            .await
            .map_err(|e| RecapError::Db(format!("failed to commit candidates: {e}")))?;
        Ok(())
    }

    pub async fn get_candidates_for_job(
        pool: &PgPool,
        job_id: Uuid,
    ) -> Result<Vec<RecapCardCandidate>> {
        let rows = sqlx::query(
            r"
            SELECT id, job_id, rank, cluster_fingerprint, size,
                   domains, items, scores, centroid, created_at
            FROM recap_card_candidates
            WHERE job_id = $1
            ORDER BY rank ASC
            ",
        )
        .bind(job_id)
        .fetch_all(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to get candidates: {e}")))?;

        let mut res = Vec::with_capacity(rows.len());
        for r in rows {
            let domains: Value = r.try_get::<Json<Value>, _>("domains")?.0;
            let items: Value = r.try_get::<Json<Value>, _>("items")?.0;
            let scores: Value = r.try_get::<Json<Value>, _>("scores")?.0;
            res.push(RecapCardCandidate {
                id: r.try_get("id")?,
                job_id: r.try_get("job_id")?,
                rank: r.try_get("rank")?,
                cluster_fingerprint: r.try_get("cluster_fingerprint")?,
                size: r.try_get("size")?,
                domains,
                items,
                scores,
                centroid: r.try_get("centroid")?,
                created_at: r.try_get("created_at")?,
            });
        }
        Ok(res)
    }

    pub async fn get_candidates_for_window(
        pool: &PgPool,
        window_id: Uuid,
    ) -> Result<Vec<RecapCardCandidate>> {
        let rows = sqlx::query(
            r"
            SELECT c.id, c.job_id, c.rank, c.cluster_fingerprint, c.size,
                   c.domains, c.items, c.scores, c.centroid, c.created_at
            FROM recap_card_candidates c
            JOIN recap_eval_windows w ON c.job_id = w.snapshot_job_id
            WHERE w.id = $1
            ORDER BY c.rank ASC
            ",
        )
        .bind(window_id)
        .fetch_all(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to get candidates for window: {e}")))?;

        let mut res = Vec::with_capacity(rows.len());
        for r in rows {
            let domains: Value = r.try_get::<Json<Value>, _>("domains")?.0;
            let items: Value = r.try_get::<Json<Value>, _>("items")?.0;
            let scores: Value = r.try_get::<Json<Value>, _>("scores")?.0;
            res.push(RecapCardCandidate {
                id: r.try_get("id")?,
                job_id: r.try_get("job_id")?,
                rank: r.try_get("rank")?,
                cluster_fingerprint: r.try_get("cluster_fingerprint")?,
                size: r.try_get("size")?,
                domains,
                items,
                scores,
                centroid: r.try_get("centroid")?,
                created_at: r.try_get("created_at")?,
            });
        }
        Ok(res)
    }

    pub async fn insert_cards(pool: &PgPool, cards: &[RecapCard]) -> Result<()> {
        if cards.is_empty() {
            return Ok(());
        }
        let mut tx = pool
            .begin()
            .await
            .map_err(|e| RecapError::Db(format!("failed to begin tx: {e}")))?;
        for c in cards {
            sqlx::query(
                r"
                INSERT INTO recap_cards (
                    id, job_id, rank, story_id, continues_card_id, merged_from,
                    headline_ja, what_ja, why_ja, genre, member_feed_ids,
                    sources, centroid, scores, gates, generation, created_at
                ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
                ",
            )
            .bind(c.id)
            .bind(c.job_id)
            .bind(c.rank)
            .bind(c.story_id)
            .bind(c.continues_card_id)
            .bind(c.merged_from.as_deref())
            .bind(&c.headline_ja)
            .bind(&c.what_ja)
            .bind(c.why_ja.as_deref())
            .bind(c.genre.as_deref())
            .bind(&c.member_feed_ids)
            .bind(Json(&c.sources))
            .bind(c.centroid.as_deref())
            .bind(Json(&c.scores))
            .bind(Json(&c.gates))
            .bind(Json(&c.generation))
            .bind(c.created_at)
            .execute(&mut *tx)
            .await
            .map_err(|e| RecapError::Db(format!("failed to insert card: {e}")))?;
        }
        tx.commit()
            .await
            .map_err(|e| RecapError::Db(format!("failed to commit cards: {e}")))?;
        Ok(())
    }

    pub async fn get_cards_for_job(pool: &PgPool, job_id: Uuid) -> Result<Vec<RecapCard>> {
        let rows = sqlx::query(
            r"
            SELECT id, job_id, rank, story_id, continues_card_id, merged_from,
                   headline_ja, what_ja, why_ja, genre, member_feed_ids,
                   sources, centroid, scores, gates, generation, created_at
            FROM recap_cards
            WHERE job_id = $1
            ORDER BY rank ASC
            ",
        )
        .bind(job_id)
        .fetch_all(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to get cards for job: {e}")))?;

        let mut res = Vec::with_capacity(rows.len());
        for r in rows {
            let sources: Value = r.try_get::<Json<Value>, _>("sources")?.0;
            let scores: Value = r.try_get::<Json<Value>, _>("scores")?.0;
            let gates: Value = r.try_get::<Json<Value>, _>("gates")?.0;
            let generation: Value = r.try_get::<Json<Value>, _>("generation")?.0;
            res.push(RecapCard {
                id: r.try_get("id")?,
                job_id: r.try_get("job_id")?,
                rank: r.try_get("rank")?,
                story_id: r.try_get("story_id")?,
                continues_card_id: r.try_get("continues_card_id")?,
                merged_from: r.try_get("merged_from")?,
                headline_ja: r.try_get("headline_ja")?,
                what_ja: r.try_get("what_ja")?,
                why_ja: r.try_get("why_ja")?,
                genre: r.try_get("genre")?,
                member_feed_ids: r.try_get("member_feed_ids")?,
                sources,
                centroid: r.try_get("centroid")?,
                scores,
                gates,
                generation,
                created_at: r.try_get("created_at")?,
            });
        }
        Ok(res)
    }

    pub async fn insert_job_stats(pool: &PgPool, s: &RecapCardJobStats) -> Result<()> {
        sqlx::query(
            r"
            INSERT INTO recap_card_job_stats (
                job_id, items_fetched, items_after_noise, items_after_dedup,
                clusters, candidates, cards_selected, cards_dropped,
                embed_ms, cluster_ms, llm_ms, total_ms, params_version, params
            ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
            ",
        )
        .bind(s.job_id)
        .bind(s.items_fetched)
        .bind(s.items_after_noise)
        .bind(s.items_after_dedup)
        .bind(s.clusters)
        .bind(s.candidates)
        .bind(s.cards_selected)
        .bind(Json(&s.cards_dropped))
        .bind(s.embed_ms)
        .bind(s.cluster_ms)
        .bind(s.llm_ms)
        .bind(s.total_ms)
        .bind(&s.params_version)
        .bind(serde_json::json!({}))
        .execute(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to insert recap_card_job_stats: {e}")))?;
        Ok(())
    }

    pub async fn get_job_stats(pool: &PgPool, job_id: Uuid) -> Result<Option<RecapCardJobStats>> {
        let row = sqlx::query(
            r"
            SELECT job_id, items_fetched, items_after_noise, items_after_dedup,
                   clusters, candidates, cards_selected, cards_dropped,
                   embed_ms, cluster_ms, llm_ms, total_ms, params_version, created_at
            FROM recap_card_job_stats
            WHERE job_id = $1
            ",
        )
        .bind(job_id)
        .fetch_optional(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to get recap_card_job_stats: {e}")))?;

        match row {
            Some(r) => {
                let cards_dropped: Value = r.try_get::<Json<Value>, _>("cards_dropped")?.0;
                Ok(Some(RecapCardJobStats {
                    job_id: r.try_get("job_id")?,
                    items_fetched: r.try_get("items_fetched")?,
                    items_after_noise: r.try_get("items_after_noise")?,
                    items_after_dedup: r.try_get("items_after_dedup")?,
                    clusters: r.try_get("clusters")?,
                    candidates: r.try_get("candidates")?,
                    cards_selected: r.try_get("cards_selected")?,
                    cards_dropped,
                    embed_ms: r.try_get("embed_ms")?,
                    cluster_ms: r.try_get("cluster_ms")?,
                    llm_ms: r.try_get("llm_ms")?,
                    total_ms: r.try_get("total_ms")?,
                    params_version: r.try_get("params_version")?,
                    created_at: r.try_get("created_at")?,
                }))
            }
            None => Ok(None),
        }
    }

    pub async fn insert_eval_window(pool: &PgPool, w: &RecapEvalWindow) -> Result<()> {
        sqlx::query(
            r"
            INSERT INTO recap_eval_windows (
                id, from_ts, to_ts, snapshot_job_id, created_at
            ) VALUES ($1, $2, $3, $4, $5)
            ",
        )
        .bind(w.id)
        .bind(w.from_ts)
        .bind(w.to_ts)
        .bind(w.snapshot_job_id)
        .bind(w.created_at)
        .execute(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to insert eval_window: {e}")))?;
        Ok(())
    }

    pub async fn get_eval_window(
        pool: &PgPool,
        window_id: Uuid,
    ) -> Result<Option<RecapEvalWindow>> {
        let row = sqlx::query(
            r"
            SELECT id, from_ts, to_ts, snapshot_job_id, created_at
            FROM recap_eval_windows
            WHERE id = $1
            ",
        )
        .bind(window_id)
        .fetch_optional(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to get eval_window: {e}")))?;

        match row {
            Some(r) => Ok(Some(RecapEvalWindow {
                id: r.try_get("id")?,
                from_ts: r.try_get("from_ts")?,
                to_ts: r.try_get("to_ts")?,
                snapshot_job_id: r.try_get("snapshot_job_id")?,
                created_at: r.try_get("created_at")?,
            })),
            None => Ok(None),
        }
    }

    pub async fn list_eval_windows(pool: &PgPool) -> Result<Vec<RecapEvalWindowSummary>> {
        let rows = sqlx::query(
            r"
            SELECT
                w.id,
                w.from_ts,
                w.to_ts,
                w.snapshot_job_id,
                w.created_at,
                COALESCE((
                    SELECT COUNT(*)::bigint
                    FROM recap_card_candidates c
                    WHERE c.job_id = w.snapshot_job_id
                ), 0) AS candidate_count,
                COALESCE((
                    SELECT COUNT(DISTINCT j.cluster_fingerprint)::bigint
                    FROM recap_story_judgments j
                    WHERE j.window_id = w.id
                ), 0) AS judged_count
            FROM recap_eval_windows w
            ORDER BY w.created_at DESC
            ",
        )
        .fetch_all(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to list eval_windows: {e}")))?;

        let mut res = Vec::with_capacity(rows.len());
        for r in rows {
            res.push(RecapEvalWindowSummary {
                id: r.try_get("id")?,
                from_ts: r.try_get("from_ts")?,
                to_ts: r.try_get("to_ts")?,
                snapshot_job_id: r.try_get("snapshot_job_id")?,
                created_at: r.try_get("created_at")?,
                candidate_count: r.try_get("candidate_count")?,
                judged_count: r.try_get("judged_count")?,
            });
        }
        Ok(res)
    }

    pub async fn insert_story_judgment(pool: &PgPool, j: &RecapStoryJudgment) -> Result<()> {
        if !is_valid_decision(&j.decision) {
            return Err(RecapError::Db(format!(
                "invalid judgment decision '{}': must be 'top', 'not_top', or 'noise'",
                j.decision
            )));
        }
        sqlx::query(
            r"
            INSERT INTO recap_story_judgments (
                id, window_id, cluster_fingerprint, decision, rated_at
            ) VALUES ($1, $2, $3, $4, $5)
            ",
        )
        .bind(j.id)
        .bind(j.window_id)
        .bind(&j.cluster_fingerprint)
        .bind(&j.decision)
        .bind(j.rated_at)
        .execute(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to insert story_judgment: {e}")))?;
        Ok(())
    }

    pub async fn latest_judgments_for_window(
        pool: &PgPool,
        window_id: Uuid,
    ) -> Result<Vec<RecapStoryJudgment>> {
        let rows = sqlx::query(
            r"
            SELECT DISTINCT ON (cluster_fingerprint)
                id, window_id, cluster_fingerprint, decision, rated_at
            FROM recap_story_judgments
            WHERE window_id = $1
            ORDER BY cluster_fingerprint, rated_at DESC
            ",
        )
        .bind(window_id)
        .fetch_all(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to get latest judgments: {e}")))?;

        let mut res = Vec::with_capacity(rows.len());
        for r in rows {
            res.push(RecapStoryJudgment {
                id: r.try_get("id")?,
                window_id: r.try_get("window_id")?,
                cluster_fingerprint: r.try_get("cluster_fingerprint")?,
                decision: r.try_get("decision")?,
                rated_at: r.try_get("rated_at")?,
            });
        }
        Ok(res)
    }

    pub async fn insert_card_rating(pool: &PgPool, r: &RecapCardRating) -> Result<()> {
        if !is_valid_score(r.score) {
            return Err(RecapError::Db(format!(
                "invalid rating score {}: must be between 0 and 2",
                r.score
            )));
        }
        sqlx::query(
            r"
            INSERT INTO recap_card_ratings (
                id, card_id, score, flags, comment, rated_at
            ) VALUES ($1, $2, $3, $4, $5, $6)
            ",
        )
        .bind(r.id)
        .bind(r.card_id)
        .bind(r.score)
        .bind(&r.flags)
        .bind(r.comment.as_deref())
        .bind(r.rated_at)
        .execute(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to insert card_rating: {e}")))?;
        Ok(())
    }

    pub async fn latest_rating_per_card(
        pool: &PgPool,
        job_id: Uuid,
    ) -> Result<Vec<RecapCardRating>> {
        let rows = sqlx::query(
            r"
            SELECT DISTINCT ON (r.card_id)
                r.id, r.card_id, r.score, r.flags, r.comment, r.rated_at
            FROM recap_card_ratings r
            JOIN recap_cards c ON r.card_id = c.id
            WHERE c.job_id = $1
            ORDER BY r.card_id, r.rated_at DESC
            ",
        )
        .bind(job_id)
        .fetch_all(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to get latest rating per card: {e}")))?;

        let mut res = Vec::with_capacity(rows.len());
        for r in rows {
            res.push(RecapCardRating {
                id: r.try_get("id")?,
                card_id: r.try_get("card_id")?,
                score: r.try_get("score")?,
                flags: r.try_get("flags")?,
                comment: r.try_get("comment")?,
                rated_at: r.try_get("rated_at")?,
            });
        }
        Ok(res)
    }

    pub async fn list_cards_jobs(pool: &PgPool, limit: i64) -> Result<Vec<CardsJobSummary>> {
        let rows = sqlx::query(
            r"
            SELECT
                j.job_id,
                j.status,
                j.trigger_source,
                j.kicked_at,
                COALESCE((
                    SELECT COUNT(*)::bigint
                    FROM recap_cards c
                    WHERE c.job_id = j.job_id
                ), 0) AS card_count,
                COALESCE((
                    SELECT COUNT(DISTINCT r.card_id)::bigint
                    FROM recap_card_ratings r
                    JOIN recap_cards c ON r.card_id = c.id
                    WHERE c.job_id = j.job_id
                ), 0) AS rated_count
            FROM recap_jobs j
            WHERE j.trigger_source IN ('cards', 'cards_replay')
            ORDER BY j.kicked_at DESC
            LIMIT $1
            ",
        )
        .bind(limit)
        .fetch_all(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to list cards jobs: {e}")))?;

        let mut res = Vec::with_capacity(rows.len());
        for r in rows {
            res.push(CardsJobSummary {
                job_id: r.try_get("job_id")?,
                status: r.try_get("status")?,
                trigger_source: r.try_get("trigger_source")?,
                kicked_at: r.try_get("kicked_at")?,
                card_count: r.try_get("card_count")?,
                rated_count: r.try_get("rated_count")?,
            });
        }
        Ok(res)
    }

    /// Retrieve the latest completed cards job and its card centroids for novelty comparison.
    pub async fn get_latest_completed_cards_job(pool: &PgPool) -> Result<Option<PreviousCardsJob>> {
        let job_row = sqlx::query(
            r"
            SELECT j.job_id, s.to_ts
            FROM recap_jobs j
            JOIN recap_card_snapshots s ON s.job_id = j.job_id
            WHERE j.trigger_source = 'cards'
              AND j.status = 'completed'
            ORDER BY j.kicked_at DESC
            LIMIT 1
            ",
        )
        .fetch_optional(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to get latest completed cards job: {e}")))?;

        let Some(job_row) = job_row else {
            return Ok(None);
        };

        let job_id: Uuid = job_row.try_get("job_id")?;
        let to_ts: DateTime<Utc> = job_row.try_get("to_ts")?;

        let card_rows = sqlx::query(
            r"
            SELECT id, story_id, centroid
            FROM recap_cards
            WHERE job_id = $1
            ORDER BY rank ASC
            ",
        )
        .bind(job_id)
        .fetch_all(pool)
        .await
        .map_err(|e| {
            RecapError::Db(format!(
                "failed to get cards for previous job {job_id}: {e}"
            ))
        })?;

        let mut cards = Vec::with_capacity(card_rows.len());
        for r in card_rows {
            let centroid: Option<Vec<f32>> = r.try_get("centroid")?;
            if let Some(c) = centroid {
                cards.push(PreviousCardSummary {
                    id: r.try_get("id")?,
                    story_id: r.try_get("story_id")?,
                    centroid: c,
                });
            }
        }

        Ok(Some(PreviousCardsJob {
            job_id,
            to_ts,
            cards,
        }))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_decision_validation() {
        assert!(is_valid_decision("top"));
        assert!(is_valid_decision("not_top"));
        assert!(is_valid_decision("noise"));
        assert!(!is_valid_decision("invalid"));
        assert!(!is_valid_decision(""));
    }

    #[test]
    fn test_score_validation() {
        assert!(is_valid_score(0));
        assert!(is_valid_score(1));
        assert!(is_valid_score(2));
        assert!(!is_valid_score(-1));
        assert!(!is_valid_score(3));
    }

    #[test]
    fn test_serialization_roundtrip() {
        let candidate = RecapCardCandidate {
            id: Uuid::new_v4(),
            job_id: Uuid::new_v4(),
            rank: 1,
            cluster_fingerprint: "fp-1".to_string(),
            size: 3,
            domains: serde_json::json!([{"host": "example.com", "count": 2}]),
            items: serde_json::json!([{"feed_id": Uuid::new_v4(), "title": "test"}]),
            scores: serde_json::json!({"corroboration": 1.2}),
            centroid: Some(vec![0.1, 0.2, 0.3]),
            created_at: Utc::now(),
        };

        let json = serde_json::to_string(&candidate).expect("serialize candidate");
        let deserialized: RecapCardCandidate =
            serde_json::from_str(&json).expect("deserialize candidate");
        assert_eq!(candidate.id, deserialized.id);
        assert_eq!(candidate.rank, deserialized.rank);
        assert_eq!(
            candidate.cluster_fingerprint,
            deserialized.cluster_fingerprint
        );
    }

    #[test]
    fn test_previous_cards_job_serialization() {
        let prev = PreviousCardsJob {
            job_id: Uuid::new_v4(),
            to_ts: Utc::now(),
            cards: vec![PreviousCardSummary {
                id: Uuid::new_v4(),
                story_id: Uuid::new_v4(),
                centroid: vec![0.1, 0.2, 0.3],
            }],
        };

        let json = serde_json::to_string(&prev).expect("serialize prev");
        let deserialized: PreviousCardsJob = serde_json::from_str(&json).expect("deserialize prev");
        assert_eq!(prev.job_id, deserialized.job_id);
        assert_eq!(prev.cards.len(), deserialized.cards.len());
        assert_eq!(prev.cards[0].id, deserialized.cards[0].id);
        assert_eq!(prev.cards[0].story_id, deserialized.cards[0].story_id);
        assert_eq!(prev.cards[0].centroid, deserialized.cards[0].centroid);
    }
}
