//! Topic cards and evaluation DAO for 3-day recap redesign.
//!
//! All tables are INSERT-only: snapshots, candidates, cards, job_stats,
//! eval_windows, story_judgments, and card_ratings.

use crate::error::{RecapError, Result};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sqlx::types::Json;
use sqlx::{PgPool, Row};
use std::collections::HashMap;
use uuid::Uuid;

/// 1. Snapshot of input state frozen at job execution time (reproject-safe).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecapCardSnapshot {
    pub job_id: Uuid,
    pub from_ts: DateTime<Utc>,
    pub to_ts: DateTime<Utc>,
    pub feed_ids: Vec<Uuid>,
    pub read_feed_ids: Vec<Uuid>,
    pub previous_job_id: Option<Uuid>,
    pub previous_cards: Value,
    pub params_version: String,
    pub params: Value,
    pub created_at: DateTime<Utc>,
}

/// 2. Candidates produced by selection phase prior to LLM generation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecapCardCandidate {
    pub id: Uuid,
    pub job_id: Uuid,
    pub rank: i32,
    pub cluster_fingerprint: String,
    pub size: i32,
    pub domains: Value,
    pub items: Value,
    pub scores: Value,
    pub centroid: Option<Vec<f32>>,
    pub member_feed_ids: Vec<Uuid>,
    pub created_at: DateTime<Utc>,
}

/// 3. Versioned topic cards selected and generated by recap pipeline.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecapCard {
    pub id: Uuid,
    pub job_id: Uuid,
    pub rank: i32,
    pub story_id: Uuid,
    pub continues_card_id: Option<Uuid>,
    /// Previous card IDs merged into this continuation (same ID space as continues_card_id).
    pub merged_from: Option<Vec<Uuid>>,
    pub headline_ja: String,
    pub what_ja: String,
    pub why_ja: Option<String>,
    pub genre: Option<String>,
    pub member_feed_ids: Vec<Uuid>,
    pub sources: Value,
    pub centroid: Option<Vec<f32>>,
    pub scores: Value,
    pub gates: Value,
    pub generation: Value,
    pub created_at: DateTime<Utc>,
}

/// 4. Pipeline execution stats and gate drop metrics.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecapCardJobStats {
    pub job_id: Uuid,
    pub items_fetched: i32,
    pub items_after_noise: i32,
    pub items_after_dedup: i32,
    pub clusters: i32,
    pub candidates: i32,
    pub cards_selected: i32,
    pub cards_dropped: Value,
    pub embed_ms: i64,
    pub cluster_ms: i64,
    pub llm_ms: i64,
    pub total_ms: i64,
    pub params_version: String,
    #[serde(default)]
    pub embed_cache_hits: usize,
    #[serde(default)]
    pub embed_cache_misses: usize,
    pub created_at: DateTime<Utc>,
}

/// 5. Evaluation windows referencing replay snapshots.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecapEvalWindow {
    pub id: Uuid,
    pub from_ts: DateTime<Utc>,
    pub to_ts: DateTime<Utc>,
    pub snapshot_job_id: Uuid,
    pub created_at: DateTime<Utc>,
}

/// Evaluation window with aggregate candidate and judgment counts.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecapEvalWindowSummary {
    pub id: Uuid,
    pub from_ts: DateTime<Utc>,
    pub to_ts: DateTime<Utc>,
    pub snapshot_job_id: Uuid,
    pub created_at: DateTime<Utc>,
    pub candidate_count: i64,
    pub judged_count: i64,
    pub params_version: String,
}

/// 6. Human golden judgments on candidate clusters (top / not_top / noise).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecapStoryJudgment {
    pub id: Uuid,
    pub window_id: Uuid,
    pub cluster_fingerprint: String,
    pub decision: String,
    pub rated_at: DateTime<Utc>,
}

/// 7. Human ratings on generated topic cards (0/1/2 + defect flags + comment).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecapCardRating {
    pub id: Uuid,
    pub card_id: Uuid,
    pub score: i16,
    pub flags: Vec<String>,
    pub comment: Option<String>,
    pub rated_at: DateTime<Utc>,
}

/// Summary of a cards job from recap_jobs with aggregate card and rating counts.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CardsJobSummary {
    pub job_id: Uuid,
    pub status: String,
    pub trigger_source: String,
    pub kicked_at: DateTime<Utc>,
    pub card_count: i64,
    pub rated_count: i64,
}

/// Summary of a previous card for novelty matching and continuation tracking.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PreviousCardSummary {
    pub id: Uuid,
    pub story_id: Uuid,
    pub centroid: Vec<f32>,
}

/// Metadata about the latest completed cards job.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PreviousCardsJobMeta {
    pub job_id: Uuid,
    pub kicked_at: DateTime<Utc>,
    pub from_ts: DateTime<Utc>,
    pub to_ts: DateTime<Utc>,
    pub params_version: String,
}

/// Information about the latest completed cards job and its cards.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PreviousCardsJob {
    pub job_id: Uuid,
    pub kicked_at: DateTime<Utc>,
    pub from_ts: DateTime<Utc>,
    pub to_ts: DateTime<Utc>,
    pub params_version: String,
    pub cards: Vec<PreviousCardSummary>,
}

/// Pure validation helper for judgment decisions.
#[must_use]
pub fn is_valid_decision(decision: &str) -> bool {
    matches!(decision, "top" | "not_top" | "noise")
}

/// Pure validation helper for card rating scores (0, 1, 2).
#[must_use]
pub fn is_valid_score(score: i16) -> bool {
    (0..=2).contains(&score)
}

pub struct CardsDaoOps;

impl CardsDaoOps {
    pub async fn get_candidates_for_window(
        pool: &PgPool,
        window_id: Uuid,
    ) -> Result<Vec<RecapCardCandidate>> {
        let rows = sqlx::query(
            r"
            SELECT c.id, c.job_id, c.rank, c.cluster_fingerprint, c.size,
                   c.domains, c.items, c.scores, c.centroid, c.member_feed_ids, c.created_at
            FROM recap_card_candidates c
            JOIN recap_eval_windows w ON c.job_id = w.snapshot_job_id
            WHERE w.id = $1
            ORDER BY c.rank ASC
            ",
        )
        .bind(window_id)
        .fetch_all(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to get candidates for window: {e}")))?;

        let mut res = Vec::with_capacity(rows.len());
        for r in rows {
            let domains: Value = r.try_get::<Json<Value>, _>("domains")?.0;
            let items: Value = r.try_get::<Json<Value>, _>("items")?.0;
            let scores: Value = r.try_get::<Json<Value>, _>("scores")?.0;
            let member_feed_ids: Vec<Uuid> = r.try_get("member_feed_ids")?;
            res.push(RecapCardCandidate {
                id: r.try_get("id")?,
                job_id: r.try_get("job_id")?,
                rank: r.try_get("rank")?,
                cluster_fingerprint: r.try_get("cluster_fingerprint")?,
                size: r.try_get("size")?,
                domains,
                items,
                scores,
                centroid: r.try_get("centroid")?,
                member_feed_ids,
                created_at: r.try_get("created_at")?,
            });
        }
        Ok(res)
    }

    pub async fn get_cards_for_job(pool: &PgPool, job_id: Uuid) -> Result<Vec<RecapCard>> {
        let rows = sqlx::query(
            r"
            SELECT id, job_id, rank, story_id, continues_card_id, merged_from,
                   headline_ja, what_ja, why_ja, genre, member_feed_ids,
                   sources, centroid, scores, gates, generation, created_at
            FROM recap_cards
            WHERE job_id = $1
            ORDER BY rank ASC
            ",
        )
        .bind(job_id)
        .fetch_all(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to get cards for job: {e}")))?;

        let mut res = Vec::with_capacity(rows.len());
        for r in rows {
            let sources: Value = r.try_get::<Json<Value>, _>("sources")?.0;
            let scores: Value = r.try_get::<Json<Value>, _>("scores")?.0;
            let gates: Value = r.try_get::<Json<Value>, _>("gates")?.0;
            let generation: Value = r.try_get::<Json<Value>, _>("generation")?.0;
            res.push(RecapCard {
                id: r.try_get("id")?,
                job_id: r.try_get("job_id")?,
                rank: r.try_get("rank")?,
                story_id: r.try_get("story_id")?,
                continues_card_id: r.try_get("continues_card_id")?,
                merged_from: r.try_get("merged_from")?,
                headline_ja: r.try_get("headline_ja")?,
                what_ja: r.try_get("what_ja")?,
                why_ja: r.try_get("why_ja")?,
                genre: r.try_get("genre")?,
                member_feed_ids: r.try_get("member_feed_ids")?,
                sources,
                centroid: r.try_get("centroid")?,
                scores,
                gates,
                generation,
                created_at: r.try_get("created_at")?,
            });
        }
        Ok(res)
    }

    pub async fn get_job_stats(pool: &PgPool, job_id: Uuid) -> Result<Option<RecapCardJobStats>> {
        let row = sqlx::query(
            r"
            SELECT job_id, items_fetched, items_after_noise, items_after_dedup,
                   clusters, candidates, cards_selected, cards_dropped,
                   embed_ms, cluster_ms, llm_ms, total_ms, params_version,
                   embed_cache_hits, embed_cache_misses, created_at
            FROM recap_card_job_stats
            WHERE job_id = $1
            ",
        )
        .bind(job_id)
        .fetch_optional(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to get recap_card_job_stats: {e}")))?;

        match row {
            Some(r) => {
                let cards_dropped: Value = r.try_get::<Json<Value>, _>("cards_dropped")?.0;
                let embed_cache_hits_i32: i32 = r.try_get("embed_cache_hits")?;
                let embed_cache_misses_i32: i32 = r.try_get("embed_cache_misses")?;
                Ok(Some(RecapCardJobStats {
                    job_id: r.try_get("job_id")?,
                    items_fetched: r.try_get("items_fetched")?,
                    items_after_noise: r.try_get("items_after_noise")?,
                    items_after_dedup: r.try_get("items_after_dedup")?,
                    clusters: r.try_get("clusters")?,
                    candidates: r.try_get("candidates")?,
                    cards_selected: r.try_get("cards_selected")?,
                    cards_dropped,
                    embed_ms: r.try_get("embed_ms")?,
                    cluster_ms: r.try_get("cluster_ms")?,
                    llm_ms: r.try_get("llm_ms")?,
                    total_ms: r.try_get("total_ms")?,
                    params_version: r.try_get("params_version")?,
                    embed_cache_hits: usize::try_from(embed_cache_hits_i32).unwrap_or(0),
                    embed_cache_misses: usize::try_from(embed_cache_misses_i32).unwrap_or(0),
                    created_at: r.try_get("created_at")?,
                }))
            }
            None => Ok(None),
        }
    }

    pub async fn get_eval_window(
        pool: &PgPool,
        window_id: Uuid,
    ) -> Result<Option<RecapEvalWindow>> {
        let row = sqlx::query(
            r"
            SELECT id, from_ts, to_ts, snapshot_job_id, created_at
            FROM recap_eval_windows
            WHERE id = $1
            ",
        )
        .bind(window_id)
        .fetch_optional(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to get eval_window: {e}")))?;

        match row {
            Some(r) => Ok(Some(RecapEvalWindow {
                id: r.try_get("id")?,
                from_ts: r.try_get("from_ts")?,
                to_ts: r.try_get("to_ts")?,
                snapshot_job_id: r.try_get("snapshot_job_id")?,
                created_at: r.try_get("created_at")?,
            })),
            None => Ok(None),
        }
    }

    pub async fn list_eval_windows(pool: &PgPool) -> Result<Vec<RecapEvalWindowSummary>> {
        let rows = sqlx::query(
            r"
            SELECT
                w.id,
                w.from_ts,
                w.to_ts,
                w.snapshot_job_id,
                w.created_at,
                COALESCE(s.params_version, snap.params_version, '') AS params_version,
                COALESCE((
                    SELECT COUNT(*)::bigint
                    FROM recap_card_candidates c
                    WHERE c.job_id = w.snapshot_job_id
                ), 0) AS candidate_count,
                COALESCE((
                    SELECT COUNT(DISTINCT j.cluster_fingerprint)::bigint
                    FROM recap_story_judgments j
                    WHERE j.window_id = w.id
                ), 0) AS judged_count
            FROM recap_eval_windows w
            LEFT JOIN recap_card_job_stats s ON s.job_id = w.snapshot_job_id
            LEFT JOIN recap_card_snapshots snap ON snap.job_id = w.snapshot_job_id
            ORDER BY w.created_at DESC
            ",
        )
        .fetch_all(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to list eval_windows: {e}")))?;

        let mut res = Vec::with_capacity(rows.len());
        for r in rows {
            res.push(RecapEvalWindowSummary {
                id: r.try_get("id")?,
                from_ts: r.try_get("from_ts")?,
                to_ts: r.try_get("to_ts")?,
                snapshot_job_id: r.try_get("snapshot_job_id")?,
                created_at: r.try_get("created_at")?,
                candidate_count: r.try_get("candidate_count")?,
                judged_count: r.try_get("judged_count")?,
                params_version: r.try_get("params_version")?,
            });
        }
        Ok(res)
    }

    pub async fn insert_story_judgment(pool: &PgPool, j: &RecapStoryJudgment) -> Result<()> {
        if !is_valid_decision(&j.decision) {
            return Err(RecapError::Db(format!(
                "invalid judgment decision '{}': must be 'top', 'not_top', or 'noise'",
                j.decision
            )));
        }
        sqlx::query(
            r"
            INSERT INTO recap_story_judgments (
                id, window_id, cluster_fingerprint, decision, rated_at
            ) VALUES ($1, $2, $3, $4, $5)
            ",
        )
        .bind(j.id)
        .bind(j.window_id)
        .bind(&j.cluster_fingerprint)
        .bind(&j.decision)
        .bind(j.rated_at)
        .execute(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to insert story_judgment: {e}")))?;
        Ok(())
    }

    pub async fn latest_judgments_for_window(
        pool: &PgPool,
        window_id: Uuid,
    ) -> Result<Vec<RecapStoryJudgment>> {
        let rows = sqlx::query(
            r"
            SELECT DISTINCT ON (cluster_fingerprint)
                id, window_id, cluster_fingerprint, decision, rated_at
            FROM recap_story_judgments
            WHERE window_id = $1
            ORDER BY cluster_fingerprint, rated_at DESC, id DESC
            ",
        )
        .bind(window_id)
        .fetch_all(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to get latest judgments: {e}")))?;

        let mut res = Vec::with_capacity(rows.len());
        for r in rows {
            res.push(RecapStoryJudgment {
                id: r.try_get("id")?,
                window_id: r.try_get("window_id")?,
                cluster_fingerprint: r.try_get("cluster_fingerprint")?,
                decision: r.try_get("decision")?,
                rated_at: r.try_get("rated_at")?,
            });
        }
        Ok(res)
    }

    /// Retrieve the latest story judgment per cluster across all eval windows covering [from_ts, to_ts).
    /// Optionally excludes a given window_id (e.g., the window currently being evaluated).
    pub async fn latest_judgments_for_date_range(
        pool: &PgPool,
        from_ts: DateTime<Utc>,
        to_ts: DateTime<Utc>,
        exclude_window_id: Option<Uuid>,
    ) -> Result<Vec<RecapStoryJudgment>> {
        let rows = sqlx::query(
            r"
            SELECT DISTINCT ON (j.window_id, j.cluster_fingerprint)
                j.id, j.window_id, j.cluster_fingerprint, j.decision, j.rated_at
            FROM recap_story_judgments j
            JOIN recap_eval_windows w ON j.window_id = w.id
            WHERE w.from_ts = $1 AND w.to_ts = $2
              AND ($3::uuid IS NULL OR w.id != $3)
            ORDER BY j.window_id, j.cluster_fingerprint, j.rated_at DESC, j.id DESC
            ",
        )
        .bind(from_ts)
        .bind(to_ts)
        .bind(exclude_window_id)
        .fetch_all(pool)
        .await
        .map_err(|e| {
            RecapError::Db(format!(
                "failed to get latest judgments for date range: {e}"
            ))
        })?;

        let mut res = Vec::with_capacity(rows.len());
        for r in rows {
            res.push(RecapStoryJudgment {
                id: r.try_get("id")?,
                window_id: r.try_get("window_id")?,
                cluster_fingerprint: r.try_get("cluster_fingerprint")?,
                decision: r.try_get("decision")?,
                rated_at: r.try_get("rated_at")?,
            });
        }
        Ok(res)
    }

    /// Retrieve all candidate clusters across eval windows covering [from_ts, to_ts).
    /// Optionally excludes a given window_id.
    pub async fn get_candidates_for_date_range(
        pool: &PgPool,
        from_ts: DateTime<Utc>,
        to_ts: DateTime<Utc>,
        exclude_window_id: Option<Uuid>,
    ) -> Result<Vec<RecapCardCandidate>> {
        let rows = sqlx::query(
            r"
            SELECT c.id, c.job_id, c.rank, c.cluster_fingerprint, c.size,
                   c.domains, c.items, c.scores, c.member_feed_ids, c.created_at
            FROM recap_card_candidates c
            JOIN recap_eval_windows w ON c.job_id = w.snapshot_job_id
            WHERE w.from_ts = $1 AND w.to_ts = $2
              AND ($3::uuid IS NULL OR w.id != $3)
            ORDER BY w.created_at DESC, c.rank ASC
            ",
        )
        .bind(from_ts)
        .bind(to_ts)
        .bind(exclude_window_id)
        .fetch_all(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to get candidates for date range: {e}")))?;

        let mut res = Vec::with_capacity(rows.len());
        for r in rows {
            let domains: Value = r.try_get::<Json<Value>, _>("domains")?.0;
            let items: Value = r.try_get::<Json<Value>, _>("items")?.0;
            let scores: Value = r.try_get::<Json<Value>, _>("scores")?.0;
            let member_feed_ids: Vec<Uuid> = r.try_get("member_feed_ids")?;
            res.push(RecapCardCandidate {
                id: r.try_get("id")?,
                job_id: r.try_get("job_id")?,
                rank: r.try_get("rank")?,
                cluster_fingerprint: r.try_get("cluster_fingerprint")?,
                size: r.try_get("size")?,
                domains,
                items,
                scores,
                centroid: None,
                member_feed_ids,
                created_at: r.try_get("created_at")?,
            });
        }
        Ok(res)
    }

    /// Retrieve all eval windows covering the given [from_ts, to_ts) range, newest first.
    pub async fn get_eval_windows_for_date_range(
        pool: &PgPool,
        from_ts: DateTime<Utc>,
        to_ts: DateTime<Utc>,
    ) -> Result<Vec<RecapEvalWindow>> {
        let rows = sqlx::query(
            r"
            SELECT id, from_ts, to_ts, snapshot_job_id, created_at
            FROM recap_eval_windows
            WHERE from_ts = $1 AND to_ts = $2
            ORDER BY created_at DESC
            ",
        )
        .bind(from_ts)
        .bind(to_ts)
        .fetch_all(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to get eval windows for date range: {e}")))?;

        let mut res = Vec::with_capacity(rows.len());
        for r in rows {
            res.push(RecapEvalWindow {
                id: r.try_get("id")?,
                from_ts: r.try_get("from_ts")?,
                to_ts: r.try_get("to_ts")?,
                snapshot_job_id: r.try_get("snapshot_job_id")?,
                created_at: r.try_get("created_at")?,
            });
        }
        Ok(res)
    }

    pub async fn insert_card_rating(pool: &PgPool, r: &RecapCardRating) -> Result<()> {
        if !is_valid_score(r.score) {
            return Err(RecapError::Db(format!(
                "invalid rating score {}: must be between 0 and 2",
                r.score
            )));
        }
        sqlx::query(
            r"
            INSERT INTO recap_card_ratings (
                id, card_id, score, flags, comment, rated_at
            ) VALUES ($1, $2, $3, $4, $5, $6)
            ",
        )
        .bind(r.id)
        .bind(r.card_id)
        .bind(r.score)
        .bind(&r.flags)
        .bind(r.comment.as_deref())
        .bind(r.rated_at)
        .execute(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to insert card_rating: {e}")))?;
        Ok(())
    }

    pub async fn latest_rating_per_card(
        pool: &PgPool,
        job_id: Uuid,
    ) -> Result<Vec<RecapCardRating>> {
        let rows = sqlx::query(
            r"
            SELECT DISTINCT ON (r.card_id)
                r.id, r.card_id, r.score, r.flags, r.comment, r.rated_at
            FROM recap_card_ratings r
            JOIN recap_cards c ON r.card_id = c.id
            WHERE c.job_id = $1
            ORDER BY r.card_id, r.rated_at DESC, r.id DESC
            ",
        )
        .bind(job_id)
        .fetch_all(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to get latest rating per card: {e}")))?;

        let mut res = Vec::with_capacity(rows.len());
        for r in rows {
            res.push(RecapCardRating {
                id: r.try_get("id")?,
                card_id: r.try_get("card_id")?,
                score: r.try_get("score")?,
                flags: r.try_get("flags")?,
                comment: r.try_get("comment")?,
                rated_at: r.try_get("rated_at")?,
            });
        }
        Ok(res)
    }

    pub async fn list_cards_jobs(pool: &PgPool, limit: i64) -> Result<Vec<CardsJobSummary>> {
        let rows = sqlx::query(
            r"
            SELECT
                j.job_id,
                j.status,
                j.trigger_source,
                j.kicked_at,
                COALESCE((
                    SELECT COUNT(*)::bigint
                    FROM recap_cards c
                    WHERE c.job_id = j.job_id
                ), 0) AS card_count,
                COALESCE((
                    SELECT COUNT(DISTINCT r.card_id)::bigint
                    FROM recap_card_ratings r
                    JOIN recap_cards c ON r.card_id = c.id
                    WHERE c.job_id = j.job_id
                ), 0) AS rated_count
            FROM recap_jobs j
            WHERE j.trigger_source IN ('cards', 'cards_replay')
            ORDER BY j.kicked_at DESC
            LIMIT $1
            ",
        )
        .bind(limit)
        .fetch_all(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to list cards jobs: {e}")))?;

        let mut res = Vec::with_capacity(rows.len());
        for r in rows {
            res.push(CardsJobSummary {
                job_id: r.try_get("job_id")?,
                status: r.try_get("status")?,
                trigger_source: r.try_get("trigger_source")?,
                kicked_at: r.try_get("kicked_at")?,
                card_count: r.try_get("card_count")?,
                rated_count: r.try_get("rated_count")?,
            });
        }
        Ok(res)
    }

    /// Retrieve the latest completed cards job metadata.
    pub async fn get_latest_completed_cards_job_meta(
        pool: &PgPool,
    ) -> Result<Option<PreviousCardsJobMeta>> {
        let job_row = sqlx::query(
            r"
            SELECT j.job_id, j.kicked_at, s.from_ts, s.to_ts, s.params_version
            FROM recap_jobs j
            JOIN recap_card_snapshots s ON s.job_id = j.job_id
            WHERE j.trigger_source = 'cards'
              AND j.status = 'completed'
            ORDER BY j.kicked_at DESC
            LIMIT 1
            ",
        )
        .fetch_optional(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to get latest completed cards job: {e}")))?;

        let Some(job_row) = job_row else {
            return Ok(None);
        };

        Ok(Some(PreviousCardsJobMeta {
            job_id: job_row.try_get("job_id")?,
            kicked_at: job_row.try_get("kicked_at")?,
            from_ts: job_row.try_get("from_ts")?,
            to_ts: job_row.try_get("to_ts")?,
            params_version: job_row.try_get("params_version")?,
        }))
    }

    /// Retrieve the latest completed cards job and its card centroids for novelty comparison.
    pub async fn get_latest_completed_cards_job(pool: &PgPool) -> Result<Option<PreviousCardsJob>> {
        let Some(meta) = Self::get_latest_completed_cards_job_meta(pool).await? else {
            return Ok(None);
        };

        let card_rows = sqlx::query(
            r"
            SELECT id, story_id, centroid
            FROM recap_cards
            WHERE job_id = $1
            ORDER BY rank ASC
            ",
        )
        .bind(meta.job_id)
        .fetch_all(pool)
        .await
        .map_err(|e| {
            RecapError::Db(format!(
                "failed to get cards for previous job {}: {e}",
                meta.job_id
            ))
        })?;

        let raw_rows = card_rows
            .into_iter()
            .map(|r| {
                Ok((
                    r.try_get("id")?,
                    r.try_get("story_id")?,
                    r.try_get("centroid")?,
                ))
            })
            .collect::<std::result::Result<Vec<(Uuid, Uuid, Option<Vec<f32>>)>, sqlx::Error>>()
            .map_err(|e| RecapError::Db(format!("failed to parse previous cards rows: {e}")))?;

        let (cards, _) = parse_previous_card_rows(meta.job_id, raw_rows);

        Ok(Some(PreviousCardsJob {
            job_id: meta.job_id,
            kicked_at: meta.kicked_at,
            from_ts: meta.from_ts,
            to_ts: meta.to_ts,
            params_version: meta.params_version,
            cards,
        }))
    }

    /// Retrieve cached embeddings by model and text hashes.
    pub async fn get_cached_embeddings(
        pool: &PgPool,
        model: &str,
        text_hashes: &[String],
    ) -> Result<HashMap<String, Vec<f32>>> {
        if text_hashes.is_empty() {
            return Ok(HashMap::new());
        }

        let rows = sqlx::query(
            r"
            SELECT text_hash, model, dim, embedding
            FROM recap_card_embeddings
            WHERE model = $1 AND text_hash = ANY($2)
            ",
        )
        .bind(model)
        .bind(text_hashes)
        .fetch_all(pool)
        .await
        .map_err(|e| RecapError::Db(format!("failed to get cached embeddings: {e}")))?;

        let mut result = HashMap::with_capacity(rows.len());
        for r in rows {
            let text_hash: String = r.try_get("text_hash")?;
            let row_model: String = r.try_get("model")?;
            if row_model != model {
                return Err(RecapError::Db(format!(
                    "embedding cache model identity mismatch for hash {text_hash}: expected {model}, got {row_model}"
                )));
            }
            let dim: i32 = r.try_get("dim")?;
            let embedding: Vec<f32> = r.try_get("embedding")?;
            if usize::try_from(dim).ok() != Some(embedding.len()) {
                return Err(RecapError::Db(format!(
                    "cached embedding dimension mismatch for hash {text_hash}: dim column {dim} != embedding array length {}",
                    embedding.len()
                )));
            }
            result.insert(text_hash, embedding);
        }

        Ok(result)
    }

    /// Insert new embeddings into cache idempotently (DO NOTHING on conflict).
    pub async fn insert_embeddings(
        pool: &PgPool,
        model: &str,
        dim: usize,
        entries: &[(String, Vec<f32>)],
    ) -> Result<()> {
        if entries.is_empty() {
            return Ok(());
        }

        for (hash, vec) in entries {
            if vec.len() != dim {
                return Err(RecapError::Db(format!(
                    "cannot insert embedding for hash {hash}: vector length {} != specified dim {dim}",
                    vec.len()
                )));
            }
        }

        let mut tx = pool.begin().await.map_err(|e| {
            RecapError::Db(format!("failed to begin tx for insert_embeddings: {e}"))
        })?;

        for (hash, vec) in entries {
            sqlx::query(
                r"
                INSERT INTO recap_card_embeddings (text_hash, model, dim, embedding)
                VALUES ($1, $2, $3, $4)
                ON CONFLICT (text_hash, model) DO NOTHING
                ",
            )
            .bind(hash)
            .bind(model)
            .bind(dim as i32)
            .bind(vec)
            .execute(&mut *tx)
            .await
            .map_err(|e| {
                RecapError::Db(format!("failed to insert embedding for hash {hash}: {e}"))
            })?;
        }

        tx.commit()
            .await
            .map_err(|e| RecapError::Db(format!("failed to commit insert_embeddings tx: {e}")))?;

        Ok(())
    }
}

pub(crate) fn parse_previous_card_rows(
    job_id: Uuid,
    card_rows: impl IntoIterator<Item = (Uuid, Uuid, Option<Vec<f32>>)>,
) -> (Vec<PreviousCardSummary>, usize) {
    let mut cards = Vec::new();
    let mut null_centroids = 0;
    for (id, story_id, centroid) in card_rows {
        if let Some(c) = centroid {
            cards.push(PreviousCardSummary {
                id,
                story_id,
                centroid: c,
            });
        } else {
            null_centroids += 1;
        }
    }
    if null_centroids > 0 {
        tracing::warn!(
            job_id = %job_id,
            null_centroids,
            "previous cards job had cards with NULL centroid"
        );
    }
    (cards, null_centroids)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_decision_validation() {
        assert!(is_valid_decision("top"));
        assert!(is_valid_decision("not_top"));
        assert!(is_valid_decision("noise"));
        assert!(!is_valid_decision("invalid"));
        assert!(!is_valid_decision(""));
    }

    #[test]
    fn test_score_validation() {
        assert!(is_valid_score(0));
        assert!(is_valid_score(1));
        assert!(is_valid_score(2));
        assert!(!is_valid_score(-1));
        assert!(!is_valid_score(3));
    }

    #[test]
    fn test_serialization_roundtrip() {
        let candidate = RecapCardCandidate {
            id: Uuid::new_v4(),
            job_id: Uuid::new_v4(),
            rank: 1,
            cluster_fingerprint: "fp-1".to_string(),
            size: 3,
            domains: serde_json::json!([{"host": "example.com", "count": 2}]),
            items: serde_json::json!([{"feed_id": Uuid::new_v4(), "title": "test"}]),
            scores: serde_json::json!({"corroboration": 1.2}),
            centroid: Some(vec![0.1, 0.2, 0.3]),
            member_feed_ids: vec![Uuid::new_v4()],
            created_at: Utc::now(),
        };

        let json = serde_json::to_string(&candidate).expect("serialize candidate");
        let deserialized: RecapCardCandidate =
            serde_json::from_str(&json).expect("deserialize candidate");
        assert_eq!(candidate.id, deserialized.id);
        assert_eq!(candidate.rank, deserialized.rank);
        assert_eq!(
            candidate.cluster_fingerprint,
            deserialized.cluster_fingerprint
        );
        assert_eq!(candidate.member_feed_ids, deserialized.member_feed_ids);
    }

    #[test]
    fn test_previous_cards_job_serialization() {
        let now = Utc::now();
        let prev = PreviousCardsJob {
            job_id: Uuid::new_v4(),
            kicked_at: now,
            from_ts: now - chrono::Duration::days(3),
            to_ts: now,
            params_version: "cards-v0.1".to_string(),
            cards: vec![PreviousCardSummary {
                id: Uuid::new_v4(),
                story_id: Uuid::new_v4(),
                centroid: vec![0.1, 0.2, 0.3],
            }],
        };

        let json = serde_json::to_string(&prev).expect("serialize prev");
        let deserialized: PreviousCardsJob = serde_json::from_str(&json).expect("deserialize prev");
        assert_eq!(prev.job_id, deserialized.job_id);
        assert_eq!(prev.kicked_at, deserialized.kicked_at);
        assert_eq!(prev.from_ts, deserialized.from_ts);
        assert_eq!(prev.to_ts, deserialized.to_ts);
        assert_eq!(prev.params_version, deserialized.params_version);
        assert_eq!(prev.cards.len(), deserialized.cards.len());
        assert_eq!(prev.cards[0].id, deserialized.cards[0].id);
        assert_eq!(prev.cards[0].story_id, deserialized.cards[0].story_id);
        assert_eq!(prev.cards[0].centroid, deserialized.cards[0].centroid);
    }

    #[test]
    fn test_parse_previous_card_rows_null_centroid_warning_path() {
        let job_id = Uuid::new_v4();
        let card1_id = Uuid::new_v4();
        let card1_story = Uuid::new_v4();
        let card2_id = Uuid::new_v4();
        let card2_story = Uuid::new_v4();
        let card3_id = Uuid::new_v4();
        let card3_story = Uuid::new_v4();

        let rows = vec![
            (card1_id, card1_story, Some(vec![0.1, 0.2])),
            (card2_id, card2_story, None),
            (card3_id, card3_story, Some(vec![0.3, 0.4])),
        ];

        let (cards, null_count) = parse_previous_card_rows(job_id, rows);
        assert_eq!(null_count, 1);
        assert_eq!(cards.len(), 2);
        assert_eq!(cards[0].id, card1_id);
        assert_eq!(cards[0].centroid, vec![0.1, 0.2]);
        assert_eq!(cards[1].id, card3_id);
        assert_eq!(cards[1].centroid, vec![0.3, 0.4]);
    }

    #[tokio::test]
    async fn test_cached_embeddings_empty_inputs() {
        let pool = sqlx::PgPool::connect_lazy("postgres://localhost/dummy").unwrap();
        let get_res = CardsDaoOps::get_cached_embeddings(&pool, "bge-m3", &[])
            .await
            .unwrap();
        assert!(get_res.is_empty());

        let insert_res = CardsDaoOps::insert_embeddings(&pool, "bge-m3", 4, &[]).await;
        assert!(insert_res.is_ok());
    }

    #[tokio::test]
    async fn test_insert_embeddings_dimension_mismatch_fails_before_db() {
        let pool = sqlx::PgPool::connect_lazy("postgres://localhost/dummy").unwrap();
        let entries = vec![
            ("hash1".to_string(), vec![0.1, 0.2, 0.3]), // len 3, specified 4
        ];
        let res = CardsDaoOps::insert_embeddings(&pool, "bge-m3", 4, &entries).await;
        assert!(res.is_err());
        let err = format!("{}", res.unwrap_err());
        assert!(err.contains("vector length 3 != specified dim 4"));
    }
}
