// Package rag_gateway provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package rag_gateway

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// AnswerCitation defines model for AnswerCitation.
type AnswerCitation struct {
	ChunkId         *string  `json:"chunk_id,omitempty"`
	ChunkText       *string  `json:"chunk_text,omitempty"`
	DocumentVersion *int64   `json:"document_version,omitempty"`
	Score           *float32 `json:"score,omitempty"`
	Title           *string  `json:"title,omitempty"`
	Url             *string  `json:"url,omitempty"`
}

// AnswerDebug defines model for AnswerDebug.
type AnswerDebug struct {
	PromptVersion  *string `json:"prompt_version,omitempty"`
	RetrievalSetId *string `json:"retrieval_set_id,omitempty"`
}

// AnswerRequest defines model for AnswerRequest.
type AnswerRequest struct {
	CandidateArticleIds *[]string `json:"candidate_article_ids,omitempty"`
	Locale              *string   `json:"locale,omitempty"`
	MaxChunks           *int32    `json:"max_chunks,omitempty"`
	MaxTokens           *int32    `json:"max_tokens,omitempty"`
	Query               string    `json:"query"`
	UserId              *string   `json:"user_id,omitempty"`
}

// AnswerResponse defines model for AnswerResponse.
type AnswerResponse struct {
	Answer    *string           `json:"answer,omitempty"`
	Citations *[]AnswerCitation `json:"citations,omitempty"`
	Contexts  *[]Context        `json:"contexts,omitempty"`
	Debug     *AnswerDebug      `json:"debug,omitempty"`
	Fallback  *bool             `json:"fallback,omitempty"`
	Reason    *string           `json:"reason,omitempty"`
}

// Context defines model for Context.
type Context struct {
	ChunkId   *string `json:"chunk_id,omitempty"`
	ChunkText *string `json:"chunk_text,omitempty"`

	// DocumentVersion Version of the document this chunk belongs to
	DocumentVersion *int64     `json:"document_version,omitempty"`
	PublishedAt     *time.Time `json:"published_at,omitempty"`

	// Score Similarity score
	Score *float32 `json:"score,omitempty"`
	Title *string  `json:"title,omitempty"`
	Url   *string  `json:"url,omitempty"`
}

// DeleteIndexRequest defines model for DeleteIndexRequest.
type DeleteIndexRequest struct {
	ArticleId string `json:"article_id"`
	UserId    string `json:"user_id"`
}

// RetrieveRequest defines model for RetrieveRequest.
type RetrieveRequest struct {
	// CandidateArticleIds Optional list of article IDs to restrict search to
	CandidateArticleIds *[]string `json:"candidate_article_ids,omitempty"`
	Query               string    `json:"query"`
}

// RetrieveResponse defines model for RetrieveResponse.
type RetrieveResponse struct {
	Contexts *[]Context `json:"contexts,omitempty"`
}

// UpsertIndexRequest defines model for UpsertIndexRequest.
type UpsertIndexRequest struct {
	// ArticleId Unique identifier of the article (UUID or string)
	ArticleId string `json:"article_id"`

	// Body Full text content of the article
	Body        string     `json:"body"`
	PublishedAt time.Time  `json:"published_at"`
	Title       string     `json:"title"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty"`
	Url         string     `json:"url"`

	// UserId User ID owning the article
	UserId string `json:"user_id"`
}

// DeleteIndexJSONRequestBody defines body for DeleteIndex for application/json ContentType.
type DeleteIndexJSONRequestBody = DeleteIndexRequest

// UpsertIndexJSONRequestBody defines body for UpsertIndex for application/json ContentType.
type UpsertIndexJSONRequestBody = UpsertIndexRequest

// AnswerWithRAGJSONRequestBody defines body for AnswerWithRAG for application/json ContentType.
type AnswerWithRAGJSONRequestBody = AnswerRequest

// RetrieveContextJSONRequestBody defines body for RetrieveContext for application/json ContentType.
type RetrieveContextJSONRequestBody = RetrieveRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// DeleteIndexWithBody request with any body
	DeleteIndexWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DeleteIndex(ctx context.Context, body DeleteIndexJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpsertIndexWithBody request with any body
	UpsertIndexWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpsertIndex(ctx context.Context, body UpsertIndexJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AnswerWithRAGWithBody request with any body
	AnswerWithRAGWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AnswerWithRAG(ctx context.Context, body AnswerWithRAGJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RetrieveContextWithBody request with any body
	RetrieveContextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RetrieveContext(ctx context.Context, body RetrieveContextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) DeleteIndexWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteIndexRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteIndex(ctx context.Context, body DeleteIndexJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteIndexRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpsertIndexWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpsertIndexRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpsertIndex(ctx context.Context, body UpsertIndexJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpsertIndexRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AnswerWithRAGWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAnswerWithRAGRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AnswerWithRAG(ctx context.Context, body AnswerWithRAGJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAnswerWithRAGRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RetrieveContextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRetrieveContextRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RetrieveContext(ctx context.Context, body RetrieveContextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRetrieveContextRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDeleteIndexRequest calls the generic DeleteIndex builder with application/json body
func NewDeleteIndexRequest(server string, body DeleteIndexJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDeleteIndexRequestWithBody(server, "application/json", bodyReader)
}

// NewDeleteIndexRequestWithBody generates requests for DeleteIndex with any type of body
func NewDeleteIndexRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/rag/index/delete")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUpsertIndexRequest calls the generic UpsertIndex builder with application/json body
func NewUpsertIndexRequest(server string, body UpsertIndexJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpsertIndexRequestWithBody(server, "application/json", bodyReader)
}

// NewUpsertIndexRequestWithBody generates requests for UpsertIndex with any type of body
func NewUpsertIndexRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/rag/index/upsert")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewAnswerWithRAGRequest calls the generic AnswerWithRAG builder with application/json body
func NewAnswerWithRAGRequest(server string, body AnswerWithRAGJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAnswerWithRAGRequestWithBody(server, "application/json", bodyReader)
}

// NewAnswerWithRAGRequestWithBody generates requests for AnswerWithRAG with any type of body
func NewAnswerWithRAGRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/rag/answer")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRetrieveContextRequest calls the generic RetrieveContext builder with application/json body
func NewRetrieveContextRequest(server string, body RetrieveContextJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRetrieveContextRequestWithBody(server, "application/json", bodyReader)
}

// NewRetrieveContextRequestWithBody generates requests for RetrieveContext with any type of body
func NewRetrieveContextRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/rag/retrieve")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// DeleteIndexWithBodyWithResponse request with any body
	DeleteIndexWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteIndexResponse, error)

	DeleteIndexWithResponse(ctx context.Context, body DeleteIndexJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteIndexResponse, error)

	// UpsertIndexWithBodyWithResponse request with any body
	UpsertIndexWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpsertIndexResponse, error)

	UpsertIndexWithResponse(ctx context.Context, body UpsertIndexJSONRequestBody, reqEditors ...RequestEditorFn) (*UpsertIndexResponse, error)

	// AnswerWithRAGWithBodyWithResponse request with any body
	AnswerWithRAGWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AnswerWithRAGResponse, error)

	AnswerWithRAGWithResponse(ctx context.Context, body AnswerWithRAGJSONRequestBody, reqEditors ...RequestEditorFn) (*AnswerWithRAGResponse, error)

	// RetrieveContextWithBodyWithResponse request with any body
	RetrieveContextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RetrieveContextResponse, error)

	RetrieveContextWithResponse(ctx context.Context, body RetrieveContextJSONRequestBody, reqEditors ...RequestEditorFn) (*RetrieveContextResponse, error)
}

type DeleteIndexResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteIndexResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteIndexResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpsertIndexResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UpsertIndexResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpsertIndexResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AnswerWithRAGResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AnswerResponse
}

// Status returns HTTPResponse.Status
func (r AnswerWithRAGResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AnswerWithRAGResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RetrieveContextResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RetrieveResponse
}

// Status returns HTTPResponse.Status
func (r RetrieveContextResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RetrieveContextResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// DeleteIndexWithBodyWithResponse request with arbitrary body returning *DeleteIndexResponse
func (c *ClientWithResponses) DeleteIndexWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteIndexResponse, error) {
	rsp, err := c.DeleteIndexWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteIndexResponse(rsp)
}

func (c *ClientWithResponses) DeleteIndexWithResponse(ctx context.Context, body DeleteIndexJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteIndexResponse, error) {
	rsp, err := c.DeleteIndex(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteIndexResponse(rsp)
}

// UpsertIndexWithBodyWithResponse request with arbitrary body returning *UpsertIndexResponse
func (c *ClientWithResponses) UpsertIndexWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpsertIndexResponse, error) {
	rsp, err := c.UpsertIndexWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpsertIndexResponse(rsp)
}

func (c *ClientWithResponses) UpsertIndexWithResponse(ctx context.Context, body UpsertIndexJSONRequestBody, reqEditors ...RequestEditorFn) (*UpsertIndexResponse, error) {
	rsp, err := c.UpsertIndex(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpsertIndexResponse(rsp)
}

// AnswerWithRAGWithBodyWithResponse request with arbitrary body returning *AnswerWithRAGResponse
func (c *ClientWithResponses) AnswerWithRAGWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AnswerWithRAGResponse, error) {
	rsp, err := c.AnswerWithRAGWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAnswerWithRAGResponse(rsp)
}

func (c *ClientWithResponses) AnswerWithRAGWithResponse(ctx context.Context, body AnswerWithRAGJSONRequestBody, reqEditors ...RequestEditorFn) (*AnswerWithRAGResponse, error) {
	rsp, err := c.AnswerWithRAG(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAnswerWithRAGResponse(rsp)
}

// RetrieveContextWithBodyWithResponse request with arbitrary body returning *RetrieveContextResponse
func (c *ClientWithResponses) RetrieveContextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RetrieveContextResponse, error) {
	rsp, err := c.RetrieveContextWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRetrieveContextResponse(rsp)
}

func (c *ClientWithResponses) RetrieveContextWithResponse(ctx context.Context, body RetrieveContextJSONRequestBody, reqEditors ...RequestEditorFn) (*RetrieveContextResponse, error) {
	rsp, err := c.RetrieveContext(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRetrieveContextResponse(rsp)
}

// ParseDeleteIndexResponse parses an HTTP response from a DeleteIndexWithResponse call
func ParseDeleteIndexResponse(rsp *http.Response) (*DeleteIndexResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteIndexResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUpsertIndexResponse parses an HTTP response from a UpsertIndexWithResponse call
func ParseUpsertIndexResponse(rsp *http.Response) (*UpsertIndexResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpsertIndexResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseAnswerWithRAGResponse parses an HTTP response from a AnswerWithRAGWithResponse call
func ParseAnswerWithRAGResponse(rsp *http.Response) (*AnswerWithRAGResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AnswerWithRAGResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AnswerResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseRetrieveContextResponse parses an HTTP response from a RetrieveContextWithResponse call
func ParseRetrieveContextResponse(rsp *http.Response) (*RetrieveContextResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RetrieveContextResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RetrieveResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
