// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/validate_fetch_rss_port/port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/validate_fetch_rss_port/port.go -destination=./alt-backend/app/mocks/mock_validate_fetch_rss_port.go -package=mocks ValidateAndFetchRSSPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockValidateAndFetchRSSPort is a mock of ValidateAndFetchRSSPort interface.
type MockValidateAndFetchRSSPort struct {
	ctrl     *gomock.Controller
	recorder *MockValidateAndFetchRSSPortMockRecorder
	isgomock struct{}
}

// MockValidateAndFetchRSSPortMockRecorder is the mock recorder for MockValidateAndFetchRSSPort.
type MockValidateAndFetchRSSPortMockRecorder struct {
	mock *MockValidateAndFetchRSSPort
}

// NewMockValidateAndFetchRSSPort creates a new mock instance.
func NewMockValidateAndFetchRSSPort(ctrl *gomock.Controller) *MockValidateAndFetchRSSPort {
	mock := &MockValidateAndFetchRSSPort{ctrl: ctrl}
	mock.recorder = &MockValidateAndFetchRSSPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidateAndFetchRSSPort) EXPECT() *MockValidateAndFetchRSSPortMockRecorder {
	return m.recorder
}

// ValidateAndFetch mocks base method.
func (m *MockValidateAndFetchRSSPort) ValidateAndFetch(ctx context.Context, link string) (*domain.ParsedFeed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndFetch", ctx, link)
	ret0, _ := ret[0].(*domain.ParsedFeed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAndFetch indicates an expected call of ValidateAndFetch.
func (mr *MockValidateAndFetchRSSPortMockRecorder) ValidateAndFetch(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndFetch", reflect.TypeOf((*MockValidateAndFetchRSSPort)(nil).ValidateAndFetch), ctx, link)
}
