// Code generated by MockGen. DO NOT EDIT.
// Source: orchestrator/port/search_indexer_port/search_indexer_port.go

package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockArticleSearchPort is a mock of ArticleSearchPort interface.
type MockArticleSearchPort struct {
	ctrl     *gomock.Controller
	recorder *MockArticleSearchPortMockRecorder
	isgomock struct{}
}

// MockArticleSearchPortMockRecorder is the mock recorder for MockArticleSearchPort.
type MockArticleSearchPortMockRecorder struct {
	mock *MockArticleSearchPort
}

// NewMockArticleSearchPort creates a new mock instance.
func NewMockArticleSearchPort(ctrl *gomock.Controller) *MockArticleSearchPort {
	mock := &MockArticleSearchPort{ctrl: ctrl}
	mock.recorder = &MockArticleSearchPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleSearchPort) EXPECT() *MockArticleSearchPortMockRecorder {
	return m.recorder
}

// SearchArticles mocks base method.
func (m *MockArticleSearchPort) SearchArticles(ctx context.Context, query, userID string) ([]domain.SearchIndexerArticleHit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchArticles", ctx, query, userID)
	ret0, _ := ret[0].([]domain.SearchIndexerArticleHit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchArticles indicates an expected call of SearchArticles.
func (mr *MockArticleSearchPortMockRecorder) SearchArticles(ctx, query, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchArticles", reflect.TypeOf((*MockArticleSearchPort)(nil).SearchArticles), ctx, query, userID)
}

// SearchArticlesWithPagination mocks base method.
func (m *MockArticleSearchPort) SearchArticlesWithPagination(ctx context.Context, query, userID string, offset, limit int) ([]domain.SearchIndexerArticleHit, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchArticlesWithPagination", ctx, query, userID, offset, limit)
	ret0, _ := ret[0].([]domain.SearchIndexerArticleHit)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchArticlesWithPagination indicates an expected call of SearchArticlesWithPagination.
func (mr *MockArticleSearchPortMockRecorder) SearchArticlesWithPagination(ctx, query, userID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchArticlesWithPagination", reflect.TypeOf((*MockArticleSearchPort)(nil).SearchArticlesWithPagination), ctx, query, userID, offset, limit)
}

// MockRecapSearchPort is a mock of RecapSearchPort interface.
type MockRecapSearchPort struct {
	ctrl     *gomock.Controller
	recorder *MockRecapSearchPortMockRecorder
	isgomock struct{}
}

// MockRecapSearchPortMockRecorder is the mock recorder for MockRecapSearchPort.
type MockRecapSearchPortMockRecorder struct {
	mock *MockRecapSearchPort
}

// NewMockRecapSearchPort creates a new mock instance.
func NewMockRecapSearchPort(ctrl *gomock.Controller) *MockRecapSearchPort {
	mock := &MockRecapSearchPort{ctrl: ctrl}
	mock.recorder = &MockRecapSearchPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecapSearchPort) EXPECT() *MockRecapSearchPortMockRecorder {
	return m.recorder
}

// SearchRecapsByTag mocks base method.
func (m *MockRecapSearchPort) SearchRecapsByTag(ctx context.Context, tagName string, limit int) ([]*domain.RecapSearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRecapsByTag", ctx, tagName, limit)
	ret0, _ := ret[0].([]*domain.RecapSearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRecapsByTag indicates an expected call of SearchRecapsByTag.
func (mr *MockRecapSearchPortMockRecorder) SearchRecapsByTag(ctx, tagName, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRecapsByTag", reflect.TypeOf((*MockRecapSearchPort)(nil).SearchRecapsByTag), ctx, tagName, limit)
}

// SearchRecapsByQuery mocks base method.
func (m *MockRecapSearchPort) SearchRecapsByQuery(ctx context.Context, query string, limit int) ([]*domain.RecapSearchResult, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRecapsByQuery", ctx, query, limit)
	ret0, _ := ret[0].([]*domain.RecapSearchResult)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchRecapsByQuery indicates an expected call of SearchRecapsByQuery.
func (mr *MockRecapSearchPortMockRecorder) SearchRecapsByQuery(ctx, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRecapsByQuery", reflect.TypeOf((*MockRecapSearchPort)(nil).SearchRecapsByQuery), ctx, query, limit)
}
