// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/recap_port/recap_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/recap_port/recap_port.go -destination=./alt-backend/app/mocks/mock_recap_port.go -package=mocks RecapPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRecapPort is a mock of RecapPort interface.
type MockRecapPort struct {
	ctrl     *gomock.Controller
	recorder *MockRecapPortMockRecorder
	isgomock struct{}
}

// MockRecapPortMockRecorder is the mock recorder for MockRecapPort.
type MockRecapPortMockRecorder struct {
	mock *MockRecapPort
}

// NewMockRecapPort creates a new mock instance.
func NewMockRecapPort(ctrl *gomock.Controller) *MockRecapPort {
	mock := &MockRecapPort{ctrl: ctrl}
	mock.recorder = &MockRecapPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecapPort) EXPECT() *MockRecapPortMockRecorder {
	return m.recorder
}

// GetSevenDayRecap mocks base method.
func (m *MockRecapPort) GetSevenDayRecap(ctx context.Context) (*domain.RecapSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSevenDayRecap", ctx)
	ret0, _ := ret[0].(*domain.RecapSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSevenDayRecap indicates an expected call of GetSevenDayRecap.
func (mr *MockRecapPortMockRecorder) GetSevenDayRecap(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSevenDayRecap", reflect.TypeOf((*MockRecapPort)(nil).GetSevenDayRecap), ctx)
}
