// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/scraping_policy_port/scraping_policy_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/scraping_policy_port/scraping_policy_port.go -destination=./alt-backend/app/mocks/mock_scraping_policy_port.go -package=mocks ScrapingPolicyPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockScrapingPolicyPort is a mock of ScrapingPolicyPort interface.
type MockScrapingPolicyPort struct {
	ctrl     *gomock.Controller
	recorder *MockScrapingPolicyPortMockRecorder
	isgomock struct{}
}

// MockScrapingPolicyPortMockRecorder is the mock recorder for MockScrapingPolicyPort.
type MockScrapingPolicyPortMockRecorder struct {
	mock *MockScrapingPolicyPort
}

// NewMockScrapingPolicyPort creates a new mock instance.
func NewMockScrapingPolicyPort(ctrl *gomock.Controller) *MockScrapingPolicyPort {
	mock := &MockScrapingPolicyPort{ctrl: ctrl}
	mock.recorder = &MockScrapingPolicyPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScrapingPolicyPort) EXPECT() *MockScrapingPolicyPortMockRecorder {
	return m.recorder
}

// CanFetchArticle mocks base method.
func (m *MockScrapingPolicyPort) CanFetchArticle(ctx context.Context, articleURL string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanFetchArticle", ctx, articleURL)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanFetchArticle indicates an expected call of CanFetchArticle.
func (mr *MockScrapingPolicyPortMockRecorder) CanFetchArticle(ctx, articleURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanFetchArticle", reflect.TypeOf((*MockScrapingPolicyPort)(nil).CanFetchArticle), ctx, articleURL)
}
