// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/robots_txt_port/robots_txt_port.go

package mocks

import (
	domain "alt/domain"
	context "context"
	url "net/url"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRobotsTxtFetcherPort is a mock of RobotsTxtFetcherPort interface.
type MockRobotsTxtFetcherPort struct {
	ctrl     *gomock.Controller
	recorder *MockRobotsTxtFetcherPortMockRecorder
	isgomock struct{}
}

// MockRobotsTxtFetcherPortMockRecorder is the mock recorder for MockRobotsTxtFetcherPort.
type MockRobotsTxtFetcherPortMockRecorder struct {
	mock *MockRobotsTxtFetcherPort
}

// NewMockRobotsTxtFetcherPort creates a new mock instance.
func NewMockRobotsTxtFetcherPort(ctrl *gomock.Controller) *MockRobotsTxtFetcherPort {
	mock := &MockRobotsTxtFetcherPort{ctrl: ctrl}
	mock.recorder = &MockRobotsTxtFetcherPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRobotsTxtFetcherPort) EXPECT() *MockRobotsTxtFetcherPortMockRecorder {
	return m.recorder
}

// FetchRobotsTxt mocks base method.
func (m *MockRobotsTxtFetcherPort) FetchRobotsTxt(ctx context.Context, domainName, scheme string) (*domain.RobotsTxt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRobotsTxt", ctx, domainName, scheme)
	ret0, _ := ret[0].(*domain.RobotsTxt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRobotsTxt indicates an expected call of FetchRobotsTxt.
func (mr *MockRobotsTxtFetcherPortMockRecorder) FetchRobotsTxt(ctx, domainName, scheme any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRobotsTxt", reflect.TypeOf((*MockRobotsTxtFetcherPort)(nil).FetchRobotsTxt), ctx, domainName, scheme)
}

// MockRobotsTxtPolicyPort is a mock of RobotsTxtPolicyPort interface.
type MockRobotsTxtPolicyPort struct {
	ctrl     *gomock.Controller
	recorder *MockRobotsTxtPolicyPortMockRecorder
	isgomock struct{}
}

// MockRobotsTxtPolicyPortMockRecorder is the mock recorder for MockRobotsTxtPolicyPort.
type MockRobotsTxtPolicyPortMockRecorder struct {
	mock *MockRobotsTxtPolicyPort
}

// NewMockRobotsTxtPolicyPort creates a new mock instance.
func NewMockRobotsTxtPolicyPort(ctrl *gomock.Controller) *MockRobotsTxtPolicyPort {
	mock := &MockRobotsTxtPolicyPort{ctrl: ctrl}
	mock.recorder = &MockRobotsTxtPolicyPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRobotsTxtPolicyPort) EXPECT() *MockRobotsTxtPolicyPortMockRecorder {
	return m.recorder
}

// IsPathAllowed mocks base method.
func (m *MockRobotsTxtPolicyPort) IsPathAllowed(ctx context.Context, targetURL *url.URL, userAgent string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPathAllowed", ctx, targetURL, userAgent)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsPathAllowed indicates an expected call of IsPathAllowed.
func (mr *MockRobotsTxtPolicyPortMockRecorder) IsPathAllowed(ctx, targetURL, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPathAllowed", reflect.TypeOf((*MockRobotsTxtPolicyPort)(nil).IsPathAllowed), ctx, targetURL, userAgent)
}
