// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/archive_article_port/archive_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/archive_article_port/archive_port.go -destination=./alt-backend/app/mocks/mock_archive_article_port.go -package=mocks ArchiveArticlePort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	archive_article_port "alt/port/archive_article_port"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockArchiveArticlePort is a mock of ArchiveArticlePort interface.
type MockArchiveArticlePort struct {
	ctrl     *gomock.Controller
	recorder *MockArchiveArticlePortMockRecorder
	isgomock struct{}
}

// MockArchiveArticlePortMockRecorder is the mock recorder for MockArchiveArticlePort.
type MockArchiveArticlePortMockRecorder struct {
	mock *MockArchiveArticlePort
}

// NewMockArchiveArticlePort creates a new mock instance.
func NewMockArchiveArticlePort(ctrl *gomock.Controller) *MockArchiveArticlePort {
	mock := &MockArchiveArticlePort{ctrl: ctrl}
	mock.recorder = &MockArchiveArticlePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArchiveArticlePort) EXPECT() *MockArchiveArticlePortMockRecorder {
	return m.recorder
}

// SaveArticle mocks base method.
func (m *MockArchiveArticlePort) SaveArticle(ctx context.Context, record archive_article_port.ArticleRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveArticle", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveArticle indicates an expected call of SaveArticle.
func (mr *MockArchiveArticlePortMockRecorder) SaveArticle(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveArticle", reflect.TypeOf((*MockArchiveArticlePort)(nil).SaveArticle), ctx, record)
}
