// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/knowledge_metrics_port/port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/knowledge_metrics_port/port.go -destination=./alt-backend/app/mocks/mock_knowledge_metrics_port.go -package=mocks GetSystemMetricsPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetSystemMetricsPort is a mock of GetSystemMetricsPort interface.
type MockGetSystemMetricsPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetSystemMetricsPortMockRecorder
	isgomock struct{}
}

// MockGetSystemMetricsPortMockRecorder is the mock recorder for MockGetSystemMetricsPort.
type MockGetSystemMetricsPortMockRecorder struct {
	mock *MockGetSystemMetricsPort
}

// NewMockGetSystemMetricsPort creates a new mock instance.
func NewMockGetSystemMetricsPort(ctrl *gomock.Controller) *MockGetSystemMetricsPort {
	mock := &MockGetSystemMetricsPort{ctrl: ctrl}
	mock.recorder = &MockGetSystemMetricsPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetSystemMetricsPort) EXPECT() *MockGetSystemMetricsPortMockRecorder {
	return m.recorder
}

// GetSystemMetrics mocks base method.
func (m *MockGetSystemMetricsPort) GetSystemMetrics(ctx context.Context) (*domain.SystemMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemMetrics", ctx)
	ret0, _ := ret[0].(*domain.SystemMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemMetrics indicates an expected call of GetSystemMetrics.
func (mr *MockGetSystemMetricsPortMockRecorder) GetSystemMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemMetrics", reflect.TypeOf((*MockGetSystemMetricsPort)(nil).GetSystemMetrics), ctx)
}

// MockCheckServiceHealthPort is a mock of CheckServiceHealthPort interface.
type MockCheckServiceHealthPort struct {
	ctrl     *gomock.Controller
	recorder *MockCheckServiceHealthPortMockRecorder
	isgomock struct{}
}

// MockCheckServiceHealthPortMockRecorder is the mock recorder for MockCheckServiceHealthPort.
type MockCheckServiceHealthPortMockRecorder struct {
	mock *MockCheckServiceHealthPort
}

// NewMockCheckServiceHealthPort creates a new mock instance.
func NewMockCheckServiceHealthPort(ctrl *gomock.Controller) *MockCheckServiceHealthPort {
	mock := &MockCheckServiceHealthPort{ctrl: ctrl}
	mock.recorder = &MockCheckServiceHealthPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckServiceHealthPort) EXPECT() *MockCheckServiceHealthPortMockRecorder {
	return m.recorder
}

// CheckHealth mocks base method.
func (m *MockCheckServiceHealthPort) CheckHealth(ctx context.Context) ([]domain.ServiceHealthStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckHealth", ctx)
	ret0, _ := ret[0].([]domain.ServiceHealthStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckHealth indicates an expected call of CheckHealth.
func (mr *MockCheckServiceHealthPortMockRecorder) CheckHealth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckHealth", reflect.TypeOf((*MockCheckServiceHealthPort)(nil).CheckHealth), ctx)
}
