// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/fetch_recent_articles_port/fetch_recent_articles_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/fetch_recent_articles_port/fetch_recent_articles_port.go -destination=./alt-backend/app/mocks/mock_fetch_recent_articles_port.go -package=mocks FetchRecentArticlesPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockFetchRecentArticlesPort is a mock of FetchRecentArticlesPort interface.
type MockFetchRecentArticlesPort struct {
	ctrl     *gomock.Controller
	recorder *MockFetchRecentArticlesPortMockRecorder
	isgomock struct{}
}

// MockFetchRecentArticlesPortMockRecorder is the mock recorder for MockFetchRecentArticlesPort.
type MockFetchRecentArticlesPortMockRecorder struct {
	mock *MockFetchRecentArticlesPort
}

// NewMockFetchRecentArticlesPort creates a new mock instance.
func NewMockFetchRecentArticlesPort(ctrl *gomock.Controller) *MockFetchRecentArticlesPort {
	mock := &MockFetchRecentArticlesPort{ctrl: ctrl}
	mock.recorder = &MockFetchRecentArticlesPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFetchRecentArticlesPort) EXPECT() *MockFetchRecentArticlesPortMockRecorder {
	return m.recorder
}

// FetchRecentArticles mocks base method.
func (m *MockFetchRecentArticlesPort) FetchRecentArticles(ctx context.Context, since time.Time, limit int) ([]*domain.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRecentArticles", ctx, since, limit)
	ret0, _ := ret[0].([]*domain.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRecentArticles indicates an expected call of FetchRecentArticles.
func (mr *MockFetchRecentArticlesPortMockRecorder) FetchRecentArticles(ctx, since, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRecentArticles", reflect.TypeOf((*MockFetchRecentArticlesPort)(nil).FetchRecentArticles), ctx, since, limit)
}
