// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/knowledge_event_port/port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/knowledge_event_port/port.go -destination=./alt-backend/app/mocks/mock_knowledge_event_port.go -package=mocks AppendKnowledgeEventPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAppendKnowledgeEventPort is a mock of AppendKnowledgeEventPort interface.
type MockAppendKnowledgeEventPort struct {
	ctrl     *gomock.Controller
	recorder *MockAppendKnowledgeEventPortMockRecorder
	isgomock struct{}
}

// MockAppendKnowledgeEventPortMockRecorder is the mock recorder for MockAppendKnowledgeEventPort.
type MockAppendKnowledgeEventPortMockRecorder struct {
	mock *MockAppendKnowledgeEventPort
}

// NewMockAppendKnowledgeEventPort creates a new mock instance.
func NewMockAppendKnowledgeEventPort(ctrl *gomock.Controller) *MockAppendKnowledgeEventPort {
	mock := &MockAppendKnowledgeEventPort{ctrl: ctrl}
	mock.recorder = &MockAppendKnowledgeEventPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppendKnowledgeEventPort) EXPECT() *MockAppendKnowledgeEventPortMockRecorder {
	return m.recorder
}

// AppendKnowledgeEvent mocks base method.
func (m *MockAppendKnowledgeEventPort) AppendKnowledgeEvent(ctx context.Context, event domain.KnowledgeEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendKnowledgeEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendKnowledgeEvent indicates an expected call of AppendKnowledgeEvent.
func (mr *MockAppendKnowledgeEventPortMockRecorder) AppendKnowledgeEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendKnowledgeEvent", reflect.TypeOf((*MockAppendKnowledgeEventPort)(nil).AppendKnowledgeEvent), ctx, event)
}

// MockListKnowledgeEventsPort is a mock of ListKnowledgeEventsPort interface.
type MockListKnowledgeEventsPort struct {
	ctrl     *gomock.Controller
	recorder *MockListKnowledgeEventsPortMockRecorder
	isgomock struct{}
}

// MockListKnowledgeEventsPortMockRecorder is the mock recorder for MockListKnowledgeEventsPort.
type MockListKnowledgeEventsPortMockRecorder struct {
	mock *MockListKnowledgeEventsPort
}

// NewMockListKnowledgeEventsPort creates a new mock instance.
func NewMockListKnowledgeEventsPort(ctrl *gomock.Controller) *MockListKnowledgeEventsPort {
	mock := &MockListKnowledgeEventsPort{ctrl: ctrl}
	mock.recorder = &MockListKnowledgeEventsPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListKnowledgeEventsPort) EXPECT() *MockListKnowledgeEventsPortMockRecorder {
	return m.recorder
}

// ListKnowledgeEventsSince mocks base method.
func (m *MockListKnowledgeEventsPort) ListKnowledgeEventsSince(ctx context.Context, afterSeq int64, limit int) ([]domain.KnowledgeEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKnowledgeEventsSince", ctx, afterSeq, limit)
	ret0, _ := ret[0].([]domain.KnowledgeEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKnowledgeEventsSince indicates an expected call of ListKnowledgeEventsSince.
func (mr *MockListKnowledgeEventsPortMockRecorder) ListKnowledgeEventsSince(ctx, afterSeq, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKnowledgeEventsSince", reflect.TypeOf((*MockListKnowledgeEventsPort)(nil).ListKnowledgeEventsSince), ctx, afterSeq, limit)
}

// MockListKnowledgeEventsForUserPort is a mock of ListKnowledgeEventsForUserPort interface.
type MockListKnowledgeEventsForUserPort struct {
	ctrl     *gomock.Controller
	recorder *MockListKnowledgeEventsForUserPortMockRecorder
	isgomock struct{}
}

// MockListKnowledgeEventsForUserPortMockRecorder is the mock recorder for MockListKnowledgeEventsForUserPort.
type MockListKnowledgeEventsForUserPortMockRecorder struct {
	mock *MockListKnowledgeEventsForUserPort
}

// NewMockListKnowledgeEventsForUserPort creates a new mock instance.
func NewMockListKnowledgeEventsForUserPort(ctrl *gomock.Controller) *MockListKnowledgeEventsForUserPort {
	mock := &MockListKnowledgeEventsForUserPort{ctrl: ctrl}
	mock.recorder = &MockListKnowledgeEventsForUserPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListKnowledgeEventsForUserPort) EXPECT() *MockListKnowledgeEventsForUserPortMockRecorder {
	return m.recorder
}

// ListKnowledgeEventsSinceForUser mocks base method.
func (m *MockListKnowledgeEventsForUserPort) ListKnowledgeEventsSinceForUser(ctx context.Context, tenantID, userID uuid.UUID, afterSeq int64, limit int) ([]domain.KnowledgeEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKnowledgeEventsSinceForUser", ctx, tenantID, userID, afterSeq, limit)
	ret0, _ := ret[0].([]domain.KnowledgeEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKnowledgeEventsSinceForUser indicates an expected call of ListKnowledgeEventsSinceForUser.
func (mr *MockListKnowledgeEventsForUserPortMockRecorder) ListKnowledgeEventsSinceForUser(ctx, tenantID, userID, afterSeq, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKnowledgeEventsSinceForUser", reflect.TypeOf((*MockListKnowledgeEventsForUserPort)(nil).ListKnowledgeEventsSinceForUser), ctx, tenantID, userID, afterSeq, limit)
}

// MockLatestKnowledgeEventSeqForUserPort is a mock of LatestKnowledgeEventSeqForUserPort interface.
type MockLatestKnowledgeEventSeqForUserPort struct {
	ctrl     *gomock.Controller
	recorder *MockLatestKnowledgeEventSeqForUserPortMockRecorder
	isgomock struct{}
}

// MockLatestKnowledgeEventSeqForUserPortMockRecorder is the mock recorder for MockLatestKnowledgeEventSeqForUserPort.
type MockLatestKnowledgeEventSeqForUserPortMockRecorder struct {
	mock *MockLatestKnowledgeEventSeqForUserPort
}

// NewMockLatestKnowledgeEventSeqForUserPort creates a new mock instance.
func NewMockLatestKnowledgeEventSeqForUserPort(ctrl *gomock.Controller) *MockLatestKnowledgeEventSeqForUserPort {
	mock := &MockLatestKnowledgeEventSeqForUserPort{ctrl: ctrl}
	mock.recorder = &MockLatestKnowledgeEventSeqForUserPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLatestKnowledgeEventSeqForUserPort) EXPECT() *MockLatestKnowledgeEventSeqForUserPortMockRecorder {
	return m.recorder
}

// GetLatestKnowledgeEventSeqForUser mocks base method.
func (m *MockLatestKnowledgeEventSeqForUserPort) GetLatestKnowledgeEventSeqForUser(ctx context.Context, tenantID, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestKnowledgeEventSeqForUser", ctx, tenantID, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestKnowledgeEventSeqForUser indicates an expected call of GetLatestKnowledgeEventSeqForUser.
func (mr *MockLatestKnowledgeEventSeqForUserPortMockRecorder) GetLatestKnowledgeEventSeqForUser(ctx, tenantID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestKnowledgeEventSeqForUser", reflect.TypeOf((*MockLatestKnowledgeEventSeqForUserPort)(nil).GetLatestKnowledgeEventSeqForUser), ctx, tenantID, userID)
}

// MockIsArticleVisibleInLensPort is a mock of IsArticleVisibleInLensPort interface.
type MockIsArticleVisibleInLensPort struct {
	ctrl     *gomock.Controller
	recorder *MockIsArticleVisibleInLensPortMockRecorder
	isgomock struct{}
}

// MockIsArticleVisibleInLensPortMockRecorder is the mock recorder for MockIsArticleVisibleInLensPort.
type MockIsArticleVisibleInLensPortMockRecorder struct {
	mock *MockIsArticleVisibleInLensPort
}

// NewMockIsArticleVisibleInLensPort creates a new mock instance.
func NewMockIsArticleVisibleInLensPort(ctrl *gomock.Controller) *MockIsArticleVisibleInLensPort {
	mock := &MockIsArticleVisibleInLensPort{ctrl: ctrl}
	mock.recorder = &MockIsArticleVisibleInLensPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIsArticleVisibleInLensPort) EXPECT() *MockIsArticleVisibleInLensPortMockRecorder {
	return m.recorder
}

// AreArticlesVisibleInLens mocks base method.
func (m *MockIsArticleVisibleInLensPort) AreArticlesVisibleInLens(ctx context.Context, tenantID, userID uuid.UUID, articleIDs []uuid.UUID, filter *domain.KnowledgeHomeLensFilter) (map[uuid.UUID]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AreArticlesVisibleInLens", ctx, tenantID, userID, articleIDs, filter)
	ret0, _ := ret[0].(map[uuid.UUID]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AreArticlesVisibleInLens indicates an expected call of AreArticlesVisibleInLens.
func (mr *MockIsArticleVisibleInLensPortMockRecorder) AreArticlesVisibleInLens(ctx, tenantID, userID, articleIDs, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AreArticlesVisibleInLens", reflect.TypeOf((*MockIsArticleVisibleInLensPort)(nil).AreArticlesVisibleInLens), ctx, tenantID, userID, articleIDs, filter)
}
