// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/fetch_inoreader_summary_port/fetch_summary_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/fetch_inoreader_summary_port/fetch_summary_port.go -destination=./alt-backend/app/mocks/mock_fetch_inoreader_summary_port.go -package=mocks FetchInoreaderSummaryPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFetchInoreaderSummaryPort is a mock of FetchInoreaderSummaryPort interface.
type MockFetchInoreaderSummaryPort struct {
	ctrl     *gomock.Controller
	recorder *MockFetchInoreaderSummaryPortMockRecorder
	isgomock struct{}
}

// MockFetchInoreaderSummaryPortMockRecorder is the mock recorder for MockFetchInoreaderSummaryPort.
type MockFetchInoreaderSummaryPortMockRecorder struct {
	mock *MockFetchInoreaderSummaryPort
}

// NewMockFetchInoreaderSummaryPort creates a new mock instance.
func NewMockFetchInoreaderSummaryPort(ctrl *gomock.Controller) *MockFetchInoreaderSummaryPort {
	mock := &MockFetchInoreaderSummaryPort{ctrl: ctrl}
	mock.recorder = &MockFetchInoreaderSummaryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFetchInoreaderSummaryPort) EXPECT() *MockFetchInoreaderSummaryPortMockRecorder {
	return m.recorder
}

// FetchSummariesByURLs mocks base method.
func (m *MockFetchInoreaderSummaryPort) FetchSummariesByURLs(ctx context.Context, urls []string) ([]*domain.InoreaderSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchSummariesByURLs", ctx, urls)
	ret0, _ := ret[0].([]*domain.InoreaderSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchSummariesByURLs indicates an expected call of FetchSummariesByURLs.
func (mr *MockFetchInoreaderSummaryPortMockRecorder) FetchSummariesByURLs(ctx, urls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchSummariesByURLs", reflect.TypeOf((*MockFetchInoreaderSummaryPort)(nil).FetchSummariesByURLs), ctx, urls)
}
