// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/article_summary_port/article_summary_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/article_summary_port/article_summary_port.go -destination=./alt-backend/app/mocks/mock_article_summary_port.go -package=mocks FetchArticleSummaryPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	url "net/url"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFetchArticleSummaryPort is a mock of FetchArticleSummaryPort interface.
type MockFetchArticleSummaryPort struct {
	ctrl     *gomock.Controller
	recorder *MockFetchArticleSummaryPortMockRecorder
	isgomock struct{}
}

// MockFetchArticleSummaryPortMockRecorder is the mock recorder for MockFetchArticleSummaryPort.
type MockFetchArticleSummaryPortMockRecorder struct {
	mock *MockFetchArticleSummaryPort
}

// NewMockFetchArticleSummaryPort creates a new mock instance.
func NewMockFetchArticleSummaryPort(ctrl *gomock.Controller) *MockFetchArticleSummaryPort {
	mock := &MockFetchArticleSummaryPort{ctrl: ctrl}
	mock.recorder = &MockFetchArticleSummaryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFetchArticleSummaryPort) EXPECT() *MockFetchArticleSummaryPortMockRecorder {
	return m.recorder
}

// FetchFeedSummary mocks base method.
func (m *MockFetchArticleSummaryPort) FetchFeedSummary(ctx context.Context, feedURL *url.URL) (*domain.FeedSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFeedSummary", ctx, feedURL)
	ret0, _ := ret[0].(*domain.FeedSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchFeedSummary indicates an expected call of FetchFeedSummary.
func (mr *MockFetchArticleSummaryPortMockRecorder) FetchFeedSummary(ctx, feedURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFeedSummary", reflect.TypeOf((*MockFetchArticleSummaryPort)(nil).FetchFeedSummary), ctx, feedURL)
}
