// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/feature_flag_port/port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/feature_flag_port/port.go -destination=./alt-backend/app/mocks/mock_feature_flag_port.go -package=mocks FeatureFlagPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockFeatureFlagPort is a mock of FeatureFlagPort interface.
type MockFeatureFlagPort struct {
	ctrl     *gomock.Controller
	recorder *MockFeatureFlagPortMockRecorder
	isgomock struct{}
}

// MockFeatureFlagPortMockRecorder is the mock recorder for MockFeatureFlagPort.
type MockFeatureFlagPortMockRecorder struct {
	mock *MockFeatureFlagPort
}

// NewMockFeatureFlagPort creates a new mock instance.
func NewMockFeatureFlagPort(ctrl *gomock.Controller) *MockFeatureFlagPort {
	mock := &MockFeatureFlagPort{ctrl: ctrl}
	mock.recorder = &MockFeatureFlagPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeatureFlagPort) EXPECT() *MockFeatureFlagPortMockRecorder {
	return m.recorder
}

// IsEnabled mocks base method.
func (m *MockFeatureFlagPort) IsEnabled(flagName string, userID uuid.UUID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabled", flagName, userID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnabled indicates an expected call of IsEnabled.
func (mr *MockFeatureFlagPortMockRecorder) IsEnabled(flagName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockFeatureFlagPort)(nil).IsEnabled), flagName, userID)
}
