// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/robots_txt_port/robots_txt_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/robots_txt_port/robots_txt_port.go -destination=./alt-backend/app/mocks/mock_robots_txt_port.go -package=mocks RobotsTxtPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	url "net/url"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRobotsTxtPort is a mock of RobotsTxtPort interface.
type MockRobotsTxtPort struct {
	ctrl     *gomock.Controller
	recorder *MockRobotsTxtPortMockRecorder
	isgomock struct{}
}

// MockRobotsTxtPortMockRecorder is the mock recorder for MockRobotsTxtPort.
type MockRobotsTxtPortMockRecorder struct {
	mock *MockRobotsTxtPort
}

// NewMockRobotsTxtPort creates a new mock instance.
func NewMockRobotsTxtPort(ctrl *gomock.Controller) *MockRobotsTxtPort {
	mock := &MockRobotsTxtPort{ctrl: ctrl}
	mock.recorder = &MockRobotsTxtPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRobotsTxtPort) EXPECT() *MockRobotsTxtPortMockRecorder {
	return m.recorder
}

// FetchRobotsTxt mocks base method.
func (m *MockRobotsTxtPort) FetchRobotsTxt(ctx context.Context, domainName, scheme string) (*domain.RobotsTxt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRobotsTxt", ctx, domainName, scheme)
	ret0, _ := ret[0].(*domain.RobotsTxt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRobotsTxt indicates an expected call of FetchRobotsTxt.
func (mr *MockRobotsTxtPortMockRecorder) FetchRobotsTxt(ctx, domainName, scheme any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRobotsTxt", reflect.TypeOf((*MockRobotsTxtPort)(nil).FetchRobotsTxt), ctx, domainName, scheme)
}

// IsPathAllowed mocks base method.
func (m *MockRobotsTxtPort) IsPathAllowed(ctx context.Context, targetURL *url.URL, userAgent string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPathAllowed", ctx, targetURL, userAgent)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsPathAllowed indicates an expected call of IsPathAllowed.
func (mr *MockRobotsTxtPortMockRecorder) IsPathAllowed(ctx, targetURL, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPathAllowed", reflect.TypeOf((*MockRobotsTxtPort)(nil).IsPathAllowed), ctx, targetURL, userAgent)
}
