// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/dashboard_port/dashboard_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/dashboard_port/dashboard_port.go -destination=./alt-backend/app/mocks/mock_dashboard_port.go -package=mocks DashboardMetricsPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDashboardMetricsPort is a mock of DashboardMetricsPort interface.
type MockDashboardMetricsPort struct {
	ctrl     *gomock.Controller
	recorder *MockDashboardMetricsPortMockRecorder
	isgomock struct{}
}

// MockDashboardMetricsPortMockRecorder is the mock recorder for MockDashboardMetricsPort.
type MockDashboardMetricsPortMockRecorder struct {
	mock *MockDashboardMetricsPort
}

// NewMockDashboardMetricsPort creates a new mock instance.
func NewMockDashboardMetricsPort(ctrl *gomock.Controller) *MockDashboardMetricsPort {
	mock := &MockDashboardMetricsPort{ctrl: ctrl}
	mock.recorder = &MockDashboardMetricsPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDashboardMetricsPort) EXPECT() *MockDashboardMetricsPortMockRecorder {
	return m.recorder
}

// GetJobs mocks base method.
func (m *MockDashboardMetricsPort) GetJobs(ctx context.Context, windowSeconds, limit int64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobs", ctx, windowSeconds, limit)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobs indicates an expected call of GetJobs.
func (mr *MockDashboardMetricsPortMockRecorder) GetJobs(ctx, windowSeconds, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobs", reflect.TypeOf((*MockDashboardMetricsPort)(nil).GetJobs), ctx, windowSeconds, limit)
}

// GetLogs mocks base method.
func (m *MockDashboardMetricsPort) GetLogs(ctx context.Context, windowSeconds, limit int64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogs", ctx, windowSeconds, limit)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogs indicates an expected call of GetLogs.
func (mr *MockDashboardMetricsPortMockRecorder) GetLogs(ctx, windowSeconds, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogs", reflect.TypeOf((*MockDashboardMetricsPort)(nil).GetLogs), ctx, windowSeconds, limit)
}

// GetMetrics mocks base method.
func (m *MockDashboardMetricsPort) GetMetrics(ctx context.Context, metricType string, windowSeconds, limit int64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics", ctx, metricType, windowSeconds, limit)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockDashboardMetricsPortMockRecorder) GetMetrics(ctx, metricType, windowSeconds, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockDashboardMetricsPort)(nil).GetMetrics), ctx, metricType, windowSeconds, limit)
}

// GetOverview mocks base method.
func (m *MockDashboardMetricsPort) GetOverview(ctx context.Context, windowSeconds, limit int64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverview", ctx, windowSeconds, limit)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverview indicates an expected call of GetOverview.
func (mr *MockDashboardMetricsPortMockRecorder) GetOverview(ctx, windowSeconds, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverview", reflect.TypeOf((*MockDashboardMetricsPort)(nil).GetOverview), ctx, windowSeconds, limit)
}
