// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/admin_metrics_port/admin_metrics_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/admin_metrics_port/admin_metrics_port.go -destination=./alt-backend/app/mocks/mock_admin_metrics_port.go -package=mocks AdminMetricsPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAdminMetricsPort is a mock of AdminMetricsPort interface.
type MockAdminMetricsPort struct {
	ctrl     *gomock.Controller
	recorder *MockAdminMetricsPortMockRecorder
	isgomock struct{}
}

// MockAdminMetricsPortMockRecorder is the mock recorder for MockAdminMetricsPort.
type MockAdminMetricsPortMockRecorder struct {
	mock *MockAdminMetricsPort
}

// NewMockAdminMetricsPort creates a new mock instance.
func NewMockAdminMetricsPort(ctrl *gomock.Controller) *MockAdminMetricsPort {
	mock := &MockAdminMetricsPort{ctrl: ctrl}
	mock.recorder = &MockAdminMetricsPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminMetricsPort) EXPECT() *MockAdminMetricsPortMockRecorder {
	return m.recorder
}

// Catalog mocks base method.
func (m *MockAdminMetricsPort) Catalog() []domain.MetricCatalogEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Catalog")
	ret0, _ := ret[0].([]domain.MetricCatalogEntry)
	return ret0
}

// Catalog indicates an expected call of Catalog.
func (mr *MockAdminMetricsPortMockRecorder) Catalog() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Catalog", reflect.TypeOf((*MockAdminMetricsPort)(nil).Catalog))
}

// Healthy mocks base method.
func (m *MockAdminMetricsPort) Healthy(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Healthy", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Healthy indicates an expected call of Healthy.
func (mr *MockAdminMetricsPortMockRecorder) Healthy(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Healthy", reflect.TypeOf((*MockAdminMetricsPort)(nil).Healthy), ctx)
}

// Snapshot mocks base method.
func (m *MockAdminMetricsPort) Snapshot(ctx context.Context, keys []domain.MetricKey, window domain.RangeWindow, step domain.Step) (*domain.MetricsSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", ctx, keys, window, step)
	ret0, _ := ret[0].(*domain.MetricsSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockAdminMetricsPortMockRecorder) Snapshot(ctx, keys, window, step any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockAdminMetricsPort)(nil).Snapshot), ctx, keys, window, step)
}
