// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/feed_link_availability_port/feed_link_availability_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/feed_link_availability_port/feed_link_availability_port.go -destination=./alt-backend/app/mocks/mock_feed_link_availability_port.go -package=mocks FeedLinkAvailabilityPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFeedLinkAvailabilityPort is a mock of FeedLinkAvailabilityPort interface.
type MockFeedLinkAvailabilityPort struct {
	ctrl     *gomock.Controller
	recorder *MockFeedLinkAvailabilityPortMockRecorder
	isgomock struct{}
}

// MockFeedLinkAvailabilityPortMockRecorder is the mock recorder for MockFeedLinkAvailabilityPort.
type MockFeedLinkAvailabilityPortMockRecorder struct {
	mock *MockFeedLinkAvailabilityPort
}

// NewMockFeedLinkAvailabilityPort creates a new mock instance.
func NewMockFeedLinkAvailabilityPort(ctrl *gomock.Controller) *MockFeedLinkAvailabilityPort {
	mock := &MockFeedLinkAvailabilityPort{ctrl: ctrl}
	mock.recorder = &MockFeedLinkAvailabilityPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedLinkAvailabilityPort) EXPECT() *MockFeedLinkAvailabilityPortMockRecorder {
	return m.recorder
}

// DisableFeedLink mocks base method.
func (m *MockFeedLinkAvailabilityPort) DisableFeedLink(ctx context.Context, feedURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableFeedLink", ctx, feedURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableFeedLink indicates an expected call of DisableFeedLink.
func (mr *MockFeedLinkAvailabilityPortMockRecorder) DisableFeedLink(ctx, feedURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableFeedLink", reflect.TypeOf((*MockFeedLinkAvailabilityPort)(nil).DisableFeedLink), ctx, feedURL)
}

// IncrementFeedLinkFailures mocks base method.
func (m *MockFeedLinkAvailabilityPort) IncrementFeedLinkFailures(ctx context.Context, feedURL, reason string) (*domain.FeedLinkAvailability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementFeedLinkFailures", ctx, feedURL, reason)
	ret0, _ := ret[0].(*domain.FeedLinkAvailability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementFeedLinkFailures indicates an expected call of IncrementFeedLinkFailures.
func (mr *MockFeedLinkAvailabilityPortMockRecorder) IncrementFeedLinkFailures(ctx, feedURL, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementFeedLinkFailures", reflect.TypeOf((*MockFeedLinkAvailabilityPort)(nil).IncrementFeedLinkFailures), ctx, feedURL, reason)
}

// ResetFeedLinkFailures mocks base method.
func (m *MockFeedLinkAvailabilityPort) ResetFeedLinkFailures(ctx context.Context, feedURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetFeedLinkFailures", ctx, feedURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetFeedLinkFailures indicates an expected call of ResetFeedLinkFailures.
func (mr *MockFeedLinkAvailabilityPortMockRecorder) ResetFeedLinkFailures(ctx, feedURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetFeedLinkFailures", reflect.TypeOf((*MockFeedLinkAvailabilityPort)(nil).ResetFeedLinkFailures), ctx, feedURL)
}
