// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/knowledge_sovereign_port/port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/knowledge_sovereign_port/port.go -destination=./alt-backend/app/mocks/mock_knowledge_sovereign_port.go -package=mocks ProjectionMutator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	knowledge_sovereign_port "alt/port/knowledge_sovereign_port"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProjectionMutator is a mock of ProjectionMutator interface.
type MockProjectionMutator struct {
	ctrl     *gomock.Controller
	recorder *MockProjectionMutatorMockRecorder
	isgomock struct{}
}

// MockProjectionMutatorMockRecorder is the mock recorder for MockProjectionMutator.
type MockProjectionMutatorMockRecorder struct {
	mock *MockProjectionMutator
}

// NewMockProjectionMutator creates a new mock instance.
func NewMockProjectionMutator(ctrl *gomock.Controller) *MockProjectionMutator {
	mock := &MockProjectionMutator{ctrl: ctrl}
	mock.recorder = &MockProjectionMutatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectionMutator) EXPECT() *MockProjectionMutatorMockRecorder {
	return m.recorder
}

// ApplyProjectionMutation mocks base method.
func (m *MockProjectionMutator) ApplyProjectionMutation(ctx context.Context, mutation knowledge_sovereign_port.ProjectionMutation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyProjectionMutation", ctx, mutation)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyProjectionMutation indicates an expected call of ApplyProjectionMutation.
func (mr *MockProjectionMutatorMockRecorder) ApplyProjectionMutation(ctx, mutation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyProjectionMutation", reflect.TypeOf((*MockProjectionMutator)(nil).ApplyProjectionMutation), ctx, mutation)
}

// MockRecallMutator is a mock of RecallMutator interface.
type MockRecallMutator struct {
	ctrl     *gomock.Controller
	recorder *MockRecallMutatorMockRecorder
	isgomock struct{}
}

// MockRecallMutatorMockRecorder is the mock recorder for MockRecallMutator.
type MockRecallMutatorMockRecorder struct {
	mock *MockRecallMutator
}

// NewMockRecallMutator creates a new mock instance.
func NewMockRecallMutator(ctrl *gomock.Controller) *MockRecallMutator {
	mock := &MockRecallMutator{ctrl: ctrl}
	mock.recorder = &MockRecallMutatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecallMutator) EXPECT() *MockRecallMutatorMockRecorder {
	return m.recorder
}

// ApplyRecallMutation mocks base method.
func (m *MockRecallMutator) ApplyRecallMutation(ctx context.Context, mutation knowledge_sovereign_port.RecallMutation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyRecallMutation", ctx, mutation)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyRecallMutation indicates an expected call of ApplyRecallMutation.
func (mr *MockRecallMutatorMockRecorder) ApplyRecallMutation(ctx, mutation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyRecallMutation", reflect.TypeOf((*MockRecallMutator)(nil).ApplyRecallMutation), ctx, mutation)
}

// MockCurationMutator is a mock of CurationMutator interface.
type MockCurationMutator struct {
	ctrl     *gomock.Controller
	recorder *MockCurationMutatorMockRecorder
	isgomock struct{}
}

// MockCurationMutatorMockRecorder is the mock recorder for MockCurationMutator.
type MockCurationMutatorMockRecorder struct {
	mock *MockCurationMutator
}

// NewMockCurationMutator creates a new mock instance.
func NewMockCurationMutator(ctrl *gomock.Controller) *MockCurationMutator {
	mock := &MockCurationMutator{ctrl: ctrl}
	mock.recorder = &MockCurationMutatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurationMutator) EXPECT() *MockCurationMutatorMockRecorder {
	return m.recorder
}

// ApplyCurationMutation mocks base method.
func (m *MockCurationMutator) ApplyCurationMutation(ctx context.Context, mutation knowledge_sovereign_port.CurationMutation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyCurationMutation", ctx, mutation)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyCurationMutation indicates an expected call of ApplyCurationMutation.
func (mr *MockCurationMutatorMockRecorder) ApplyCurationMutation(ctx, mutation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyCurationMutation", reflect.TypeOf((*MockCurationMutator)(nil).ApplyCurationMutation), ctx, mutation)
}
