// Code generated by MockGen. DO NOT EDIT.
// Source: orchestrator/port/rag_integration_port/rag_integration_port.go

package mocks

import (
	rag_integration_port "alt/orchestrator/port/rag_integration_port"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockArticleUpsertPort is a mock of ArticleUpsertPort interface.
type MockArticleUpsertPort struct {
	ctrl     *gomock.Controller
	recorder *MockArticleUpsertPortMockRecorder
	isgomock struct{}
}

// MockArticleUpsertPortMockRecorder is the mock recorder for MockArticleUpsertPort.
type MockArticleUpsertPortMockRecorder struct {
	mock *MockArticleUpsertPort
}

// NewMockArticleUpsertPort creates a new mock instance.
func NewMockArticleUpsertPort(ctrl *gomock.Controller) *MockArticleUpsertPort {
	mock := &MockArticleUpsertPort{ctrl: ctrl}
	mock.recorder = &MockArticleUpsertPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleUpsertPort) EXPECT() *MockArticleUpsertPortMockRecorder {
	return m.recorder
}

// UpsertArticle mocks base method.
func (m *MockArticleUpsertPort) UpsertArticle(ctx context.Context, input rag_integration_port.UpsertArticleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertArticle", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertArticle indicates an expected call of UpsertArticle.
func (mr *MockArticleUpsertPortMockRecorder) UpsertArticle(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertArticle", reflect.TypeOf((*MockArticleUpsertPort)(nil).UpsertArticle), ctx, input)
}

// MockRagRetrievalPort is a mock of RagRetrievalPort interface.
type MockRagRetrievalPort struct {
	ctrl     *gomock.Controller
	recorder *MockRagRetrievalPortMockRecorder
	isgomock struct{}
}

// MockRagRetrievalPortMockRecorder is the mock recorder for MockRagRetrievalPort.
type MockRagRetrievalPortMockRecorder struct {
	mock *MockRagRetrievalPort
}

// NewMockRagRetrievalPort creates a new mock instance.
func NewMockRagRetrievalPort(ctrl *gomock.Controller) *MockRagRetrievalPort {
	mock := &MockRagRetrievalPort{ctrl: ctrl}
	mock.recorder = &MockRagRetrievalPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRagRetrievalPort) EXPECT() *MockRagRetrievalPortMockRecorder {
	return m.recorder
}

// RetrieveContext mocks base method.
func (m *MockRagRetrievalPort) RetrieveContext(ctx context.Context, query string, candidateIDs []string, userID string) ([]rag_integration_port.RagContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveContext", ctx, query, candidateIDs, userID)
	ret0, _ := ret[0].([]rag_integration_port.RagContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveContext indicates an expected call of RetrieveContext.
func (mr *MockRagRetrievalPortMockRecorder) RetrieveContext(ctx, query, candidateIDs, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveContext", reflect.TypeOf((*MockRagRetrievalPort)(nil).RetrieveContext), ctx, query, candidateIDs, userID)
}

// MockRagAnswerPort is a mock of RagAnswerPort interface.
type MockRagAnswerPort struct {
	ctrl     *gomock.Controller
	recorder *MockRagAnswerPortMockRecorder
	isgomock struct{}
}

// MockRagAnswerPortMockRecorder is the mock recorder for MockRagAnswerPort.
type MockRagAnswerPortMockRecorder struct {
	mock *MockRagAnswerPort
}

// NewMockRagAnswerPort creates a new mock instance.
func NewMockRagAnswerPort(ctrl *gomock.Controller) *MockRagAnswerPort {
	mock := &MockRagAnswerPort{ctrl: ctrl}
	mock.recorder = &MockRagAnswerPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRagAnswerPort) EXPECT() *MockRagAnswerPortMockRecorder {
	return m.recorder
}

// Answer mocks base method.
func (m *MockRagAnswerPort) Answer(ctx context.Context, input rag_integration_port.AnswerInput) (<-chan string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Answer", ctx, input)
	ret0, _ := ret[0].(<-chan string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Answer indicates an expected call of Answer.
func (mr *MockRagAnswerPortMockRecorder) Answer(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Answer", reflect.TypeOf((*MockRagAnswerPort)(nil).Answer), ctx, input)
}
