// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/fetch_random_subscription_port/port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/fetch_random_subscription_port/port.go -destination=./alt-backend/app/mocks/mock_fetch_random_subscription_port.go -package=mocks FetchRandomSubscriptionPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFetchRandomSubscriptionPort is a mock of FetchRandomSubscriptionPort interface.
type MockFetchRandomSubscriptionPort struct {
	ctrl     *gomock.Controller
	recorder *MockFetchRandomSubscriptionPortMockRecorder
	isgomock struct{}
}

// MockFetchRandomSubscriptionPortMockRecorder is the mock recorder for MockFetchRandomSubscriptionPort.
type MockFetchRandomSubscriptionPortMockRecorder struct {
	mock *MockFetchRandomSubscriptionPort
}

// NewMockFetchRandomSubscriptionPort creates a new mock instance.
func NewMockFetchRandomSubscriptionPort(ctrl *gomock.Controller) *MockFetchRandomSubscriptionPort {
	mock := &MockFetchRandomSubscriptionPort{ctrl: ctrl}
	mock.recorder = &MockFetchRandomSubscriptionPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFetchRandomSubscriptionPort) EXPECT() *MockFetchRandomSubscriptionPortMockRecorder {
	return m.recorder
}

// FetchRandomSubscription mocks base method.
func (m *MockFetchRandomSubscriptionPort) FetchRandomSubscription(ctx context.Context) (*domain.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRandomSubscription", ctx)
	ret0, _ := ret[0].(*domain.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRandomSubscription indicates an expected call of FetchRandomSubscription.
func (mr *MockFetchRandomSubscriptionPortMockRecorder) FetchRandomSubscription(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRandomSubscription", reflect.TypeOf((*MockFetchRandomSubscriptionPort)(nil).FetchRandomSubscription), ctx)
}
