// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/knowledge_backfill_port/port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/knowledge_backfill_port/port.go -destination=./alt-backend/app/mocks/mock_knowledge_backfill_port.go -package=mocks CreateBackfillJobPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateBackfillJobPort is a mock of CreateBackfillJobPort interface.
type MockCreateBackfillJobPort struct {
	ctrl     *gomock.Controller
	recorder *MockCreateBackfillJobPortMockRecorder
	isgomock struct{}
}

// MockCreateBackfillJobPortMockRecorder is the mock recorder for MockCreateBackfillJobPort.
type MockCreateBackfillJobPortMockRecorder struct {
	mock *MockCreateBackfillJobPort
}

// NewMockCreateBackfillJobPort creates a new mock instance.
func NewMockCreateBackfillJobPort(ctrl *gomock.Controller) *MockCreateBackfillJobPort {
	mock := &MockCreateBackfillJobPort{ctrl: ctrl}
	mock.recorder = &MockCreateBackfillJobPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateBackfillJobPort) EXPECT() *MockCreateBackfillJobPortMockRecorder {
	return m.recorder
}

// CreateBackfillJob mocks base method.
func (m *MockCreateBackfillJobPort) CreateBackfillJob(ctx context.Context, job domain.KnowledgeBackfillJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBackfillJob", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBackfillJob indicates an expected call of CreateBackfillJob.
func (mr *MockCreateBackfillJobPortMockRecorder) CreateBackfillJob(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBackfillJob", reflect.TypeOf((*MockCreateBackfillJobPort)(nil).CreateBackfillJob), ctx, job)
}

// MockGetBackfillJobPort is a mock of GetBackfillJobPort interface.
type MockGetBackfillJobPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetBackfillJobPortMockRecorder
	isgomock struct{}
}

// MockGetBackfillJobPortMockRecorder is the mock recorder for MockGetBackfillJobPort.
type MockGetBackfillJobPortMockRecorder struct {
	mock *MockGetBackfillJobPort
}

// NewMockGetBackfillJobPort creates a new mock instance.
func NewMockGetBackfillJobPort(ctrl *gomock.Controller) *MockGetBackfillJobPort {
	mock := &MockGetBackfillJobPort{ctrl: ctrl}
	mock.recorder = &MockGetBackfillJobPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetBackfillJobPort) EXPECT() *MockGetBackfillJobPortMockRecorder {
	return m.recorder
}

// GetBackfillJob mocks base method.
func (m *MockGetBackfillJobPort) GetBackfillJob(ctx context.Context, jobID uuid.UUID) (*domain.KnowledgeBackfillJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackfillJob", ctx, jobID)
	ret0, _ := ret[0].(*domain.KnowledgeBackfillJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackfillJob indicates an expected call of GetBackfillJob.
func (mr *MockGetBackfillJobPortMockRecorder) GetBackfillJob(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackfillJob", reflect.TypeOf((*MockGetBackfillJobPort)(nil).GetBackfillJob), ctx, jobID)
}

// MockUpdateBackfillJobPort is a mock of UpdateBackfillJobPort interface.
type MockUpdateBackfillJobPort struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateBackfillJobPortMockRecorder
	isgomock struct{}
}

// MockUpdateBackfillJobPortMockRecorder is the mock recorder for MockUpdateBackfillJobPort.
type MockUpdateBackfillJobPortMockRecorder struct {
	mock *MockUpdateBackfillJobPort
}

// NewMockUpdateBackfillJobPort creates a new mock instance.
func NewMockUpdateBackfillJobPort(ctrl *gomock.Controller) *MockUpdateBackfillJobPort {
	mock := &MockUpdateBackfillJobPort{ctrl: ctrl}
	mock.recorder = &MockUpdateBackfillJobPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateBackfillJobPort) EXPECT() *MockUpdateBackfillJobPortMockRecorder {
	return m.recorder
}

// UpdateBackfillJob mocks base method.
func (m *MockUpdateBackfillJobPort) UpdateBackfillJob(ctx context.Context, job domain.KnowledgeBackfillJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBackfillJob", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBackfillJob indicates an expected call of UpdateBackfillJob.
func (mr *MockUpdateBackfillJobPortMockRecorder) UpdateBackfillJob(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBackfillJob", reflect.TypeOf((*MockUpdateBackfillJobPort)(nil).UpdateBackfillJob), ctx, job)
}

// MockListBackfillJobsPort is a mock of ListBackfillJobsPort interface.
type MockListBackfillJobsPort struct {
	ctrl     *gomock.Controller
	recorder *MockListBackfillJobsPortMockRecorder
	isgomock struct{}
}

// MockListBackfillJobsPortMockRecorder is the mock recorder for MockListBackfillJobsPort.
type MockListBackfillJobsPortMockRecorder struct {
	mock *MockListBackfillJobsPort
}

// NewMockListBackfillJobsPort creates a new mock instance.
func NewMockListBackfillJobsPort(ctrl *gomock.Controller) *MockListBackfillJobsPort {
	mock := &MockListBackfillJobsPort{ctrl: ctrl}
	mock.recorder = &MockListBackfillJobsPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListBackfillJobsPort) EXPECT() *MockListBackfillJobsPortMockRecorder {
	return m.recorder
}

// ListBackfillJobs mocks base method.
func (m *MockListBackfillJobsPort) ListBackfillJobs(ctx context.Context) ([]domain.KnowledgeBackfillJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBackfillJobs", ctx)
	ret0, _ := ret[0].([]domain.KnowledgeBackfillJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBackfillJobs indicates an expected call of ListBackfillJobs.
func (mr *MockListBackfillJobsPortMockRecorder) ListBackfillJobs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBackfillJobs", reflect.TypeOf((*MockListBackfillJobsPort)(nil).ListBackfillJobs), ctx)
}

// MockListBackfillArticlesPort is a mock of ListBackfillArticlesPort interface.
type MockListBackfillArticlesPort struct {
	ctrl     *gomock.Controller
	recorder *MockListBackfillArticlesPortMockRecorder
	isgomock struct{}
}

// MockListBackfillArticlesPortMockRecorder is the mock recorder for MockListBackfillArticlesPort.
type MockListBackfillArticlesPortMockRecorder struct {
	mock *MockListBackfillArticlesPort
}

// NewMockListBackfillArticlesPort creates a new mock instance.
func NewMockListBackfillArticlesPort(ctrl *gomock.Controller) *MockListBackfillArticlesPort {
	mock := &MockListBackfillArticlesPort{ctrl: ctrl}
	mock.recorder = &MockListBackfillArticlesPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListBackfillArticlesPort) EXPECT() *MockListBackfillArticlesPortMockRecorder {
	return m.recorder
}

// ListBackfillArticles mocks base method.
func (m *MockListBackfillArticlesPort) ListBackfillArticles(ctx context.Context, lastCreatedAt *time.Time, lastArticleID *uuid.UUID, limit int) ([]domain.KnowledgeBackfillArticle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBackfillArticles", ctx, lastCreatedAt, lastArticleID, limit)
	ret0, _ := ret[0].([]domain.KnowledgeBackfillArticle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBackfillArticles indicates an expected call of ListBackfillArticles.
func (mr *MockListBackfillArticlesPortMockRecorder) ListBackfillArticles(ctx, lastCreatedAt, lastArticleID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBackfillArticles", reflect.TypeOf((*MockListBackfillArticlesPort)(nil).ListBackfillArticles), ctx, lastCreatedAt, lastArticleID, limit)
}

// MockCountBackfillArticlesPort is a mock of CountBackfillArticlesPort interface.
type MockCountBackfillArticlesPort struct {
	ctrl     *gomock.Controller
	recorder *MockCountBackfillArticlesPortMockRecorder
	isgomock struct{}
}

// MockCountBackfillArticlesPortMockRecorder is the mock recorder for MockCountBackfillArticlesPort.
type MockCountBackfillArticlesPortMockRecorder struct {
	mock *MockCountBackfillArticlesPort
}

// NewMockCountBackfillArticlesPort creates a new mock instance.
func NewMockCountBackfillArticlesPort(ctrl *gomock.Controller) *MockCountBackfillArticlesPort {
	mock := &MockCountBackfillArticlesPort{ctrl: ctrl}
	mock.recorder = &MockCountBackfillArticlesPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCountBackfillArticlesPort) EXPECT() *MockCountBackfillArticlesPortMockRecorder {
	return m.recorder
}

// CountBackfillArticles mocks base method.
func (m *MockCountBackfillArticlesPort) CountBackfillArticles(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBackfillArticles", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBackfillArticles indicates an expected call of CountBackfillArticles.
func (mr *MockCountBackfillArticlesPortMockRecorder) CountBackfillArticles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBackfillArticles", reflect.TypeOf((*MockCountBackfillArticlesPort)(nil).CountBackfillArticles), ctx)
}
