// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/knowledge_home_port/port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/knowledge_home_port/port.go -destination=./alt-backend/app/mocks/mock_knowledge_home_port.go -package=mocks GetKnowledgeHomeItemsPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	knowledge_home_port "alt/port/knowledge_home_port"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGetKnowledgeHomeItemsPort is a mock of GetKnowledgeHomeItemsPort interface.
type MockGetKnowledgeHomeItemsPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetKnowledgeHomeItemsPortMockRecorder
	isgomock struct{}
}

// MockGetKnowledgeHomeItemsPortMockRecorder is the mock recorder for MockGetKnowledgeHomeItemsPort.
type MockGetKnowledgeHomeItemsPortMockRecorder struct {
	mock *MockGetKnowledgeHomeItemsPort
}

// NewMockGetKnowledgeHomeItemsPort creates a new mock instance.
func NewMockGetKnowledgeHomeItemsPort(ctrl *gomock.Controller) *MockGetKnowledgeHomeItemsPort {
	mock := &MockGetKnowledgeHomeItemsPort{ctrl: ctrl}
	mock.recorder = &MockGetKnowledgeHomeItemsPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetKnowledgeHomeItemsPort) EXPECT() *MockGetKnowledgeHomeItemsPortMockRecorder {
	return m.recorder
}

// GetKnowledgeHomeItems mocks base method.
func (m *MockGetKnowledgeHomeItemsPort) GetKnowledgeHomeItems(ctx context.Context, userID uuid.UUID, cursor string, limit int, filter *domain.KnowledgeHomeLensFilter) ([]domain.KnowledgeHomeItem, string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKnowledgeHomeItems", ctx, userID, cursor, limit, filter)
	ret0, _ := ret[0].([]domain.KnowledgeHomeItem)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetKnowledgeHomeItems indicates an expected call of GetKnowledgeHomeItems.
func (mr *MockGetKnowledgeHomeItemsPortMockRecorder) GetKnowledgeHomeItems(ctx, userID, cursor, limit, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnowledgeHomeItems", reflect.TypeOf((*MockGetKnowledgeHomeItemsPort)(nil).GetKnowledgeHomeItems), ctx, userID, cursor, limit, filter)
}

// MockUpsertKnowledgeHomeItemPort is a mock of UpsertKnowledgeHomeItemPort interface.
type MockUpsertKnowledgeHomeItemPort struct {
	ctrl     *gomock.Controller
	recorder *MockUpsertKnowledgeHomeItemPortMockRecorder
	isgomock struct{}
}

// MockUpsertKnowledgeHomeItemPortMockRecorder is the mock recorder for MockUpsertKnowledgeHomeItemPort.
type MockUpsertKnowledgeHomeItemPortMockRecorder struct {
	mock *MockUpsertKnowledgeHomeItemPort
}

// NewMockUpsertKnowledgeHomeItemPort creates a new mock instance.
func NewMockUpsertKnowledgeHomeItemPort(ctrl *gomock.Controller) *MockUpsertKnowledgeHomeItemPort {
	mock := &MockUpsertKnowledgeHomeItemPort{ctrl: ctrl}
	mock.recorder = &MockUpsertKnowledgeHomeItemPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpsertKnowledgeHomeItemPort) EXPECT() *MockUpsertKnowledgeHomeItemPortMockRecorder {
	return m.recorder
}

// UpsertKnowledgeHomeItem mocks base method.
func (m *MockUpsertKnowledgeHomeItemPort) UpsertKnowledgeHomeItem(ctx context.Context, item domain.KnowledgeHomeItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertKnowledgeHomeItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertKnowledgeHomeItem indicates an expected call of UpsertKnowledgeHomeItem.
func (mr *MockUpsertKnowledgeHomeItemPortMockRecorder) UpsertKnowledgeHomeItem(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertKnowledgeHomeItem", reflect.TypeOf((*MockUpsertKnowledgeHomeItemPort)(nil).UpsertKnowledgeHomeItem), ctx, item)
}

// MockDismissKnowledgeHomeItemPort is a mock of DismissKnowledgeHomeItemPort interface.
type MockDismissKnowledgeHomeItemPort struct {
	ctrl     *gomock.Controller
	recorder *MockDismissKnowledgeHomeItemPortMockRecorder
	isgomock struct{}
}

// MockDismissKnowledgeHomeItemPortMockRecorder is the mock recorder for MockDismissKnowledgeHomeItemPort.
type MockDismissKnowledgeHomeItemPortMockRecorder struct {
	mock *MockDismissKnowledgeHomeItemPort
}

// NewMockDismissKnowledgeHomeItemPort creates a new mock instance.
func NewMockDismissKnowledgeHomeItemPort(ctrl *gomock.Controller) *MockDismissKnowledgeHomeItemPort {
	mock := &MockDismissKnowledgeHomeItemPort{ctrl: ctrl}
	mock.recorder = &MockDismissKnowledgeHomeItemPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDismissKnowledgeHomeItemPort) EXPECT() *MockDismissKnowledgeHomeItemPortMockRecorder {
	return m.recorder
}

// DismissKnowledgeHomeItem mocks base method.
func (m *MockDismissKnowledgeHomeItemPort) DismissKnowledgeHomeItem(ctx context.Context, userID uuid.UUID, itemKey string, projectionVersion int, dismissedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DismissKnowledgeHomeItem", ctx, userID, itemKey, projectionVersion, dismissedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// DismissKnowledgeHomeItem indicates an expected call of DismissKnowledgeHomeItem.
func (mr *MockDismissKnowledgeHomeItemPortMockRecorder) DismissKnowledgeHomeItem(ctx, userID, itemKey, projectionVersion, dismissedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DismissKnowledgeHomeItem", reflect.TypeOf((*MockDismissKnowledgeHomeItemPort)(nil).DismissKnowledgeHomeItem), ctx, userID, itemKey, projectionVersion, dismissedAt)
}

// MockClearSupersedeStatePort is a mock of ClearSupersedeStatePort interface.
type MockClearSupersedeStatePort struct {
	ctrl     *gomock.Controller
	recorder *MockClearSupersedeStatePortMockRecorder
	isgomock struct{}
}

// MockClearSupersedeStatePortMockRecorder is the mock recorder for MockClearSupersedeStatePort.
type MockClearSupersedeStatePortMockRecorder struct {
	mock *MockClearSupersedeStatePort
}

// NewMockClearSupersedeStatePort creates a new mock instance.
func NewMockClearSupersedeStatePort(ctrl *gomock.Controller) *MockClearSupersedeStatePort {
	mock := &MockClearSupersedeStatePort{ctrl: ctrl}
	mock.recorder = &MockClearSupersedeStatePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClearSupersedeStatePort) EXPECT() *MockClearSupersedeStatePortMockRecorder {
	return m.recorder
}

// ClearSupersedeState mocks base method.
func (m *MockClearSupersedeStatePort) ClearSupersedeState(ctx context.Context, userID uuid.UUID, itemKey string, projectionVersion int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearSupersedeState", ctx, userID, itemKey, projectionVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearSupersedeState indicates an expected call of ClearSupersedeState.
func (mr *MockClearSupersedeStatePortMockRecorder) ClearSupersedeState(ctx, userID, itemKey, projectionVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearSupersedeState", reflect.TypeOf((*MockClearSupersedeStatePort)(nil).ClearSupersedeState), ctx, userID, itemKey, projectionVersion)
}

// MockListDistinctUserIDsPort is a mock of ListDistinctUserIDsPort interface.
type MockListDistinctUserIDsPort struct {
	ctrl     *gomock.Controller
	recorder *MockListDistinctUserIDsPortMockRecorder
	isgomock struct{}
}

// MockListDistinctUserIDsPortMockRecorder is the mock recorder for MockListDistinctUserIDsPort.
type MockListDistinctUserIDsPortMockRecorder struct {
	mock *MockListDistinctUserIDsPort
}

// NewMockListDistinctUserIDsPort creates a new mock instance.
func NewMockListDistinctUserIDsPort(ctrl *gomock.Controller) *MockListDistinctUserIDsPort {
	mock := &MockListDistinctUserIDsPort{ctrl: ctrl}
	mock.recorder = &MockListDistinctUserIDsPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListDistinctUserIDsPort) EXPECT() *MockListDistinctUserIDsPortMockRecorder {
	return m.recorder
}

// ListDistinctUserIDs mocks base method.
func (m *MockListDistinctUserIDsPort) ListDistinctUserIDs(ctx context.Context) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDistinctUserIDs", ctx)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDistinctUserIDs indicates an expected call of ListDistinctUserIDs.
func (mr *MockListDistinctUserIDsPortMockRecorder) ListDistinctUserIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDistinctUserIDs", reflect.TypeOf((*MockListDistinctUserIDsPort)(nil).ListDistinctUserIDs), ctx)
}

// MockFetchTagArticleCountsPort is a mock of FetchTagArticleCountsPort interface.
type MockFetchTagArticleCountsPort struct {
	ctrl     *gomock.Controller
	recorder *MockFetchTagArticleCountsPortMockRecorder
	isgomock struct{}
}

// MockFetchTagArticleCountsPortMockRecorder is the mock recorder for MockFetchTagArticleCountsPort.
type MockFetchTagArticleCountsPortMockRecorder struct {
	mock *MockFetchTagArticleCountsPort
}

// NewMockFetchTagArticleCountsPort creates a new mock instance.
func NewMockFetchTagArticleCountsPort(ctrl *gomock.Controller) *MockFetchTagArticleCountsPort {
	mock := &MockFetchTagArticleCountsPort{ctrl: ctrl}
	mock.recorder = &MockFetchTagArticleCountsPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFetchTagArticleCountsPort) EXPECT() *MockFetchTagArticleCountsPortMockRecorder {
	return m.recorder
}

// FetchTagArticleCounts mocks base method.
func (m *MockFetchTagArticleCountsPort) FetchTagArticleCounts(ctx context.Context, userID uuid.UUID, since time.Time) ([]knowledge_home_port.TagArticleCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTagArticleCounts", ctx, userID, since)
	ret0, _ := ret[0].([]knowledge_home_port.TagArticleCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTagArticleCounts indicates an expected call of FetchTagArticleCounts.
func (mr *MockFetchTagArticleCountsPortMockRecorder) FetchTagArticleCounts(ctx, userID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTagArticleCounts", reflect.TypeOf((*MockFetchTagArticleCountsPort)(nil).FetchTagArticleCounts), ctx, userID, since)
}

// MockTagHotspotPort is a mock of TagHotspotPort interface.
type MockTagHotspotPort struct {
	ctrl     *gomock.Controller
	recorder *MockTagHotspotPortMockRecorder
	isgomock struct{}
}

// MockTagHotspotPortMockRecorder is the mock recorder for MockTagHotspotPort.
type MockTagHotspotPortMockRecorder struct {
	mock *MockTagHotspotPort
}

// NewMockTagHotspotPort creates a new mock instance.
func NewMockTagHotspotPort(ctrl *gomock.Controller) *MockTagHotspotPort {
	mock := &MockTagHotspotPort{ctrl: ctrl}
	mock.recorder = &MockTagHotspotPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagHotspotPort) EXPECT() *MockTagHotspotPortMockRecorder {
	return m.recorder
}

// GetTrendingTags mocks base method.
func (m *MockTagHotspotPort) GetTrendingTags(ctx context.Context, userID uuid.UUID) ([]knowledge_home_port.TrendingTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrendingTags", ctx, userID)
	ret0, _ := ret[0].([]knowledge_home_port.TrendingTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrendingTags indicates an expected call of GetTrendingTags.
func (mr *MockTagHotspotPortMockRecorder) GetTrendingTags(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrendingTags", reflect.TypeOf((*MockTagHotspotPort)(nil).GetTrendingTags), ctx, userID)
}
