// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/article_content_cache_port/port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/article_content_cache_port/port.go -destination=./alt-backend/app/mocks/mock_article_content_cache_port.go -package=mocks ArticleContentCachePort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockArticleContentCachePort is a mock of ArticleContentCachePort interface.
type MockArticleContentCachePort struct {
	ctrl     *gomock.Controller
	recorder *MockArticleContentCachePortMockRecorder
	isgomock struct{}
}

// MockArticleContentCachePortMockRecorder is the mock recorder for MockArticleContentCachePort.
type MockArticleContentCachePortMockRecorder struct {
	mock *MockArticleContentCachePort
}

// NewMockArticleContentCachePort creates a new mock instance.
func NewMockArticleContentCachePort(ctrl *gomock.Controller) *MockArticleContentCachePort {
	mock := &MockArticleContentCachePort{ctrl: ctrl}
	mock.recorder = &MockArticleContentCachePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleContentCachePort) EXPECT() *MockArticleContentCachePortMockRecorder {
	return m.recorder
}

// GetArticles mocks base method.
func (m *MockArticleContentCachePort) GetArticles(ctx context.Context, articleIDs []uuid.UUID) ([]*domain.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticles", ctx, articleIDs)
	ret0, _ := ret[0].([]*domain.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticles indicates an expected call of GetArticles.
func (mr *MockArticleContentCachePortMockRecorder) GetArticles(ctx, articleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticles", reflect.TypeOf((*MockArticleContentCachePort)(nil).GetArticles), ctx, articleIDs)
}

// InvalidateArticle mocks base method.
func (m *MockArticleContentCachePort) InvalidateArticle(ctx context.Context, articleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateArticle", ctx, articleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateArticle indicates an expected call of InvalidateArticle.
func (mr *MockArticleContentCachePortMockRecorder) InvalidateArticle(ctx, articleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateArticle", reflect.TypeOf((*MockArticleContentCachePort)(nil).InvalidateArticle), ctx, articleID)
}
