// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/scraping_domain_port/scraping_domain_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/scraping_domain_port/scraping_domain_port.go -destination=./alt-backend/app/mocks/mock_scraping_domain_port.go -package=mocks ScrapingDomainPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockScrapingDomainPort is a mock of ScrapingDomainPort interface.
type MockScrapingDomainPort struct {
	ctrl     *gomock.Controller
	recorder *MockScrapingDomainPortMockRecorder
	isgomock struct{}
}

// MockScrapingDomainPortMockRecorder is the mock recorder for MockScrapingDomainPort.
type MockScrapingDomainPortMockRecorder struct {
	mock *MockScrapingDomainPort
}

// NewMockScrapingDomainPort creates a new mock instance.
func NewMockScrapingDomainPort(ctrl *gomock.Controller) *MockScrapingDomainPort {
	mock := &MockScrapingDomainPort{ctrl: ctrl}
	mock.recorder = &MockScrapingDomainPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScrapingDomainPort) EXPECT() *MockScrapingDomainPortMockRecorder {
	return m.recorder
}

// GetByDomain mocks base method.
func (m *MockScrapingDomainPort) GetByDomain(ctx context.Context, arg1 string) (*domain.ScrapingDomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDomain", ctx, arg1)
	ret0, _ := ret[0].(*domain.ScrapingDomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDomain indicates an expected call of GetByDomain.
func (mr *MockScrapingDomainPortMockRecorder) GetByDomain(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDomain", reflect.TypeOf((*MockScrapingDomainPort)(nil).GetByDomain), ctx, arg1)
}

// GetByID mocks base method.
func (m *MockScrapingDomainPort) GetByID(ctx context.Context, id uuid.UUID) (*domain.ScrapingDomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.ScrapingDomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockScrapingDomainPortMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockScrapingDomainPort)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockScrapingDomainPort) List(ctx context.Context, offset, limit int) ([]*domain.ScrapingDomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit)
	ret0, _ := ret[0].([]*domain.ScrapingDomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockScrapingDomainPortMockRecorder) List(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockScrapingDomainPort)(nil).List), ctx, offset, limit)
}

// Save mocks base method.
func (m *MockScrapingDomainPort) Save(ctx context.Context, arg1 *domain.ScrapingDomain) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockScrapingDomainPortMockRecorder) Save(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockScrapingDomainPort)(nil).Save), ctx, arg1)
}

// UpdatePolicy mocks base method.
func (m *MockScrapingDomainPort) UpdatePolicy(ctx context.Context, id uuid.UUID, update *domain.ScrapingPolicyUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePolicy", ctx, id, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePolicy indicates an expected call of UpdatePolicy.
func (mr *MockScrapingDomainPortMockRecorder) UpdatePolicy(ctx, id, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePolicy", reflect.TypeOf((*MockScrapingDomainPort)(nil).UpdatePolicy), ctx, id, update)
}
