// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/latest_article_port/latest_article_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/latest_article_port/latest_article_port.go -destination=./alt-backend/app/mocks/mock_latest_article_port.go -package=mocks FetchLatestArticlePort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockFetchLatestArticlePort is a mock of FetchLatestArticlePort interface.
type MockFetchLatestArticlePort struct {
	ctrl     *gomock.Controller
	recorder *MockFetchLatestArticlePortMockRecorder
	isgomock struct{}
}

// MockFetchLatestArticlePortMockRecorder is the mock recorder for MockFetchLatestArticlePort.
type MockFetchLatestArticlePortMockRecorder struct {
	mock *MockFetchLatestArticlePort
}

// NewMockFetchLatestArticlePort creates a new mock instance.
func NewMockFetchLatestArticlePort(ctrl *gomock.Controller) *MockFetchLatestArticlePort {
	mock := &MockFetchLatestArticlePort{ctrl: ctrl}
	mock.recorder = &MockFetchLatestArticlePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFetchLatestArticlePort) EXPECT() *MockFetchLatestArticlePortMockRecorder {
	return m.recorder
}

// FetchLatestArticleByFeedID mocks base method.
func (m *MockFetchLatestArticlePort) FetchLatestArticleByFeedID(ctx context.Context, feedID uuid.UUID) (*domain.ArticleContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchLatestArticleByFeedID", ctx, feedID)
	ret0, _ := ret[0].(*domain.ArticleContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchLatestArticleByFeedID indicates an expected call of FetchLatestArticleByFeedID.
func (mr *MockFetchLatestArticlePortMockRecorder) FetchLatestArticleByFeedID(ctx, feedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchLatestArticleByFeedID", reflect.TypeOf((*MockFetchLatestArticlePort)(nil).FetchLatestArticleByFeedID), ctx, feedID)
}
