// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/knowledge_reproject_port/port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/knowledge_reproject_port/port.go -destination=./alt-backend/app/mocks/mock_knowledge_reproject_port.go -package=mocks CreateReprojectRunPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateReprojectRunPort is a mock of CreateReprojectRunPort interface.
type MockCreateReprojectRunPort struct {
	ctrl     *gomock.Controller
	recorder *MockCreateReprojectRunPortMockRecorder
	isgomock struct{}
}

// MockCreateReprojectRunPortMockRecorder is the mock recorder for MockCreateReprojectRunPort.
type MockCreateReprojectRunPortMockRecorder struct {
	mock *MockCreateReprojectRunPort
}

// NewMockCreateReprojectRunPort creates a new mock instance.
func NewMockCreateReprojectRunPort(ctrl *gomock.Controller) *MockCreateReprojectRunPort {
	mock := &MockCreateReprojectRunPort{ctrl: ctrl}
	mock.recorder = &MockCreateReprojectRunPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateReprojectRunPort) EXPECT() *MockCreateReprojectRunPortMockRecorder {
	return m.recorder
}

// CreateReprojectRun mocks base method.
func (m *MockCreateReprojectRunPort) CreateReprojectRun(ctx context.Context, run *domain.ReprojectRun) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReprojectRun", ctx, run)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateReprojectRun indicates an expected call of CreateReprojectRun.
func (mr *MockCreateReprojectRunPortMockRecorder) CreateReprojectRun(ctx, run any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReprojectRun", reflect.TypeOf((*MockCreateReprojectRunPort)(nil).CreateReprojectRun), ctx, run)
}

// MockGetReprojectRunPort is a mock of GetReprojectRunPort interface.
type MockGetReprojectRunPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetReprojectRunPortMockRecorder
	isgomock struct{}
}

// MockGetReprojectRunPortMockRecorder is the mock recorder for MockGetReprojectRunPort.
type MockGetReprojectRunPortMockRecorder struct {
	mock *MockGetReprojectRunPort
}

// NewMockGetReprojectRunPort creates a new mock instance.
func NewMockGetReprojectRunPort(ctrl *gomock.Controller) *MockGetReprojectRunPort {
	mock := &MockGetReprojectRunPort{ctrl: ctrl}
	mock.recorder = &MockGetReprojectRunPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetReprojectRunPort) EXPECT() *MockGetReprojectRunPortMockRecorder {
	return m.recorder
}

// GetReprojectRun mocks base method.
func (m *MockGetReprojectRunPort) GetReprojectRun(ctx context.Context, runID uuid.UUID) (*domain.ReprojectRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReprojectRun", ctx, runID)
	ret0, _ := ret[0].(*domain.ReprojectRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReprojectRun indicates an expected call of GetReprojectRun.
func (mr *MockGetReprojectRunPortMockRecorder) GetReprojectRun(ctx, runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReprojectRun", reflect.TypeOf((*MockGetReprojectRunPort)(nil).GetReprojectRun), ctx, runID)
}

// MockUpdateReprojectRunPort is a mock of UpdateReprojectRunPort interface.
type MockUpdateReprojectRunPort struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateReprojectRunPortMockRecorder
	isgomock struct{}
}

// MockUpdateReprojectRunPortMockRecorder is the mock recorder for MockUpdateReprojectRunPort.
type MockUpdateReprojectRunPortMockRecorder struct {
	mock *MockUpdateReprojectRunPort
}

// NewMockUpdateReprojectRunPort creates a new mock instance.
func NewMockUpdateReprojectRunPort(ctrl *gomock.Controller) *MockUpdateReprojectRunPort {
	mock := &MockUpdateReprojectRunPort{ctrl: ctrl}
	mock.recorder = &MockUpdateReprojectRunPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateReprojectRunPort) EXPECT() *MockUpdateReprojectRunPortMockRecorder {
	return m.recorder
}

// UpdateReprojectRun mocks base method.
func (m *MockUpdateReprojectRunPort) UpdateReprojectRun(ctx context.Context, run *domain.ReprojectRun) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReprojectRun", ctx, run)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReprojectRun indicates an expected call of UpdateReprojectRun.
func (mr *MockUpdateReprojectRunPortMockRecorder) UpdateReprojectRun(ctx, run any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReprojectRun", reflect.TypeOf((*MockUpdateReprojectRunPort)(nil).UpdateReprojectRun), ctx, run)
}

// MockListReprojectRunsPort is a mock of ListReprojectRunsPort interface.
type MockListReprojectRunsPort struct {
	ctrl     *gomock.Controller
	recorder *MockListReprojectRunsPortMockRecorder
	isgomock struct{}
}

// MockListReprojectRunsPortMockRecorder is the mock recorder for MockListReprojectRunsPort.
type MockListReprojectRunsPortMockRecorder struct {
	mock *MockListReprojectRunsPort
}

// NewMockListReprojectRunsPort creates a new mock instance.
func NewMockListReprojectRunsPort(ctrl *gomock.Controller) *MockListReprojectRunsPort {
	mock := &MockListReprojectRunsPort{ctrl: ctrl}
	mock.recorder = &MockListReprojectRunsPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListReprojectRunsPort) EXPECT() *MockListReprojectRunsPortMockRecorder {
	return m.recorder
}

// ListReprojectRuns mocks base method.
func (m *MockListReprojectRunsPort) ListReprojectRuns(ctx context.Context, statusFilter string, limit int) ([]domain.ReprojectRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReprojectRuns", ctx, statusFilter, limit)
	ret0, _ := ret[0].([]domain.ReprojectRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReprojectRuns indicates an expected call of ListReprojectRuns.
func (mr *MockListReprojectRunsPortMockRecorder) ListReprojectRuns(ctx, statusFilter, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReprojectRuns", reflect.TypeOf((*MockListReprojectRunsPort)(nil).ListReprojectRuns), ctx, statusFilter, limit)
}

// MockCompareProjectionsPort is a mock of CompareProjectionsPort interface.
type MockCompareProjectionsPort struct {
	ctrl     *gomock.Controller
	recorder *MockCompareProjectionsPortMockRecorder
	isgomock struct{}
}

// MockCompareProjectionsPortMockRecorder is the mock recorder for MockCompareProjectionsPort.
type MockCompareProjectionsPortMockRecorder struct {
	mock *MockCompareProjectionsPort
}

// NewMockCompareProjectionsPort creates a new mock instance.
func NewMockCompareProjectionsPort(ctrl *gomock.Controller) *MockCompareProjectionsPort {
	mock := &MockCompareProjectionsPort{ctrl: ctrl}
	mock.recorder = &MockCompareProjectionsPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompareProjectionsPort) EXPECT() *MockCompareProjectionsPortMockRecorder {
	return m.recorder
}

// CompareProjections mocks base method.
func (m *MockCompareProjectionsPort) CompareProjections(ctx context.Context, fromVersion, toVersion string) (*domain.ReprojectDiffSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareProjections", ctx, fromVersion, toVersion)
	ret0, _ := ret[0].(*domain.ReprojectDiffSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompareProjections indicates an expected call of CompareProjections.
func (mr *MockCompareProjectionsPortMockRecorder) CompareProjections(ctx, fromVersion, toVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareProjections", reflect.TypeOf((*MockCompareProjectionsPort)(nil).CompareProjections), ctx, fromVersion, toVersion)
}

// MockCreateProjectionAuditPort is a mock of CreateProjectionAuditPort interface.
type MockCreateProjectionAuditPort struct {
	ctrl     *gomock.Controller
	recorder *MockCreateProjectionAuditPortMockRecorder
	isgomock struct{}
}

// MockCreateProjectionAuditPortMockRecorder is the mock recorder for MockCreateProjectionAuditPort.
type MockCreateProjectionAuditPortMockRecorder struct {
	mock *MockCreateProjectionAuditPort
}

// NewMockCreateProjectionAuditPort creates a new mock instance.
func NewMockCreateProjectionAuditPort(ctrl *gomock.Controller) *MockCreateProjectionAuditPort {
	mock := &MockCreateProjectionAuditPort{ctrl: ctrl}
	mock.recorder = &MockCreateProjectionAuditPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateProjectionAuditPort) EXPECT() *MockCreateProjectionAuditPortMockRecorder {
	return m.recorder
}

// CreateProjectionAudit mocks base method.
func (m *MockCreateProjectionAuditPort) CreateProjectionAudit(ctx context.Context, audit *domain.ProjectionAudit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProjectionAudit", ctx, audit)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProjectionAudit indicates an expected call of CreateProjectionAudit.
func (mr *MockCreateProjectionAuditPortMockRecorder) CreateProjectionAudit(ctx, audit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProjectionAudit", reflect.TypeOf((*MockCreateProjectionAuditPort)(nil).CreateProjectionAudit), ctx, audit)
}

// MockListProjectionAuditsPort is a mock of ListProjectionAuditsPort interface.
type MockListProjectionAuditsPort struct {
	ctrl     *gomock.Controller
	recorder *MockListProjectionAuditsPortMockRecorder
	isgomock struct{}
}

// MockListProjectionAuditsPortMockRecorder is the mock recorder for MockListProjectionAuditsPort.
type MockListProjectionAuditsPortMockRecorder struct {
	mock *MockListProjectionAuditsPort
}

// NewMockListProjectionAuditsPort creates a new mock instance.
func NewMockListProjectionAuditsPort(ctrl *gomock.Controller) *MockListProjectionAuditsPort {
	mock := &MockListProjectionAuditsPort{ctrl: ctrl}
	mock.recorder = &MockListProjectionAuditsPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListProjectionAuditsPort) EXPECT() *MockListProjectionAuditsPortMockRecorder {
	return m.recorder
}

// ListProjectionAudits mocks base method.
func (m *MockListProjectionAuditsPort) ListProjectionAudits(ctx context.Context, projectionName string, limit int) ([]domain.ProjectionAudit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectionAudits", ctx, projectionName, limit)
	ret0, _ := ret[0].([]domain.ProjectionAudit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectionAudits indicates an expected call of ListProjectionAudits.
func (mr *MockListProjectionAuditsPortMockRecorder) ListProjectionAudits(ctx, projectionName, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectionAudits", reflect.TypeOf((*MockListProjectionAuditsPort)(nil).ListProjectionAudits), ctx, projectionName, limit)
}
