// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/knowledge_projection_port/port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/knowledge_projection_port/port.go -destination=./alt-backend/app/mocks/mock_knowledge_projection_port.go -package=mocks GetProjectionCheckpointPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetProjectionCheckpointPort is a mock of GetProjectionCheckpointPort interface.
type MockGetProjectionCheckpointPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetProjectionCheckpointPortMockRecorder
	isgomock struct{}
}

// MockGetProjectionCheckpointPortMockRecorder is the mock recorder for MockGetProjectionCheckpointPort.
type MockGetProjectionCheckpointPortMockRecorder struct {
	mock *MockGetProjectionCheckpointPort
}

// NewMockGetProjectionCheckpointPort creates a new mock instance.
func NewMockGetProjectionCheckpointPort(ctrl *gomock.Controller) *MockGetProjectionCheckpointPort {
	mock := &MockGetProjectionCheckpointPort{ctrl: ctrl}
	mock.recorder = &MockGetProjectionCheckpointPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetProjectionCheckpointPort) EXPECT() *MockGetProjectionCheckpointPortMockRecorder {
	return m.recorder
}

// GetProjectionCheckpoint mocks base method.
func (m *MockGetProjectionCheckpointPort) GetProjectionCheckpoint(ctx context.Context, projectorName string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectionCheckpoint", ctx, projectorName)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectionCheckpoint indicates an expected call of GetProjectionCheckpoint.
func (mr *MockGetProjectionCheckpointPortMockRecorder) GetProjectionCheckpoint(ctx, projectorName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectionCheckpoint", reflect.TypeOf((*MockGetProjectionCheckpointPort)(nil).GetProjectionCheckpoint), ctx, projectorName)
}

// MockUpdateProjectionCheckpointPort is a mock of UpdateProjectionCheckpointPort interface.
type MockUpdateProjectionCheckpointPort struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateProjectionCheckpointPortMockRecorder
	isgomock struct{}
}

// MockUpdateProjectionCheckpointPortMockRecorder is the mock recorder for MockUpdateProjectionCheckpointPort.
type MockUpdateProjectionCheckpointPortMockRecorder struct {
	mock *MockUpdateProjectionCheckpointPort
}

// NewMockUpdateProjectionCheckpointPort creates a new mock instance.
func NewMockUpdateProjectionCheckpointPort(ctrl *gomock.Controller) *MockUpdateProjectionCheckpointPort {
	mock := &MockUpdateProjectionCheckpointPort{ctrl: ctrl}
	mock.recorder = &MockUpdateProjectionCheckpointPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateProjectionCheckpointPort) EXPECT() *MockUpdateProjectionCheckpointPortMockRecorder {
	return m.recorder
}

// UpdateProjectionCheckpoint mocks base method.
func (m *MockUpdateProjectionCheckpointPort) UpdateProjectionCheckpoint(ctx context.Context, projectorName string, lastSeq int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProjectionCheckpoint", ctx, projectorName, lastSeq)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProjectionCheckpoint indicates an expected call of UpdateProjectionCheckpoint.
func (mr *MockUpdateProjectionCheckpointPortMockRecorder) UpdateProjectionCheckpoint(ctx, projectorName, lastSeq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProjectionCheckpoint", reflect.TypeOf((*MockUpdateProjectionCheckpointPort)(nil).UpdateProjectionCheckpoint), ctx, projectorName, lastSeq)
}
