// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/article_status_port/update_article_status_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/article_status_port/update_article_status_port.go -destination=./alt-backend/app/mocks/mock_article_status_port.go -package=mocks UpdateArticleStatusPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	url "net/url"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUpdateArticleStatusPort is a mock of UpdateArticleStatusPort interface.
type MockUpdateArticleStatusPort struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateArticleStatusPortMockRecorder
	isgomock struct{}
}

// MockUpdateArticleStatusPortMockRecorder is the mock recorder for MockUpdateArticleStatusPort.
type MockUpdateArticleStatusPortMockRecorder struct {
	mock *MockUpdateArticleStatusPort
}

// NewMockUpdateArticleStatusPort creates a new mock instance.
func NewMockUpdateArticleStatusPort(ctrl *gomock.Controller) *MockUpdateArticleStatusPort {
	mock := &MockUpdateArticleStatusPort{ctrl: ctrl}
	mock.recorder = &MockUpdateArticleStatusPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateArticleStatusPort) EXPECT() *MockUpdateArticleStatusPortMockRecorder {
	return m.recorder
}

// MarkArticleAsRead mocks base method.
func (m *MockUpdateArticleStatusPort) MarkArticleAsRead(ctx context.Context, articleURL url.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkArticleAsRead", ctx, articleURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkArticleAsRead indicates an expected call of MarkArticleAsRead.
func (mr *MockUpdateArticleStatusPortMockRecorder) MarkArticleAsRead(ctx, articleURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkArticleAsRead", reflect.TypeOf((*MockUpdateArticleStatusPort)(nil).MarkArticleAsRead), ctx, articleURL)
}
