// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/subscription_port/subscription_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/subscription_port/subscription_port.go -destination=./alt-backend/app/mocks/mock_subscription_port.go -package=mocks SubscriptionPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionPort is a mock of SubscriptionPort interface.
type MockSubscriptionPort struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionPortMockRecorder
	isgomock struct{}
}

// MockSubscriptionPortMockRecorder is the mock recorder for MockSubscriptionPort.
type MockSubscriptionPortMockRecorder struct {
	mock *MockSubscriptionPort
}

// NewMockSubscriptionPort creates a new mock instance.
func NewMockSubscriptionPort(ctrl *gomock.Controller) *MockSubscriptionPort {
	mock := &MockSubscriptionPort{ctrl: ctrl}
	mock.recorder = &MockSubscriptionPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionPort) EXPECT() *MockSubscriptionPortMockRecorder {
	return m.recorder
}

// ListSubscriptions mocks base method.
func (m *MockSubscriptionPort) ListSubscriptions(ctx context.Context, userID uuid.UUID) ([]*domain.FeedSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubscriptions", ctx, userID)
	ret0, _ := ret[0].([]*domain.FeedSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubscriptions indicates an expected call of ListSubscriptions.
func (mr *MockSubscriptionPortMockRecorder) ListSubscriptions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubscriptions", reflect.TypeOf((*MockSubscriptionPort)(nil).ListSubscriptions), ctx, userID)
}

// Subscribe mocks base method.
func (m *MockSubscriptionPort) Subscribe(ctx context.Context, userID, feedLinkID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, userID, feedLinkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockSubscriptionPortMockRecorder) Subscribe(ctx, userID, feedLinkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockSubscriptionPort)(nil).Subscribe), ctx, userID, feedLinkID)
}

// Unsubscribe mocks base method.
func (m *MockSubscriptionPort) Unsubscribe(ctx context.Context, userID, feedLinkID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", ctx, userID, feedLinkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockSubscriptionPortMockRecorder) Unsubscribe(ctx, userID, feedLinkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockSubscriptionPort)(nil).Unsubscribe), ctx, userID, feedLinkID)
}
