// Code generated by MockGen. DO NOT EDIT.
// Source: app/port/rag_integration_port/rag_integration_port.go
//
// Generated by this command:
//
//	mockgen -source=app/port/rag_integration_port/rag_integration_port.go -destination=app/mocks/mock_rag_integration_port.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	rag_integration_port "alt/port/rag_integration_port"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRagIntegrationPort is a mock of RagIntegrationPort interface.
type MockRagIntegrationPort struct {
	ctrl     *gomock.Controller
	recorder *MockRagIntegrationPortMockRecorder
	isgomock struct{}
}

// MockRagIntegrationPortMockRecorder is the mock recorder for MockRagIntegrationPort.
type MockRagIntegrationPortMockRecorder struct {
	mock *MockRagIntegrationPort
}

// NewMockRagIntegrationPort creates a new mock instance.
func NewMockRagIntegrationPort(ctrl *gomock.Controller) *MockRagIntegrationPort {
	mock := &MockRagIntegrationPort{ctrl: ctrl}
	mock.recorder = &MockRagIntegrationPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRagIntegrationPort) EXPECT() *MockRagIntegrationPortMockRecorder {
	return m.recorder
}

// UpsertArticle mocks base method.
func (m *MockRagIntegrationPort) UpsertArticle(ctx context.Context, input rag_integration_port.UpsertArticleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertArticle", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertArticle indicates an expected call of UpsertArticle.
func (mr *MockRagIntegrationPortMockRecorder) UpsertArticle(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertArticle", reflect.TypeOf((*MockRagIntegrationPort)(nil).UpsertArticle), ctx, input)
}
