// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/feed_link_port/feed_link_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/feed_link_port/feed_link_port.go -destination=./alt-backend/app/mocks/mock_feed_link_port.go -package=mocks FeedLinkPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockFeedLinkPort is a mock of FeedLinkPort interface.
type MockFeedLinkPort struct {
	ctrl     *gomock.Controller
	recorder *MockFeedLinkPortMockRecorder
	isgomock struct{}
}

// MockFeedLinkPortMockRecorder is the mock recorder for MockFeedLinkPort.
type MockFeedLinkPortMockRecorder struct {
	mock *MockFeedLinkPort
}

// NewMockFeedLinkPort creates a new mock instance.
func NewMockFeedLinkPort(ctrl *gomock.Controller) *MockFeedLinkPort {
	mock := &MockFeedLinkPort{ctrl: ctrl}
	mock.recorder = &MockFeedLinkPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedLinkPort) EXPECT() *MockFeedLinkPortMockRecorder {
	return m.recorder
}

// DeleteFeedLink mocks base method.
func (m *MockFeedLinkPort) DeleteFeedLink(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFeedLink", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFeedLink indicates an expected call of DeleteFeedLink.
func (mr *MockFeedLinkPortMockRecorder) DeleteFeedLink(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFeedLink", reflect.TypeOf((*MockFeedLinkPort)(nil).DeleteFeedLink), ctx, id)
}

// ListFeedLinks mocks base method.
func (m *MockFeedLinkPort) ListFeedLinks(ctx context.Context) ([]*domain.FeedLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFeedLinks", ctx)
	ret0, _ := ret[0].([]*domain.FeedLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFeedLinks indicates an expected call of ListFeedLinks.
func (mr *MockFeedLinkPortMockRecorder) ListFeedLinks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFeedLinks", reflect.TypeOf((*MockFeedLinkPort)(nil).ListFeedLinks), ctx)
}
