// Code generated by MockGen. DO NOT EDIT.
// Source: orchestrator/port/article_url_lookup_port/lookup.go
//
// Generated by this command:
//
//	mockgen -source=orchestrator/port/article_url_lookup_port/lookup.go -destination=mocks/mock_article_url_lookup_port.go -package=mocks ArticleURLLookupPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockArticleURLLookupPort is a mock of ArticleURLLookupPort interface.
type MockArticleURLLookupPort struct {
	ctrl     *gomock.Controller
	recorder *MockArticleURLLookupPortMockRecorder
	isgomock struct{}
}

// MockArticleURLLookupPortMockRecorder is the mock recorder for MockArticleURLLookupPort.
type MockArticleURLLookupPortMockRecorder struct {
	mock *MockArticleURLLookupPort
}

// NewMockArticleURLLookupPort creates a new mock instance.
func NewMockArticleURLLookupPort(ctrl *gomock.Controller) *MockArticleURLLookupPort {
	mock := &MockArticleURLLookupPort{ctrl: ctrl}
	mock.recorder = &MockArticleURLLookupPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleURLLookupPort) EXPECT() *MockArticleURLLookupPortMockRecorder {
	return m.recorder
}

// LookupArticleSource mocks base method.
func (m *MockArticleURLLookupPort) LookupArticleSource(ctx context.Context, articleID string, userID uuid.UUID) (domain.ArticleSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupArticleSource", ctx, articleID, userID)
	ret0, _ := ret[0].(domain.ArticleSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupArticleSource indicates an expected call of LookupArticleSource.
func (mr *MockArticleURLLookupPortMockRecorder) LookupArticleSource(ctx, articleID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupArticleSource", reflect.TypeOf((*MockArticleURLLookupPort)(nil).LookupArticleSource), ctx, articleID, userID)
}
