// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/image_proxy_port/image_proxy_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/image_proxy_port/image_proxy_port.go -destination=./alt-backend/app/mocks/mock_image_proxy_port.go -package=mocks ImageProxyCachePort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockImageProxyCachePort is a mock of ImageProxyCachePort interface.
type MockImageProxyCachePort struct {
	ctrl     *gomock.Controller
	recorder *MockImageProxyCachePortMockRecorder
	isgomock struct{}
}

// MockImageProxyCachePortMockRecorder is the mock recorder for MockImageProxyCachePort.
type MockImageProxyCachePortMockRecorder struct {
	mock *MockImageProxyCachePort
}

// NewMockImageProxyCachePort creates a new mock instance.
func NewMockImageProxyCachePort(ctrl *gomock.Controller) *MockImageProxyCachePort {
	mock := &MockImageProxyCachePort{ctrl: ctrl}
	mock.recorder = &MockImageProxyCachePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageProxyCachePort) EXPECT() *MockImageProxyCachePortMockRecorder {
	return m.recorder
}

// CleanupExpiredImages mocks base method.
func (m *MockImageProxyCachePort) CleanupExpiredImages(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpiredImages", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupExpiredImages indicates an expected call of CleanupExpiredImages.
func (mr *MockImageProxyCachePortMockRecorder) CleanupExpiredImages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredImages", reflect.TypeOf((*MockImageProxyCachePort)(nil).CleanupExpiredImages), ctx)
}

// GetCachedImage mocks base method.
func (m *MockImageProxyCachePort) GetCachedImage(ctx context.Context, urlHash string) (*domain.ImageProxyCacheEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedImage", ctx, urlHash)
	ret0, _ := ret[0].(*domain.ImageProxyCacheEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCachedImage indicates an expected call of GetCachedImage.
func (mr *MockImageProxyCachePortMockRecorder) GetCachedImage(ctx, urlHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedImage", reflect.TypeOf((*MockImageProxyCachePort)(nil).GetCachedImage), ctx, urlHash)
}

// SaveCachedImage mocks base method.
func (m *MockImageProxyCachePort) SaveCachedImage(ctx context.Context, entry *domain.ImageProxyCacheEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCachedImage", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCachedImage indicates an expected call of SaveCachedImage.
func (mr *MockImageProxyCachePortMockRecorder) SaveCachedImage(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCachedImage", reflect.TypeOf((*MockImageProxyCachePort)(nil).SaveCachedImage), ctx, entry)
}

// MockImageProcessingPort is a mock of ImageProcessingPort interface.
type MockImageProcessingPort struct {
	ctrl     *gomock.Controller
	recorder *MockImageProcessingPortMockRecorder
	isgomock struct{}
}

// MockImageProcessingPortMockRecorder is the mock recorder for MockImageProcessingPort.
type MockImageProcessingPortMockRecorder struct {
	mock *MockImageProcessingPort
}

// NewMockImageProcessingPort creates a new mock instance.
func NewMockImageProcessingPort(ctrl *gomock.Controller) *MockImageProcessingPort {
	mock := &MockImageProcessingPort{ctrl: ctrl}
	mock.recorder = &MockImageProcessingPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageProcessingPort) EXPECT() *MockImageProcessingPortMockRecorder {
	return m.recorder
}

// ProcessImage mocks base method.
func (m *MockImageProcessingPort) ProcessImage(ctx context.Context, data []byte, contentType string, maxWidth, quality int) (*domain.ImageProxyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessImage", ctx, data, contentType, maxWidth, quality)
	ret0, _ := ret[0].(*domain.ImageProxyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessImage indicates an expected call of ProcessImage.
func (mr *MockImageProcessingPortMockRecorder) ProcessImage(ctx, data, contentType, maxWidth, quality any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessImage", reflect.TypeOf((*MockImageProcessingPort)(nil).ProcessImage), ctx, data, contentType, maxWidth, quality)
}

// MockImageProxySignerPort is a mock of ImageProxySignerPort interface.
type MockImageProxySignerPort struct {
	ctrl     *gomock.Controller
	recorder *MockImageProxySignerPortMockRecorder
	isgomock struct{}
}

// MockImageProxySignerPortMockRecorder is the mock recorder for MockImageProxySignerPort.
type MockImageProxySignerPortMockRecorder struct {
	mock *MockImageProxySignerPort
}

// NewMockImageProxySignerPort creates a new mock instance.
func NewMockImageProxySignerPort(ctrl *gomock.Controller) *MockImageProxySignerPort {
	mock := &MockImageProxySignerPort{ctrl: ctrl}
	mock.recorder = &MockImageProxySignerPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageProxySignerPort) EXPECT() *MockImageProxySignerPortMockRecorder {
	return m.recorder
}

// GenerateProxyURL mocks base method.
func (m *MockImageProxySignerPort) GenerateProxyURL(imageURL string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateProxyURL", imageURL)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateProxyURL indicates an expected call of GenerateProxyURL.
func (mr *MockImageProxySignerPortMockRecorder) GenerateProxyURL(imageURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateProxyURL", reflect.TypeOf((*MockImageProxySignerPort)(nil).GenerateProxyURL), imageURL)
}

// VerifyAndDecode mocks base method.
func (m *MockImageProxySignerPort) VerifyAndDecode(signature, encodedURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAndDecode", signature, encodedURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAndDecode indicates an expected call of VerifyAndDecode.
func (mr *MockImageProxySignerPortMockRecorder) VerifyAndDecode(signature, encodedURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAndDecode", reflect.TypeOf((*MockImageProxySignerPort)(nil).VerifyAndDecode), signature, encodedURL)
}
