// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/search_indexer_port/search_indexer_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/search_indexer_port/search_indexer_port.go -destination=./alt-backend/app/mocks/mock_search_indexer_port.go -package=mocks SearchIndexerPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSearchIndexerPort is a mock of SearchIndexerPort interface.
type MockSearchIndexerPort struct {
	ctrl     *gomock.Controller
	recorder *MockSearchIndexerPortMockRecorder
	isgomock struct{}
}

// MockSearchIndexerPortMockRecorder is the mock recorder for MockSearchIndexerPort.
type MockSearchIndexerPortMockRecorder struct {
	mock *MockSearchIndexerPort
}

// NewMockSearchIndexerPort creates a new mock instance.
func NewMockSearchIndexerPort(ctrl *gomock.Controller) *MockSearchIndexerPort {
	mock := &MockSearchIndexerPort{ctrl: ctrl}
	mock.recorder = &MockSearchIndexerPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchIndexerPort) EXPECT() *MockSearchIndexerPortMockRecorder {
	return m.recorder
}

// SearchArticles mocks base method.
func (m *MockSearchIndexerPort) SearchArticles(ctx context.Context, query, userID string) ([]domain.SearchIndexerArticleHit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchArticles", ctx, query, userID)
	ret0, _ := ret[0].([]domain.SearchIndexerArticleHit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchArticles indicates an expected call of SearchArticles.
func (mr *MockSearchIndexerPortMockRecorder) SearchArticles(ctx, query, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchArticles", reflect.TypeOf((*MockSearchIndexerPort)(nil).SearchArticles), ctx, query, userID)
}

// SearchArticlesWithPagination mocks base method.
func (m *MockSearchIndexerPort) SearchArticlesWithPagination(ctx context.Context, query, userID string, offset, limit int) ([]domain.SearchIndexerArticleHit, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchArticlesWithPagination", ctx, query, userID, offset, limit)
	ret0, _ := ret[0].([]domain.SearchIndexerArticleHit)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchArticlesWithPagination indicates an expected call of SearchArticlesWithPagination.
func (mr *MockSearchIndexerPortMockRecorder) SearchArticlesWithPagination(ctx, query, userID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchArticlesWithPagination", reflect.TypeOf((*MockSearchIndexerPort)(nil).SearchArticlesWithPagination), ctx, query, userID, offset, limit)
}

// SearchRecapsByTag mocks base method.
func (m *MockSearchIndexerPort) SearchRecapsByTag(ctx context.Context, tagName string, limit int) ([]*domain.RecapSearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRecapsByTag", ctx, tagName, limit)
	ret0, _ := ret[0].([]*domain.RecapSearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRecapsByTag indicates an expected call of SearchRecapsByTag.
func (mr *MockSearchIndexerPortMockRecorder) SearchRecapsByTag(ctx, tagName, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRecapsByTag", reflect.TypeOf((*MockSearchIndexerPort)(nil).SearchRecapsByTag), ctx, tagName, limit)
}

// SearchRecapsByQuery mocks base method.
func (m *MockSearchIndexerPort) SearchRecapsByQuery(ctx context.Context, query string, limit int) ([]*domain.RecapSearchResult, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRecapsByQuery", ctx, query, limit)
	ret0, _ := ret[0].([]*domain.RecapSearchResult)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchRecapsByQuery indicates an expected call of SearchRecapsByQuery.
func (mr *MockSearchIndexerPortMockRecorder) SearchRecapsByQuery(ctx, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRecapsByQuery", reflect.TypeOf((*MockSearchIndexerPort)(nil).SearchRecapsByQuery), ctx, query, limit)
}
