// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/morning_letter_port/stream_chat_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/morning_letter_port/stream_chat_port.go -destination=./alt-backend/app/mocks/mock_morning_letter_port.go -package=mocks StreamChatPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	v2 "alt/gen/proto/alt/morning_letter/v2"
	context "context"
	reflect "reflect"

	connect "connectrpc.com/connect"
	gomock "go.uber.org/mock/gomock"
)

// MockStreamChatPort is a mock of StreamChatPort interface.
type MockStreamChatPort struct {
	ctrl     *gomock.Controller
	recorder *MockStreamChatPortMockRecorder
	isgomock struct{}
}

// MockStreamChatPortMockRecorder is the mock recorder for MockStreamChatPort.
type MockStreamChatPortMockRecorder struct {
	mock *MockStreamChatPort
}

// NewMockStreamChatPort creates a new mock instance.
func NewMockStreamChatPort(ctrl *gomock.Controller) *MockStreamChatPort {
	mock := &MockStreamChatPort{ctrl: ctrl}
	mock.recorder = &MockStreamChatPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamChatPort) EXPECT() *MockStreamChatPortMockRecorder {
	return m.recorder
}

// StreamChat mocks base method.
func (m *MockStreamChatPort) StreamChat(ctx context.Context, messages []*v2.ChatMessage, withinHours int32) (*connect.ServerStreamForClient[v2.StreamChatResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamChat", ctx, messages, withinHours)
	ret0, _ := ret[0].(*connect.ServerStreamForClient[v2.StreamChatResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamChat indicates an expected call of StreamChat.
func (mr *MockStreamChatPortMockRecorder) StreamChat(ctx, messages, withinHours any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamChat", reflect.TypeOf((*MockStreamChatPort)(nil).StreamChat), ctx, messages, withinHours)
}
