// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/user_feed_port/user_feed_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/user_feed_port/user_feed_port.go -destination=./alt-backend/app/mocks/mock_user_feed_port.go -package=mocks UserFeedPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserFeedPort is a mock of UserFeedPort interface.
type MockUserFeedPort struct {
	ctrl     *gomock.Controller
	recorder *MockUserFeedPortMockRecorder
	isgomock struct{}
}

// MockUserFeedPortMockRecorder is the mock recorder for MockUserFeedPort.
type MockUserFeedPortMockRecorder struct {
	mock *MockUserFeedPort
}

// NewMockUserFeedPort creates a new mock instance.
func NewMockUserFeedPort(ctrl *gomock.Controller) *MockUserFeedPort {
	mock := &MockUserFeedPort{ctrl: ctrl}
	mock.recorder = &MockUserFeedPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserFeedPort) EXPECT() *MockUserFeedPortMockRecorder {
	return m.recorder
}

// GetUserFeedIDs mocks base method.
func (m *MockUserFeedPort) GetUserFeedIDs(ctx context.Context) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFeedIDs", ctx)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFeedIDs indicates an expected call of GetUserFeedIDs.
func (mr *MockUserFeedPortMockRecorder) GetUserFeedIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFeedIDs", reflect.TypeOf((*MockUserFeedPort)(nil).GetUserFeedIDs), ctx)
}
