// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/fetch_tag_cloud_port/port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/fetch_tag_cloud_port/port.go -destination=./alt-backend/app/mocks/mock_fetch_tag_cloud_port.go -package=mocks FetchTagCloudPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFetchTagCloudPort is a mock of FetchTagCloudPort interface.
type MockFetchTagCloudPort struct {
	ctrl     *gomock.Controller
	recorder *MockFetchTagCloudPortMockRecorder
	isgomock struct{}
}

// MockFetchTagCloudPortMockRecorder is the mock recorder for MockFetchTagCloudPort.
type MockFetchTagCloudPortMockRecorder struct {
	mock *MockFetchTagCloudPort
}

// NewMockFetchTagCloudPort creates a new mock instance.
func NewMockFetchTagCloudPort(ctrl *gomock.Controller) *MockFetchTagCloudPort {
	mock := &MockFetchTagCloudPort{ctrl: ctrl}
	mock.recorder = &MockFetchTagCloudPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFetchTagCloudPort) EXPECT() *MockFetchTagCloudPortMockRecorder {
	return m.recorder
}

// FetchTagCloud mocks base method.
func (m *MockFetchTagCloudPort) FetchTagCloud(ctx context.Context, limit int) ([]*domain.TagCloudItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTagCloud", ctx, limit)
	ret0, _ := ret[0].([]*domain.TagCloudItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTagCloud indicates an expected call of FetchTagCloud.
func (mr *MockFetchTagCloudPortMockRecorder) FetchTagCloud(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTagCloud", reflect.TypeOf((*MockFetchTagCloudPort)(nil).FetchTagCloud), ctx, limit)
}

// FetchTagCooccurrences mocks base method.
func (m *MockFetchTagCloudPort) FetchTagCooccurrences(ctx context.Context, tagNames []string) ([]*domain.TagCooccurrence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTagCooccurrences", ctx, tagNames)
	ret0, _ := ret[0].([]*domain.TagCooccurrence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTagCooccurrences indicates an expected call of FetchTagCooccurrences.
func (mr *MockFetchTagCloudPortMockRecorder) FetchTagCooccurrences(ctx, tagNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTagCooccurrences", reflect.TypeOf((*MockFetchTagCloudPort)(nil).FetchTagCooccurrences), ctx, tagNames)
}
