// Code generated by MockGen. DO NOT EDIT.
// Source: ./alt-backend/app/port/feed_search_port/search_by_title_port.go
//
// Generated by this command:
//
//	mockgen -source=./alt-backend/app/port/feed_search_port/search_by_title_port.go -destination=./alt-backend/app/mocks/mock_feed_search_port.go -package=mocks SearchByTitlePort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "alt/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSearchByTitlePort is a mock of SearchByTitlePort interface.
type MockSearchByTitlePort struct {
	ctrl     *gomock.Controller
	recorder *MockSearchByTitlePortMockRecorder
	isgomock struct{}
}

// MockSearchByTitlePortMockRecorder is the mock recorder for MockSearchByTitlePort.
type MockSearchByTitlePortMockRecorder struct {
	mock *MockSearchByTitlePort
}

// NewMockSearchByTitlePort creates a new mock instance.
func NewMockSearchByTitlePort(ctrl *gomock.Controller) *MockSearchByTitlePort {
	mock := &MockSearchByTitlePort{ctrl: ctrl}
	mock.recorder = &MockSearchByTitlePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchByTitlePort) EXPECT() *MockSearchByTitlePortMockRecorder {
	return m.recorder
}

// SearchFeedsByTitle mocks base method.
func (m *MockSearchByTitlePort) SearchFeedsByTitle(ctx context.Context, query, userID string) ([]*domain.FeedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchFeedsByTitle", ctx, query, userID)
	ret0, _ := ret[0].([]*domain.FeedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchFeedsByTitle indicates an expected call of SearchFeedsByTitle.
func (mr *MockSearchByTitlePortMockRecorder) SearchFeedsByTitle(ctx, query, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchFeedsByTitle", reflect.TypeOf((*MockSearchByTitlePort)(nil).SearchFeedsByTitle), ctx, query, userID)
}

// MockSearchFeedPort is a mock of SearchFeedPort interface.
type MockSearchFeedPort struct {
	ctrl     *gomock.Controller
	recorder *MockSearchFeedPortMockRecorder
	isgomock struct{}
}

// MockSearchFeedPortMockRecorder is the mock recorder for MockSearchFeedPort.
type MockSearchFeedPortMockRecorder struct {
	mock *MockSearchFeedPort
}

// NewMockSearchFeedPort creates a new mock instance.
func NewMockSearchFeedPort(ctrl *gomock.Controller) *MockSearchFeedPort {
	mock := &MockSearchFeedPort{ctrl: ctrl}
	mock.recorder = &MockSearchFeedPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchFeedPort) EXPECT() *MockSearchFeedPortMockRecorder {
	return m.recorder
}

// SearchFeeds mocks base method.
func (m *MockSearchFeedPort) SearchFeeds(ctx context.Context, query string) ([]domain.SearchArticleHit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchFeeds", ctx, query)
	ret0, _ := ret[0].([]domain.SearchArticleHit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchFeeds indicates an expected call of SearchFeeds.
func (mr *MockSearchFeedPortMockRecorder) SearchFeeds(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchFeeds", reflect.TypeOf((*MockSearchFeedPort)(nil).SearchFeeds), ctx, query)
}

// SearchFeedsWithPagination mocks base method.
func (m *MockSearchFeedPort) SearchFeedsWithPagination(ctx context.Context, query string, offset, limit int) ([]domain.SearchArticleHit, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchFeedsWithPagination", ctx, query, offset, limit)
	ret0, _ := ret[0].([]domain.SearchArticleHit)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchFeedsWithPagination indicates an expected call of SearchFeedsWithPagination.
func (mr *MockSearchFeedPortMockRecorder) SearchFeedsWithPagination(ctx, query, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchFeedsWithPagination", reflect.TypeOf((*MockSearchFeedPort)(nil).SearchFeedsWithPagination), ctx, query, offset, limit)
}
