// Code generated by protovis. DO NOT EDIT.
// Source: the (alt.api.v1.visibility) option on each alt.* service in proto/.
// Regenerate: cd proto/tools/protovis && go run . -desc <buf build output>

package server

// PublicServices are reachable from the browser through the generic
// /api/v2 proxy. Anything absent here is not proxyable, by default.
var PublicServices = map[string]struct{}{
	"alt.acolyte.v1.AcolyteService":                  {},
	"alt.articles.v2.ArticleService":                 {},
	"alt.augur.v2.AugurService":                      {},
	"alt.feeds.v2.FeedService":                       {},
	"alt.knowledge_home.v1.KnowledgeHomeService":     {},
	"alt.knowledge_trail.v1.KnowledgeTrailService":   {},
	"alt.morning_letter.v2.MorningLetterReadService": {},
	"alt.morning_letter.v2.MorningLetterService":     {},
	"alt.recap.v2.JobStatusService":                  {},
	"alt.recap.v2.RecapService":                      {},
	"alt.rss.v2.RSSService":                          {},
	"alt.search.v2.GlobalSearchService":              {},
	"alt.search.v2.SearchService":                    {},
	"alt.tts.v1.TTSService":                          {},
}

// AdminServices are forwardable only through dedicated gated routes that
// apply their own authorization. They are never proxyable generically.
var AdminServices = map[string]struct{}{
	"alt.admin_monitor.v1.AdminMonitorService":        {},
	"alt.knowledge_home.v1.KnowledgeHomeAdminService": {},
}
