package infrastructure

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"pki-agent/internal/domain"
)

// StepCACLI drives step-cli as a subprocess to mint an OTT and request a
// certificate. The Go agent owns the lifecycle state machine, retries,
// atomic writes and metrics; step-cli owns only the crypto + CA protocol.
//
// This keeps pki-agent isolated from changes in the CA protocol while still
// letting us replace the brittle compose-embedded shell with a typed,
// tested, observable binary.
type StepCACLI struct {
	CAURL            string
	RootFile         string
	Provisioner      string
	PasswordFile     string
	StepBinary       string // defaults to "step"
	TokenExtraArgs   []string
	CertExtraArgs    []string
	TempDir          string // override for tests; defaults to os.TempDir()
}

// Issue mints an OTT for `subject`, asks the CA to sign a fresh CSR, and
// returns the PEM bytes. A new key pair is generated by step-cli on every
// call (no reuse; addresses security audit F-005).
func (s *StepCACLI) Issue(ctx context.Context, subject string, sans []string) (certPEM, keyPEM []byte, err error) {
	step := s.StepBinary
	if step == "" {
		step = "step"
	}

	// 1. mint OTT.
	tokenArgs := []string{"ca", "token", subject,
		"--ca-url", s.CAURL,
		"--root", s.RootFile,
		"--provisioner", s.Provisioner,
		"--password-file", s.PasswordFile,
		"--force",
	}
	for _, san := range sans {
		tokenArgs = append(tokenArgs, "--san", san)
	}
	tokenArgs = append(tokenArgs, s.TokenExtraArgs...)
	var tokOut, tokErr bytes.Buffer
	cmd := exec.CommandContext(ctx, step, tokenArgs...)
	cmd.Stdout = &tokOut
	cmd.Stderr = &tokErr
	if err := cmd.Run(); err != nil {
		return nil, nil, fmt.Errorf("%w: token: %v: %s", domain.ErrTokenSign, err, tokErr.String())
	}
	ott := bytes.TrimSpace(tokOut.Bytes())
	if len(ott) == 0 {
		return nil, nil, fmt.Errorf("%w: empty token", domain.ErrTokenSign)
	}

	// 2. request cert to tmpfiles, then read.
	tempDir := s.TempDir
	if tempDir == "" {
		tempDir, err = os.MkdirTemp("", "pkiagent-issue-")
		if err != nil {
			return nil, nil, err
		}
		defer os.RemoveAll(tempDir)
	}
	certTmp := filepath.Join(tempDir, "svc-cert.pem")
	keyTmp := filepath.Join(tempDir, "svc-key.pem")

	certArgs := []string{"ca", "certificate", subject, certTmp, keyTmp,
		"--ca-url", s.CAURL,
		"--root", s.RootFile,
		"--token", string(ott),
		"--force",
	}
	certArgs = append(certArgs, s.CertExtraArgs...)
	var certErr bytes.Buffer
	cmd = exec.CommandContext(ctx, step, certArgs...)
	cmd.Stderr = &certErr
	if err := cmd.Run(); err != nil {
		return nil, nil, fmt.Errorf("%w: certificate: %v: %s", domain.ErrCARejected, err, certErr.String())
	}

	certPEM, err = os.ReadFile(certTmp)
	if err != nil {
		return nil, nil, fmt.Errorf("read issued cert: %w", err)
	}
	keyPEM, err = os.ReadFile(keyTmp)
	if err != nil {
		return nil, nil, fmt.Errorf("read issued key: %w", err)
	}
	return certPEM, keyPEM, nil
}
