package main

import (
	"strings"
	"testing"
)

func TestRender(t *testing.T) {
	list := Allowlist{
		Public: []string{"alt.alpha.v1.AlphaService", "alt.zulu.v2.ZuluService"},
		Admin:  []string{"alt.admin.v1.AdminService"},
	}

	tests := []struct {
		name     string
		render   func(Allowlist) ([]byte, error)
		contains []string
		absent   []string
	}{
		{
			name:   "go artifact carries the generated header, both maps and every name",
			render: RenderGo,
			contains: []string{
				"// Code generated by protovis. DO NOT EDIT.",
				"package server",
				"var PublicServices = map[string]struct{}{",
				`"alt.alpha.v1.AlphaService": {},`,
				`"alt.zulu.v2.ZuluService":   {},`,
				"var AdminServices = map[string]struct{}{",
				`"alt.admin.v1.AdminService": {},`,
			},
		},
		{
			name:   "ts artifact exposes public services only, as a const tuple",
			render: RenderTS,
			contains: []string{
				"// Code generated by protovis. DO NOT EDIT.",
				"export const PUBLIC_SERVICES = [",
				"\t\"alt.alpha.v1.AlphaService\",",
				"\t\"alt.zulu.v2.ZuluService\",",
				"] as const;",
			},
			absent: []string{"alt.admin.v1.AdminService"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := tt.render(list)
			if err != nil {
				t.Fatalf("render error = %v", err)
			}
			for _, want := range tt.contains {
				if !strings.Contains(string(got), want) {
					t.Errorf("output missing %q\n---\n%s", want, got)
				}
			}
			for _, unwanted := range tt.absent {
				if strings.Contains(string(got), unwanted) {
					t.Errorf("output unexpectedly contains %q\n---\n%s", unwanted, got)
				}
			}
		})
	}
}

func TestRenderIsDeterministic(t *testing.T) {
	list := Allowlist{
		Public: []string{"alt.alpha.v1.AlphaService", "alt.zulu.v2.ZuluService"},
		Admin:  []string{"alt.admin.v1.AdminService"},
	}

	renders := map[string]func(Allowlist) ([]byte, error){
		"go": RenderGo,
		"ts": RenderTS,
	}
	for name, render := range renders {
		t.Run(name, func(t *testing.T) {
			first, err := render(list)
			if err != nil {
				t.Fatalf("render error = %v", err)
			}
			for range 5 {
				again, err := render(list)
				if err != nil {
					t.Fatalf("render error = %v", err)
				}
				if string(again) != string(first) {
					t.Fatalf("render is not deterministic:\n%s\n---\n%s", first, again)
				}
			}
		})
	}
}
