FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY ./app/go.mod ./app/go.sum ./
RUN go mod download

COPY ./app .

RUN CGO_ENABLED=0 GOOS=linux go build -o /usr/local/bin/app ./main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /usr/local/bin/app /usr/local/bin/app

CMD ["/usr/local/bin/app"]

EXPOSE 9300