FROM golang:1.24.5-alpine AS builder
RUN apk add --no-cache ca-certificates git
RUN CGO_ENABLED=0 GO111MODULE=on \
  go install -tags "postgres" github.com/golang-migrate/migrate/v4/cmd/migrate@latest

FROM alpine:latest
RUN apk add --no-cache coreutils ca-certificates

# ← ここを修正
COPY --from=builder /go/bin/migrate /usr/local/bin/migrate

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

WORKDIR /app
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
