//go:build contract

// Package contract: mq-hub provider verification for async message pacts.
//
// search-indexer-mq-hub.json (generated by search-indexer's message_consumer_test.go)
// declares the envelope shape search-indexer expects on the Redis Streams
// `alt:events:articles` and `alt:events:index` topics. This test verifies that
// mq-hub's actual event builder (domain.NewEvent + eventToWireFormat) produces
// a payload that satisfies every interaction.
//
// gap-fill: before this test existed, search-indexer's message pact
// was orphaned — generated but never verified against real mq-hub output.

package contract

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/pact-foundation/pact-go/v2/message"
	"github.com/pact-foundation/pact-go/v2/models"
	"github.com/pact-foundation/pact-go/v2/provider"
	"github.com/stretchr/testify/require"

	"mq-hub/domain"
)

const searchIndexerProviderPact = "search-indexer-mq-hub.json"

func articleCreatedFatEvent() *domain.Event {
	payload := ArticleCreatedPayload{
		ArticleID:   "art-001",
		UserID:      "user-001",
		FeedID:      "feed-001",
		Title:       "Test Article",
		URL:         "https://example.com/article",
		Content:     "Full article content for direct indexing.",
		Tags:        []string{"technology"},
		PublishedAt: "2026-03-26T00:00:00Z",
	}
	payloadJSON, _ := json.Marshal(payload)
	event, _ := domain.NewEvent(
		domain.EventTypeArticleCreated,
		"alt-backend",
		payloadJSON,
		map[string]string{"trace_id": "trace-001"},
	)
	return event
}

func indexArticleEvent() *domain.Event {
	payload := map[string]interface{}{
		"article_id": "art-003",
		"user_id":    "user-001",
		"feed_id":    "feed-001",
	}
	payloadJSON, _ := json.Marshal(payload)
	event, _ := domain.NewEvent(
		domain.EventTypeIndexArticle,
		"alt-backend",
		payloadJSON,
		map[string]string{"trace_id": "trace-003"},
	)
	return event
}

// TestVerifySearchIndexerMqHubMessagePact replays search-indexer's consumer
// pact against a live mq-hub message generator. For each interaction description
// the handler produces the mq-hub wire-format event, and the Pact verifier
// checks that the structure matches the expected payload in the pact file.
func TestVerifySearchIndexerMqHubMessagePact(t *testing.T) {
	pactFile := filepath.Join(pactDir, searchIndexerProviderPact)
	if _, err := os.Stat(pactFile); os.IsNotExist(err) {
		t.Skipf("pact file missing: %s (run search-indexer consumer tests first)", pactFile)
	}

	verifier := provider.NewVerifier()
	err := verifier.VerifyProvider(t, provider.VerifyRequest{
		Provider:  "mq-hub",
		PactFiles: []string{pactFile},
		MessageHandlers: message.Handlers{
			"an ArticleCreated event on alt:events:articles": func(_ []models.ProviderState) (message.Body, message.Metadata, error) {
				return eventToWireFormat(buildArticleCreatedEvent()), message.Metadata{
					"contentType": "application/json",
				}, nil
			},
			"an ArticleCreated fat event with content on alt:events:articles": func(_ []models.ProviderState) (message.Body, message.Metadata, error) {
				return eventToWireFormat(articleCreatedFatEvent()), message.Metadata{
					"contentType": "application/json",
				}, nil
			},
			"an IndexArticle event on alt:events:index": func(_ []models.ProviderState) (message.Body, message.Metadata, error) {
				return eventToWireFormat(indexArticleEvent()), message.Metadata{
					"contentType": "application/json",
				}, nil
			},
		},
		StateHandlers: models.StateHandlers{
			"the articles stream exists": func(bool, models.ProviderState) (models.ProviderStateResponse, error) {
				return nil, nil
			},
			"the index stream exists": func(bool, models.ProviderState) (models.ProviderStateResponse, error) {
				return nil, nil
			},
		},
	})
	require.NoError(t, err)
}
