package render

import (
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"testing"

	"github.com/alt-project/adrdag/internal/adr"
	"github.com/alt-project/adrdag/internal/graph"
)

var update = flag.Bool("update", false, "regenerate golden files")

// loadFixture loads a checked-in fixture ADR dir from the module root.
func loadFixture(t *testing.T, name string) map[string]adr.ADR {
	t.Helper()
	adrs, err := adr.LoadDir(filepath.Join("..", "..", "testdata", "fixtures", name))
	if err != nil {
		t.Fatalf("load fixture %s: %v", name, err)
	}
	return adrs
}

func golden(t *testing.T, name string, got []byte) {
	t.Helper()
	path := filepath.Join("testdata", "golden", name)
	if *update {
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden %s (run with -update to create): %v", name, err)
	}
	if string(got) != string(want) {
		t.Errorf("output does not match golden %s\n--- got ---\n%s\n--- want ---\n%s", name, got, want)
	}
}

func TestGoldenMermaid(t *testing.T) {
	// mermaid golden files are generated by the CANONICAL python tool:
	//   python3 scripts/adr_graph.py --adr-dir adrdag/testdata/fixtures/<name> graph --out <golden>
	// so this test pins byte-for-byte parity with adr_graph.py.
	for _, name := range []string{"ok", "fan-in"} {
		t.Run(name, func(t *testing.T) {
			adrs := loadFixture(t, name)
			g := adr.SupersedesGraph(adrs)
			// python's cmd_graph writes render_mermaid(...) + "\n"
			golden(t, "mermaid-"+name+".golden", []byte(Mermaid(g, adrs)+"\n"))
		})
	}
}

func TestGoldenDOT(t *testing.T) {
	for _, name := range []string{"ok", "fan-in"} {
		t.Run(name, func(t *testing.T) {
			adrs := loadFixture(t, name)
			g := adr.SupersedesGraph(adrs)
			golden(t, "dot-"+name+".golden", []byte(DOT(g)+"\n"))
		})
	}
}

func TestGoldenJSON(t *testing.T) {
	for _, name := range []string{"ok", "fan-in"} {
		t.Run(name, func(t *testing.T) {
			adrs := loadFixture(t, name)
			g := adr.SupersedesGraph(adrs)
			rev := graph.BuildReverse(g)
			out, err := JSONGraph(adrs, g, rev)
			if err != nil {
				t.Fatal(err)
			}
			if !json.Valid(out) {
				t.Fatalf("JSONGraph produced invalid JSON: %s", out)
			}
			golden(t, "json-"+name+".golden", append(out, '\n'))
		})
	}
}

func TestJSONGraphUsesLinksKey(t *testing.T) {
	adrs := loadFixture(t, "ok")
	g := adr.SupersedesGraph(adrs)
	out, err := JSONGraph(adrs, g, graph.BuildReverse(g))
	if err != nil {
		t.Fatal(err)
	}
	var doc map[string]json.RawMessage
	if err := json.Unmarshal(out, &doc); err != nil {
		t.Fatal(err)
	}
	if _, ok := doc["links"]; !ok {
		t.Error(`JSONGraph output missing "links" key (node-link convention)`)
	}
	if _, ok := doc["edges"]; ok {
		t.Error(`JSONGraph output must not use "edges" key — node-link default is "links"`)
	}
}
