#!/bin/bash
#
# Alt Platform Backup Metrics Exporter
# Generates Prometheus-compatible metrics for backup monitoring
#
# Usage:
#   ./backup-metrics.sh
#
# Output:
#   Writes metrics to /backups/metrics/backup_metrics.prom
#   Can be scraped by Prometheus node_exporter textfile collector
#
# Environment Variables:
#   RESTIC_REPOSITORY     Path to Restic repository
#   RESTIC_PASSWORD_FILE  Path to password file
#   METRICS_DIR           Output directory for metrics (default: /backups/metrics)
#

set -euo pipefail

# Configuration
RESTIC_REPOSITORY="${RESTIC_REPOSITORY:-/backups/restic-repo}"
RESTIC_PASSWORD_FILE="${RESTIC_PASSWORD_FILE:-/run/secrets/restic_password}"
METRICS_DIR="${METRICS_DIR:-/backups/metrics}"
POSTGRES_BACKUP_DIR="${POSTGRES_BACKUP_DIR:-/backups/postgres}"

METRICS_FILE="${METRICS_DIR}/backup_metrics.prom"
TEMP_FILE="${METRICS_FILE}.tmp"

# Create metrics directory
mkdir -p "$METRICS_DIR"

# Start fresh metrics file
cat > "$TEMP_FILE" << 'EOF'
# Alt Platform Backup Metrics
# Generated by backup-metrics.sh

EOF

# Helper to add metric
add_metric() {
    local name="$1"
    local type="$2"
    local help="$3"
    local value="$4"
    local labels="${5:-}"

    echo "# HELP ${name} ${help}" >> "$TEMP_FILE"
    echo "# TYPE ${name} ${type}" >> "$TEMP_FILE"

    if [[ -n "$labels" ]]; then
        echo "${name}{${labels}} ${value}" >> "$TEMP_FILE"
    else
        echo "${name} ${value}" >> "$TEMP_FILE"
    fi
    echo "" >> "$TEMP_FILE"
}

# Check if Restic repository exists
if [[ ! -d "$RESTIC_REPOSITORY" ]]; then
    add_metric "backup_repository_initialized" "gauge" "Whether the backup repository is initialized (0=no, 1=yes)" "0"
    mv "$TEMP_FILE" "$METRICS_FILE"
    exit 0
fi

add_metric "backup_repository_initialized" "gauge" "Whether the backup repository is initialized (0=no, 1=yes)" "1"

# Get snapshot information
SNAPSHOTS_JSON=$(restic -r "$RESTIC_REPOSITORY" snapshots --json 2>/dev/null || echo "[]")
SNAPSHOT_COUNT=$(echo "$SNAPSHOTS_JSON" | jq 'length')

add_metric "backup_restic_snapshot_count" "gauge" "Total number of Restic snapshots" "$SNAPSHOT_COUNT"

# Get latest snapshot timestamp
if [[ "$SNAPSHOT_COUNT" -gt 0 ]]; then
    LATEST_SNAPSHOT=$(echo "$SNAPSHOTS_JSON" | jq -r 'sort_by(.time) | last | .time')
    LATEST_TIMESTAMP=$(date -d "$LATEST_SNAPSHOT" +%s 2>/dev/null || echo 0)

    add_metric "backup_last_success_timestamp" "gauge" "Unix timestamp of last successful Restic backup" "$LATEST_TIMESTAMP" 'type="restic"'

    # Calculate age of latest backup in hours
    CURRENT_TIME=$(date +%s)
    BACKUP_AGE_HOURS=$(( (CURRENT_TIME - LATEST_TIMESTAMP) / 3600 ))
    add_metric "backup_age_hours" "gauge" "Age of latest backup in hours" "$BACKUP_AGE_HOURS" 'type="restic"'
else
    add_metric "backup_last_success_timestamp" "gauge" "Unix timestamp of last successful Restic backup" "0" 'type="restic"'
    add_metric "backup_age_hours" "gauge" "Age of latest backup in hours" "-1" 'type="restic"'
fi

# Get repository statistics
REPO_STATS=$(restic -r "$RESTIC_REPOSITORY" stats --json 2>/dev/null || echo '{"total_size":0}')
TOTAL_SIZE=$(echo "$REPO_STATS" | jq -r '.total_size // 0')
FILE_COUNT=$(echo "$REPO_STATS" | jq -r '.total_file_count // 0')

add_metric "backup_total_size_bytes" "gauge" "Total size of backup repository in bytes" "$TOTAL_SIZE"
add_metric "backup_file_count" "gauge" "Total number of files in backup repository" "$FILE_COUNT"

# PostgreSQL backup metrics
echo "# PostgreSQL backup metrics" >> "$TEMP_FILE"

DATABASES=("alt-db" "kratos-db" "recap-db" "rag-db")
for db in "${DATABASES[@]}"; do
    # Find latest backup for this database
    LATEST_PG_BACKUP=$(find "$POSTGRES_BACKUP_DIR" -name "${db}-*.dump" -type f 2>/dev/null | sort -r | head -1 || echo "")

    if [[ -n "$LATEST_PG_BACKUP" && -f "$LATEST_PG_BACKUP" ]]; then
        PG_BACKUP_TIME=$(stat -c %Y "$LATEST_PG_BACKUP")
        PG_BACKUP_SIZE=$(stat -c %s "$LATEST_PG_BACKUP")

        add_metric "backup_postgres_last_success_timestamp" "gauge" "Unix timestamp of last successful PostgreSQL backup" "$PG_BACKUP_TIME" "database=\"${db}\""
        add_metric "backup_postgres_size_bytes" "gauge" "Size of latest PostgreSQL backup in bytes" "$PG_BACKUP_SIZE" "database=\"${db}\""
    else
        add_metric "backup_postgres_last_success_timestamp" "gauge" "Unix timestamp of last successful PostgreSQL backup" "0" "database=\"${db}\""
        add_metric "backup_postgres_size_bytes" "gauge" "Size of latest PostgreSQL backup in bytes" "0" "database=\"${db}\""
    fi
done

# Disk space metrics for backup directory
BACKUP_DISK_TOTAL=$(df -B1 /backups | tail -1 | awk '{print $2}')
BACKUP_DISK_USED=$(df -B1 /backups | tail -1 | awk '{print $3}')
BACKUP_DISK_AVAIL=$(df -B1 /backups | tail -1 | awk '{print $4}')
BACKUP_DISK_PERCENT=$(df /backups | tail -1 | awk '{print $5}' | tr -d '%')

add_metric "backup_disk_total_bytes" "gauge" "Total disk space for backups in bytes" "$BACKUP_DISK_TOTAL"
add_metric "backup_disk_used_bytes" "gauge" "Used disk space for backups in bytes" "$BACKUP_DISK_USED"
add_metric "backup_disk_available_bytes" "gauge" "Available disk space for backups in bytes" "$BACKUP_DISK_AVAIL"
add_metric "backup_disk_usage_percent" "gauge" "Disk usage percentage for backups" "$BACKUP_DISK_PERCENT"

# Offsite sync status (if remote repository configured)
REMOTE_REPO="${REMOTE_REPO:-}"
if [[ -n "$REMOTE_REPO" ]]; then
    REMOTE_SNAPSHOTS=$(restic -r "$REMOTE_REPO" snapshots --json 2>/dev/null | jq 'length' || echo "-1")

    if [[ "$REMOTE_SNAPSHOTS" != "-1" ]]; then
        add_metric "backup_offsite_snapshot_count" "gauge" "Number of snapshots in offsite repository" "$REMOTE_SNAPSHOTS"
        add_metric "backup_offsite_reachable" "gauge" "Whether offsite repository is reachable (0=no, 1=yes)" "1"

        # Get latest offsite snapshot
        REMOTE_LATEST=$(restic -r "$REMOTE_REPO" snapshots --json 2>/dev/null | jq -r 'sort_by(.time) | last | .time' || echo "")
        if [[ -n "$REMOTE_LATEST" && "$REMOTE_LATEST" != "null" ]]; then
            REMOTE_TIMESTAMP=$(date -d "$REMOTE_LATEST" +%s 2>/dev/null || echo 0)
            add_metric "backup_offsite_last_success_timestamp" "gauge" "Unix timestamp of last offsite backup" "$REMOTE_TIMESTAMP"
        fi
    else
        add_metric "backup_offsite_reachable" "gauge" "Whether offsite repository is reachable (0=no, 1=yes)" "0"
    fi
fi

# Restore verification metrics (from restore-verify.sh output)
VERIFY_METRICS_FILE="${METRICS_DIR}/backup_restore_verify.prom"
if [[ -f "$VERIFY_METRICS_FILE" ]]; then
    echo "# Restore verification metrics (from restore-verify.sh)" >> "$TEMP_FILE"
    cat "$VERIFY_METRICS_FILE" >> "$TEMP_FILE"
    echo "" >> "$TEMP_FILE"
fi

# Add generation timestamp
add_metric "backup_metrics_generated_timestamp" "gauge" "When these metrics were generated" "$(date +%s)"

# Atomically move temp file to final location
mv "$TEMP_FILE" "$METRICS_FILE"

echo "Metrics written to $METRICS_FILE"
