#!/usr/bin/env python3
"""Regenerate service-registry artifacts from services.yaml.

Single source of truth: services.yaml at the repo root.
Derived files:
  - .github/workflows/docker-build.yaml  (SERVICES=(...) block)
  - c2quay.yml                           (environments.production.services)
  - .github/generated/alt-deploy-service-paths.js
      (reference snippet for alt-deploy's release-deploy.yaml SERVICE_PATHS)

Usage:
  scripts/regen-service-registry.py --check   # exit 1 if drift detected
  scripts/regen-service-registry.py --write   # rewrite derived files

Uses only the standard library so CI can invoke it without any env setup.
"""
from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

# Stdlib YAML parser via re — we only need a subset. But PyYAML is
# essentially universally installed on GitHub-hosted runners. Prefer it
# when available so we don't reimplement YAML parsing.
try:
    import yaml
except ImportError:  # pragma: no cover
    sys.stderr.write(
        "PyYAML is required. Install via `pip install pyyaml` or use an "
        "image that preinstalls it.\n"
    )
    sys.exit(2)

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "services.yaml"
DOCKER_BUILD = ROOT / ".github" / "workflows" / "docker-build.yaml"
C2QUAY = ROOT / "c2quay.yml"
ALT_DEPLOY_SNIPPET = ROOT / ".github" / "generated" / "alt-deploy-service-paths.js"

# Sentinel markers that bracket the generated regions in the hand-edited
# files. Anything inside the sentinels is rewritten in place; anything
# outside is preserved verbatim.
SVC_BEGIN = "# <<<SERVICES-REGISTRY-BEGIN>>>"
SVC_END = "# <<<SERVICES-REGISTRY-END>>>"


def load_registry() -> dict:
    with REGISTRY.open() as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict) or "services" not in data:
        raise SystemExit(f"{REGISTRY}: missing top-level `services` list")
    return data


def pacticipants(registry: dict) -> list[dict]:
    """Services that go through the Pact gate (local + external)."""
    return [
        s for s in registry["services"]
        if s.get("kind") in ("pacticipant", "external")
    ]


def local_pacticipants(registry: dict) -> list[dict]:
    """Pacticipants built + deployed locally (excludes `external`)."""
    return [s for s in registry["services"] if s.get("kind") == "pacticipant"]


def runtime_services(registry: dict) -> list[dict]:
    """Non-pacticipant images built via docker-build but not gated by Pact."""
    return [s for s in registry["services"] if s.get("kind") == "runtime"]


def local_build_services(registry: dict) -> list[dict]:
    """Services that have a Dockerfile in this repo (pacticipant + runtime)."""
    return [
        s for s in registry["services"]
        if s.get("kind") in ("pacticipant", "runtime")
    ]


# ---------------------------------------------------------------------------
# Renderers
# ---------------------------------------------------------------------------

def render_docker_build_block(registry: dict) -> str:
    """Bash array body for docker-build.yaml SERVICES=(...)."""
    lines = ["          SERVICES=("]
    lines.append("            # --- 13 Pact pacticipants (mirrors c2quay.yml) ---")
    for s in local_pacticipants(registry):
        lines.append(f'            "{s["name"]}"')
    lines.append("            # --- Additional runtime services used by compose ---")
    for s in runtime_services(registry):
        lines.append(f'            "{s["name"]}"')
    lines.append("          )")
    return "\n".join(lines) + "\n"


def render_c2quay_block(registry: dict) -> str:
    """YAML fragment for c2quay.yml environments.production.services."""
    # Align pacticipant colons for readability (matches current style).
    names = [s["name"] for s in pacticipants(registry)]
    width = max(len(n) for n in names)
    out = []
    for s in pacticipants(registry):
        name = s["name"]
        pad = " " * (width - len(name))
        out.append(f"      {name}:{pad} {{ pacticipant: {name} }}")
    return "\n".join(out) + "\n"


def render_alt_deploy_service_paths(registry: dict) -> str:
    """JavaScript object literal for alt-deploy release-deploy.yaml.

    alt-deploy lives in a separate repo and is regenerated out-of-band;
    we commit the snippet here so drift is visible in Alt's PR review.
    """
    out = ["// AUTOGENERATED by scripts/regen-service-registry.py."]
    out.append("// Paste the object body into alt-deploy's")
    out.append("// .github/workflows/release-deploy.yaml SERVICE_PATHS.")
    out.append("//")
    out.append("// Regenerate with `scripts/regen-service-registry.py --write`.")
    out.append("const SERVICE_PATHS = {")
    for s in local_pacticipants(registry):
        name = s["name"]
        compose_files = s.get("compose_files", [])
        lines = [
            f"  '{name}': [",
            f"    '{name}/',",
            f"    'e2e/hurl/{name}/',",
            f"    'e2e/fixtures/{name}/',",
        ]
        for cf in compose_files:
            lines.append(f"    'compose/{cf}',")
        lines.append("  ],")
        out.extend(lines)
    out.append("};")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Patchers (for in-place files with sentinel markers)
# ---------------------------------------------------------------------------

def patch_between_sentinels(
    path: Path,
    new_body: str,
    begin_marker: str,
    end_marker: str,
) -> str:
    """Replace the text between begin_marker and end_marker with new_body.

    Preserves the leading whitespace of each sentinel line so the host
    file's indentation (`          #` in docker-build, `      #` in
    c2quay) survives. new_body is responsible for its own indentation.
    """
    text = path.read_text()
    pat = re.compile(
        r"(^[ \t]*)" + re.escape(begin_marker) + r".*?^([ \t]*)" + re.escape(end_marker),
        re.DOTALL | re.MULTILINE,
    )
    m = pat.search(text)
    if not m:
        raise SystemExit(
            f"{path}: sentinel markers not found.\n"
            f"  Expected '{begin_marker}' and '{end_marker}' on their own lines.\n"
            f"  Initialize the block manually, then rerun this script."
        )
    begin_indent, end_indent = m.group(1), m.group(2)
    replacement = f"{begin_indent}{begin_marker}\n{new_body}{end_indent}{end_marker}"
    return pat.sub(replacement, text, count=1)


def patch_docker_build(registry: dict) -> tuple[Path, str]:
    new_body = render_docker_build_block(registry)
    text = patch_between_sentinels(DOCKER_BUILD, new_body, SVC_BEGIN, SVC_END)
    return DOCKER_BUILD, text


def patch_c2quay(registry: dict) -> tuple[Path, str]:
    new_body = render_c2quay_block(registry)
    text = patch_between_sentinels(C2QUAY, new_body, SVC_BEGIN, SVC_END)
    return C2QUAY, text


def write_alt_deploy_snippet(registry: dict) -> tuple[Path, str]:
    ALT_DEPLOY_SNIPPET.parent.mkdir(parents=True, exist_ok=True)
    return ALT_DEPLOY_SNIPPET, render_alt_deploy_service_paths(registry)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def diff(path: Path, new_text: str) -> str:
    old = path.read_text() if path.exists() else ""
    if old == new_text:
        return ""
    return "".join(
        difflib.unified_diff(
            old.splitlines(keepends=True),
            new_text.splitlines(keepends=True),
            fromfile=f"a/{path.relative_to(ROOT)}",
            tofile=f"b/{path.relative_to(ROOT)}",
        )
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true",
                      help="exit 1 if generated files are out of date")
    mode.add_argument("--write", action="store_true",
                      help="rewrite generated files in place")
    args = parser.parse_args()

    registry = load_registry()

    outputs: list[tuple[Path, str]] = [
        patch_docker_build(registry),
        patch_c2quay(registry),
        write_alt_deploy_snippet(registry),
    ]

    if args.write:
        for path, new_text in outputs:
            path.write_text(new_text)
            print(f"wrote {path.relative_to(ROOT)}")
        return 0

    drift = False
    for path, new_text in outputs:
        d = diff(path, new_text)
        if d:
            drift = True
            print(d, end="")
            print(f"::error file={path.relative_to(ROOT)}::drifts from services.yaml; "
                  f"run scripts/regen-service-registry.py --write")
    if drift:
        return 1
    print("services registry is in sync.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
