#!/bin/bash
# run-feed-read-load-test.sh - Orchestrate feed read load test (3000 VU)
#
# Phases:
#   0. Generate Docker Compose overlay (DoS/resource overrides)
#   1. Restart alt-backend with overrides + health check
#   2. Setup test data (subscriptions + articles for test users)
#   3. Run K6 load test
#   4. Collect service logs & metrics
#   5. Teardown test data
#   6. Restore default config
#
# Usage:
#   ./alt-perf/scripts/run-feed-read-load-test.sh            # Full 3000 VU test
#   VU_COUNT=1 ./alt-perf/scripts/run-feed-read-load-test.sh # Smoke test

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$PROJECT_ROOT"

VU_COUNT="${VU_COUNT:-3000}"
VALIDATE_RATE_LIMIT="${VALIDATE_RATE_LIMIT:-10000}"
AUTH_HUB_REPLICAS="${AUTH_HUB_REPLICAS:-3}"
FEED_FETCH_CONCURRENCY="${FEED_FETCH_CONCURRENCY:-500}"
CB_MAX_CONCURRENT="${CB_MAX_CONCURRENT:-500}"
CB_FAILURE_THRESHOLD="${CB_FAILURE_THRESHOLD:-1000}"
CB_RESET_TIMEOUT="${CB_RESET_TIMEOUT:-5s}"
BACKEND_NOFILE="${BACKEND_NOFILE:-65536}"
DB_NOFILE="${DB_NOFILE:-65536}"
PGBOUNCER_NOFILE="${PGBOUNCER_NOFILE:-65536}"
K6_NOFILE="${K6_NOFILE:-65536}"
BACKEND_MEMORY_LIMIT="${BACKEND_MEMORY_LIMIT:-10G}"
GOMEMLIMIT="${GOMEMLIMIT:-10GiB}"
GOGC="${GOGC:-100}"
PPROF_ENABLED="${PPROF_ENABLED:-true}"
DB_USER="${POSTGRES_USER:-alt_db_user}"
DB_NAME="${POSTGRES_DB:-alt}"
export VALIDATE_RATE_LIMIT
export AUTH_HUB_REPLICAS
export FEED_FETCH_CONCURRENCY
export CB_MAX_CONCURRENT
export CB_FAILURE_THRESHOLD
export CB_RESET_TIMEOUT
export BACKEND_NOFILE
export DB_NOFILE
export PGBOUNCER_NOFILE
export K6_NOFILE
export BACKEND_MEMORY_LIMIT
export GOMEMLIMIT
export GOGC
export PPROF_ENABLED
K6_SCENARIO="/scripts/scenarios/feed-read-3000vu.js"
GENERATED_OVERLAY="compose/feed-read-test-generated.yaml"
RESTORE_ON_EXIT=0

cleanup() {
  set +e

  if [ "$RESTORE_ON_EXIT" -eq 1 ]; then
    echo ""
    echo "Cleanup: Restoring default config..."
    docker compose -f compose/compose.yaml -p alt up -d --force-recreate db pgbouncer auth-hub alt-backend >/dev/null 2>&1 || true
  fi

  rm -f "$GENERATED_OVERLAY"
}

trap cleanup EXIT INT TERM

echo "========================================"
echo "  Feed Read Load Test"
echo "  VUs: $VU_COUNT"
echo "  Distribution: 80/20 (popular/normal feeds)"
echo "  auth-hub validate rate limit: $VALIDATE_RATE_LIMIT req/s"
echo "  auth-hub replicas: $AUTH_HUB_REPLICAS"
echo "  FEED_FETCH_CONCURRENCY: $FEED_FETCH_CONCURRENCY"
echo "  CB_MAX_CONCURRENT: $CB_MAX_CONCURRENT"
echo "  alt-backend memory limit: $BACKEND_MEMORY_LIMIT"
echo "  nofile: backend=$BACKEND_NOFILE db=$DB_NOFILE pgbouncer=$PGBOUNCER_NOFILE k6=$K6_NOFILE"
echo "  GOMEMLIMIT: $GOMEMLIMIT"
echo "  GOGC: $GOGC"
echo "  PPROF_ENABLED: $PPROF_ENABLED"
echo "  Scenario: $K6_SCENARIO"
echo "========================================"
echo ""

# --- Phase 0: Generate compose overlay ---
echo "Phase 0: Generating compose overlay..."

if [ "$VU_COUNT" -gt 100 ]; then
  cat > "$GENERATED_OVERLAY" <<'OVERLAY_EOF'
# Generated by run-feed-read-load-test.sh — DO NOT EDIT
services:
  alt-backend:
    environment:
      - DOS_PROTECTION_RATE_LIMIT=10000
      - DOS_PROTECTION_BURST_LIMIT=20000
      - DOS_PROTECTION_BLOCK_DURATION=10s
      - DB_HOST=pgbouncer
      - DB_PORT=6432
      - DB_MAX_CONNS=200
      - DB_MIN_CONNS=10
      - FEED_FETCH_CONCURRENCY=${FEED_FETCH_CONCURRENCY}
      - CB_MAX_CONCURRENT=${CB_MAX_CONCURRENT}
      - CB_FAILURE_THRESHOLD=${CB_FAILURE_THRESHOLD}
      - CB_RESET_TIMEOUT=${CB_RESET_TIMEOUT}
      - GOMEMLIMIT=${GOMEMLIMIT}
      - GOGC=${GOGC}
      - PPROF_ENABLED=${PPROF_ENABLED}
    ports:
      - "6060:6060"
    deploy:
      resources:
        limits:
          memory: ${BACKEND_MEMORY_LIMIT}
          cpus: '8.0'
    ulimits:
      nofile:
        soft: ${BACKEND_NOFILE}
        hard: ${BACKEND_NOFILE}

  db:
    command: >
      postgres
      -c max_connections=250
      -c shared_buffers=512MB
      -c work_mem=16MB
      -c effective_cache_size=1536MB
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c log_statement=none
      -c log_connections=off
      -c log_disconnections=off
    deploy:
      resources:
        limits:
          memory: 4G
    ulimits:
      nofile:
        soft: ${DB_NOFILE}
        hard: ${DB_NOFILE}

  pgbouncer:
    environment:
      - DEFAULT_POOL_SIZE=80
      - MAX_DB_CONNECTIONS=200
      - MAX_CLIENT_CONN=2000
      - QUERY_WAIT_TIMEOUT=120
    deploy:
      resources:
        limits:
          memory: 512M
    ulimits:
      nofile:
        soft: ${PGBOUNCER_NOFILE}
        hard: ${PGBOUNCER_NOFILE}

  auth-hub:
    environment:
      - VALIDATE_RATE_LIMIT=${VALIDATE_RATE_LIMIT}
    deploy:
      replicas: ${AUTH_HUB_REPLICAS}
      resources:
        limits:
          memory: 512M

  k6:
    environment:
      - K6_BASE_URL=http://alt-backend:9101
    deploy:
      resources:
        limits:
          memory: 16G
          cpus: '8'
    ulimits:
      nofile:
        soft: ${K6_NOFILE}
        hard: ${K6_NOFILE}
OVERLAY_EOF
  echo "  Generated overlay with high-VU overrides"
else
  # Smoke/small test: minimal overrides
  cat > "$GENERATED_OVERLAY" <<'OVERLAY_EOF'
# Generated by run-feed-read-load-test.sh — DO NOT EDIT
services:
  alt-backend:
    environment:
      - DOS_PROTECTION_RATE_LIMIT=10000
      - DOS_PROTECTION_BURST_LIMIT=20000
      - FEED_FETCH_CONCURRENCY=${FEED_FETCH_CONCURRENCY}
      - CB_MAX_CONCURRENT=${CB_MAX_CONCURRENT}
      - CB_FAILURE_THRESHOLD=${CB_FAILURE_THRESHOLD}
      - CB_RESET_TIMEOUT=${CB_RESET_TIMEOUT}
      - GOMEMLIMIT=${GOMEMLIMIT}
      - GOGC=${GOGC}
      - PPROF_ENABLED=${PPROF_ENABLED}
    ports:
      - "6060:6060"
    ulimits:
      nofile:
        soft: ${BACKEND_NOFILE}
        hard: ${BACKEND_NOFILE}

  k6:
    environment:
      - K6_BASE_URL=http://alt-backend:9101
    ulimits:
      nofile:
        soft: ${K6_NOFILE}
        hard: ${K6_NOFILE}
OVERLAY_EOF
  echo "  Generated overlay with minimal overrides"
fi

COMPOSE="docker compose -f compose/compose.yaml -f ${GENERATED_OVERLAY} -p alt"

# --- Phase 1: Restart services with overrides ---
echo ""
echo "Phase 1: Restarting services with overrides..."
RESTORE_ON_EXIT=1
if [ "$VU_COUNT" -gt 100 ]; then
  $COMPOSE up -d --force-recreate db pgbouncer auth-hub alt-backend
else
  $COMPOSE up -d --force-recreate alt-backend
fi

echo "Waiting for alt-backend health..."
for i in $(seq 1 60); do
  if curl -sf http://localhost:9000/v1/health > /dev/null 2>&1 && \
     curl -sf http://localhost:9101/health > /dev/null 2>&1; then
    echo "  alt-backend is healthy (REST 9000 + Connect-RPC 9101)"
    break
  fi
  if [ "$i" -eq 60 ]; then
    echo "  ERROR: alt-backend failed to start"
    $COMPOSE logs alt-backend --tail 20
    exit 1
  fi
  sleep 1
done

# --- Phase 2: Setup test data (80/20 distribution) ---
echo ""
echo "Phase 2: Setting up test data ($VU_COUNT users, 80/20 feed distribution)..."

# Find the real user who has articles (source for copying)
REAL_USER_ID=$($COMPOSE exec -T db psql -U "$DB_USER" -d "$DB_NAME" -t -A -c \
  "SELECT user_id FROM articles GROUP BY user_id ORDER BY count(*) DESC LIMIT 1;" 2>/dev/null || echo "")

if [ -z "$REAL_USER_ID" ]; then
  echo "  WARNING: No articles found in DB. Skipping article copy."
  REAL_USER_ID="00000000-0000-0000-0000-000000000000"
fi

echo "  Source user for articles: $REAL_USER_ID"

# 2a. Classify feed popularity using ntile(5) — top 20% = popular
#     Uses a regular table (not temp) so it persists across psql sessions
echo "  Classifying feed popularity (top 20% = popular, bottom 80% = normal)..."
$COMPOSE exec -T db psql -U "$DB_USER" -d "$DB_NAME" -c "
DROP TABLE IF EXISTS _loadtest_feed_popularity;
CREATE TABLE _loadtest_feed_popularity AS
SELECT
  fl.id AS feed_link_id,
  count(f.id) AS feed_count,
  CASE WHEN ntile(5) OVER (ORDER BY count(f.id) DESC) = 1
       THEN 'popular' ELSE 'normal' END AS tier
FROM feed_links fl
LEFT JOIN feeds f ON f.feed_link_id = fl.id
GROUP BY fl.id;
"

POP_COUNT=$($COMPOSE exec -T db psql -U "$DB_USER" -d "$DB_NAME" -t -A -c \
  "SELECT count(*) FROM _loadtest_feed_popularity WHERE tier = 'popular';")
NORM_COUNT=$($COMPOSE exec -T db psql -U "$DB_USER" -d "$DB_NAME" -t -A -c \
  "SELECT count(*) FROM _loadtest_feed_popularity WHERE tier = 'normal';")
echo "  Feed distribution: popular=$POP_COUNT, normal=$NORM_COUNT"

# 2b. Popular feeds: all users subscribe
echo "  Subscribing all $VU_COUNT users to $POP_COUNT popular feeds..."
$COMPOSE exec -T db psql -U "$DB_USER" -d "$DB_NAME" -c "
INSERT INTO user_feed_subscriptions (user_id, feed_link_id, created_at)
SELECT
  ('00000000-0000-4000-a000-' || lpad(u::text, 12, '0'))::uuid,
  fp.feed_link_id,
  NOW()
FROM generate_series(1, $VU_COUNT) u
CROSS JOIN _loadtest_feed_popularity fp
WHERE fp.tier = 'popular'
ON CONFLICT DO NOTHING;
"

# 2c. Normal feeds: each user subscribes to ~30% randomly
echo "  Subscribing each user to ~30% of $NORM_COUNT normal feeds..."
$COMPOSE exec -T db psql -U "$DB_USER" -d "$DB_NAME" -c "
INSERT INTO user_feed_subscriptions (user_id, feed_link_id, created_at)
SELECT
  ('00000000-0000-4000-a000-' || lpad(u::text, 12, '0'))::uuid,
  fp.feed_link_id,
  NOW()
FROM generate_series(1, $VU_COUNT) u
CROSS JOIN _loadtest_feed_popularity fp
WHERE fp.tier = 'normal'
  AND random() < 0.3
ON CONFLICT DO NOTHING;
"

SUB_COUNT=$($COMPOSE exec -T db psql -U "$DB_USER" -d "$DB_NAME" -t -A -c \
  "SELECT count(*) FROM user_feed_subscriptions WHERE user_id::text LIKE '00000000-0000-4000-a000-%';")
echo "  Subscriptions created: $SUB_COUNT"

# 2d. Copy articles from popular feeds (15 per user)
echo "  Copying popular feed articles ($VU_COUNT users × 15 articles)..."
$COMPOSE exec -T db psql -U "$DB_USER" -d "$DB_NAME" -c "
INSERT INTO articles (id, title, content, url, feed_id, user_id, created_at, published_at)
SELECT
  gen_random_uuid(), a.title, a.content, a.url, a.feed_id,
  ('00000000-0000-4000-a000-' || lpad(u::text, 12, '0'))::uuid,
  a.created_at, a.published_at
FROM generate_series(1, $VU_COUNT) u
CROSS JOIN LATERAL (
  SELECT a.* FROM articles a
  JOIN feeds f ON a.feed_id = f.id
  JOIN _loadtest_feed_popularity fp ON f.feed_link_id = fp.feed_link_id
  WHERE a.user_id = '$REAL_USER_ID'::uuid AND fp.tier = 'popular'
  ORDER BY a.created_at DESC
  LIMIT 15
) a;
"

# 2e. Copy articles from normal feeds (5 per user)
echo "  Copying normal feed articles ($VU_COUNT users × 5 articles)..."
$COMPOSE exec -T db psql -U "$DB_USER" -d "$DB_NAME" -c "
INSERT INTO articles (id, title, content, url, feed_id, user_id, created_at, published_at)
SELECT
  gen_random_uuid(), a.title, a.content, a.url, a.feed_id,
  ('00000000-0000-4000-a000-' || lpad(u::text, 12, '0'))::uuid,
  a.created_at, a.published_at
FROM generate_series(1, $VU_COUNT) u
CROSS JOIN LATERAL (
  SELECT a.* FROM articles a
  JOIN feeds f ON a.feed_id = f.id
  JOIN _loadtest_feed_popularity fp ON f.feed_link_id = fp.feed_link_id
  WHERE a.user_id = '$REAL_USER_ID'::uuid AND fp.tier = 'normal'
  ORDER BY a.created_at DESC
  LIMIT 5
) a;
"

ART_COUNT=$($COMPOSE exec -T db psql -U "$DB_USER" -d "$DB_NAME" -t -A -c \
  "SELECT count(*) FROM articles WHERE user_id::text LIKE '00000000-0000-4000-a000-%';")
echo "  Articles created: $ART_COUNT"

# Clean up classification table and update statistics
$COMPOSE exec -T db psql -U "$DB_USER" -d "$DB_NAME" -c \
  "DROP TABLE IF EXISTS _loadtest_feed_popularity; ANALYZE user_feed_subscriptions; ANALYZE articles;" > /dev/null 2>&1

echo "  Setup complete."

# --- Phase 3: Run K6 load test ---
echo ""
echo "Phase 3: Running K6 feed read load test ($VU_COUNT VUs)..."

K6_ARGS="run $K6_SCENARIO"
if [ "$VU_COUNT" -eq 1 ]; then
  # Smoke test: override stages with 1 VU, 5 iterations
  K6_ARGS="run --vus 1 --iterations 5 $K6_SCENARIO"
fi

$COMPOSE run --rm k6 $K6_ARGS && K6_EXIT=0 || K6_EXIT=$?

# --- Phase 4: Collect logs & metrics ---
echo ""
echo "Phase 4: Collecting logs and metrics..."
$COMPOSE logs alt-backend --tail 500 > /tmp/alt-backend-feed-read-loadtest.log 2>&1 || true

# DB connection count
$COMPOSE exec -T db psql -U "$DB_USER" -d "$DB_NAME" -c \
  "SELECT count(*) as active_connections FROM pg_stat_activity WHERE state = 'active';" \
  > /tmp/db-connections-feed-read-loadtest.log 2>&1 || true

# PgBouncer pool stats
$COMPOSE exec -T pgbouncer psql -h localhost -p 6432 pgbouncer -c "SHOW POOLS;" \
  > /tmp/pgbouncer-pools-feed-read-loadtest.log 2>&1 || true

# pg_stat_statements: top 20 queries by mean execution time
$COMPOSE exec -T db psql -U "$DB_USER" -d "$DB_NAME" -c "
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
SELECT query, calls, mean_exec_time, max_exec_time, shared_blks_read, shared_blks_hit
FROM pg_stat_statements
ORDER BY mean_exec_time DESC
LIMIT 20;
" > /tmp/pg-stat-statements-feed-read-loadtest.log 2>&1 || true

# pprof heap and goroutine profiles
if [ "${PPROF_ENABLED:-false}" = "true" ]; then
  echo "  Collecting pprof heap profile..."
  curl -sf http://localhost:6060/debug/pprof/heap > /tmp/pprof-heap-feed-read.pb.gz 2>/dev/null || true
  curl -sf http://localhost:6060/debug/pprof/allocs > /tmp/pprof-allocs-feed-read.pb.gz 2>/dev/null || true
  curl -sf http://localhost:6060/debug/pprof/goroutine > /tmp/pprof-goroutine-feed-read.pb.gz 2>/dev/null || true
fi

echo "  Logs saved to /tmp/*-feed-read-loadtest.log"

# --- Phase 5: Teardown test data ---
echo ""
echo "Phase 5: Tearing down test data..."

$COMPOSE exec -T db psql -U "$DB_USER" -d "$DB_NAME" -c "
DELETE FROM articles WHERE user_id::text LIKE '00000000-0000-4000-a000-%';
DELETE FROM user_feed_subscriptions WHERE user_id::text LIKE '00000000-0000-4000-a000-%';
"

# Verify teardown
REMAINING_SUBS=$($COMPOSE exec -T db psql -U "$DB_USER" -d "$DB_NAME" -t -A -c \
  "SELECT count(*) FROM user_feed_subscriptions WHERE user_id::text LIKE '00000000-0000-4000-a000-%';")
REMAINING_ARTS=$($COMPOSE exec -T db psql -U "$DB_USER" -d "$DB_NAME" -t -A -c \
  "SELECT count(*) FROM articles WHERE user_id::text LIKE '00000000-0000-4000-a000-%';")
echo "  Remaining test subscriptions: $REMAINING_SUBS (expected: 0)"
echo "  Remaining test articles: $REMAINING_ARTS (expected: 0)"

# Reclaim space and update statistics
$COMPOSE exec -T db psql -U "$DB_USER" -d "$DB_NAME" -c \
  "VACUUM ANALYZE user_feed_subscriptions; VACUUM ANALYZE articles;" > /dev/null 2>&1 || true

echo "  Teardown complete."

# --- Phase 6: Restore default config ---
echo ""
echo "Phase 6: Restoring default config..."
if [ "$VU_COUNT" -gt 100 ]; then
  docker compose -f compose/compose.yaml -p alt up -d --force-recreate db pgbouncer auth-hub alt-backend
else
  docker compose -f compose/compose.yaml -p alt up -d --force-recreate alt-backend
fi
RESTORE_ON_EXIT=0

echo "  Removing generated overlay..."
rm -f "$GENERATED_OVERLAY"

echo ""
echo "========================================"
echo "  Load test complete (k6 exit: $K6_EXIT)"
echo "  Reports: alt-perf/reports/"
echo "========================================"

exit "$K6_EXIT"
