"""Provider verification tests for news-creator.

Verifies that news-creator fulfills the contracts defined by its consumers:
- pre-processor (via /api/v1/summarize)
- rag-orchestrator (via /api/chat)

These tests start a real FastAPI app with mocked usecases/gateways
and verify it against pact contracts. Contracts are loaded from either:
- Pact Broker (when PACT_BROKER_BASE_URL is set) — used in CI
- Local filesystem (fallback) — used in local development
"""

import importlib
import logging
import os
import socket
import threading
import time
import urllib.request
from pathlib import Path
from typing import Any, Dict
from unittest.mock import AsyncMock, Mock

import pytest
import uvicorn
from fastapi import FastAPI
from pact import Verifier

logger = logging.getLogger(__name__)

# Pact Broker configuration (set in CI via environment variables)
PACT_BROKER_URL = os.environ.get("PACT_BROKER_BASE_URL")
PACT_BROKER_USERNAME = os.environ.get("PACT_BROKER_USERNAME")
PACT_BROKER_PASSWORD = os.environ.get("PACT_BROKER_PASSWORD")
PACT_PROVIDER_VERSION = os.environ.get("PACT_PROVIDER_VERSION")
PACT_PROVIDER_BRANCH = os.environ.get("PACT_PROVIDER_BRANCH")

# Pact files generated by Go consumer tests (local fallback)
PACT_DIR = Path(__file__).resolve().parent.parent.parent.parent.parent / "pacts"
PRE_PROCESSOR_PACT = PACT_DIR / "pre-processor-news-creator.json"
RAG_ORCHESTRATOR_PACT = (
    Path(__file__).resolve().parent.parent.parent.parent.parent
    / "rag-orchestrator"
    / "pacts"
    / "rag-orchestrator-news-creator.json"
)


def _get_free_port() -> int:
    """Get a free port from the OS."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _create_provider_app() -> FastAPI:
    """Create a FastAPI app with mocked dependencies for provider verification."""
    app = FastAPI()

    # --- Mock summarize usecase ---
    import news_creator.handler.summarize_handler as summarize_mod

    importlib.reload(summarize_mod)

    # Track provider state to switch mock behavior
    provider_state = {"current": "default"}

    mock_summarize_usecase = Mock()

    async def _dynamic_generate_summary(*args: Any, **kwargs: Any):
        if provider_state["current"] == "queue_full":
            from news_creator.gateway.hybrid_priority_semaphore import QueueFullError
            raise QueueFullError("Queue depth 20 >= max 20")
        return (
            "これはテスト記事の要約です。",
            {
                "model": "gemma4-e4b-q4km",
                "prompt_tokens": 150,
                "completion_tokens": 80,
                "total_duration_ms": 2500.0,
            },
        )

    mock_summarize_usecase.generate_summary = AsyncMock(side_effect=_dynamic_generate_summary)
    router = summarize_mod.create_summarize_router(mock_summarize_usecase)
    app.include_router(router)

    # --- Mock chat handler ---
    import news_creator.handler.chat_handler as chat_mod

    importlib.reload(chat_mod)

    mock_ollama_gateway = Mock()

    # Non-streaming: gateway.chat_generate(payload=payload) -> dict
    async def _mock_chat_generate(payload: dict) -> Dict[str, Any]:
        return {
            "message": {"content": "This is a non-streaming response."},
            "done": True,
        }

    mock_ollama_gateway.chat_generate = AsyncMock(side_effect=_mock_chat_generate)

    # Streaming: gateway.chat_stream(payload=payload) -> async iterable of dict
    async def _mock_chat_stream_iter(payload: dict):
        chunks = [
            {"message": {"content": "Hello"}, "done": False},
            {"message": {"content": " world"}, "done": False},
            {"message": {"content": ""}, "done": True},
        ]
        for chunk in chunks:
            yield chunk

    # chat_stream is awaited then iterated, so return the async generator directly
    mock_ollama_gateway.chat_stream = AsyncMock(return_value=_mock_chat_stream_iter(payload={}))

    chat_router = chat_mod.create_chat_router(mock_ollama_gateway)
    app.include_router(chat_router)

    # --- Provider state handler ---
    from pydantic import BaseModel

    class ProviderStateRequest(BaseModel):
        state: str = ""
        action: str = "setup"

    @app.post("/_pact/provider-states")
    async def provider_states(req: ProviderStateRequest) -> dict:
        """Handle provider state setup for Pact verification."""
        logger.info("Setting up provider state: %s (action=%s)", req.state, req.action)
        if "queue is full" in req.state.lower():
            provider_state["current"] = "queue_full"
        else:
            provider_state["current"] = "default"
        return {"status": "ok"}

    return app


@pytest.fixture(scope="module")
def provider_url():
    """Start the provider server on a free port for all tests in this module."""
    port = _get_free_port()
    app = _create_provider_app()

    config = uvicorn.Config(app, host="127.0.0.1", port=port, log_level="warning")
    server = uvicorn.Server(config)

    thread = threading.Thread(target=server.run, daemon=True)
    thread.start()

    # Wait for server to be ready
    base_url = f"http://127.0.0.1:{port}"
    for _ in range(100):
        try:
            urllib.request.urlopen(f"{base_url}/openapi.json")
            break
        except Exception:
            time.sleep(0.05)
    else:
        pytest.fail("Provider server did not start")

    yield base_url, port


def _configure_verifier(
    verifier: Verifier,
    base_url: str,
    *,
    consumer_name: str | None = None,
    local_pact_path: Path | None = None,
) -> None:
    """Configure verifier with Broker or local file source.

    When PACT_BROKER_BASE_URL is set, loads contracts from Broker.
    Otherwise falls back to local pact files.
    """
    if PACT_BROKER_URL:
        builder = verifier.broker_source(
            url=PACT_BROKER_URL,
            username=PACT_BROKER_USERNAME,
            password=PACT_BROKER_PASSWORD,
            selector=True,
        )
        if consumer_name:
            builder = builder.consumer_version(consumer=consumer_name, latest=True)
        else:
            builder = builder.consumer_version(latest=True)
        builder.build()

        if PACT_PROVIDER_VERSION:
            verifier.set_publish_options(
                version=PACT_PROVIDER_VERSION,
                url=PACT_BROKER_URL,
                branch=PACT_PROVIDER_BRANCH,
            )
    elif local_pact_path and local_pact_path.exists():
        verifier.add_source(str(local_pact_path))
    else:
        pytest.skip(
            f"No Broker URL set and pact file not found: {local_pact_path}. "
            "Set PACT_BROKER_BASE_URL or run Go consumer tests first."
        )

    verifier.state_handler(
        f"{base_url}/_pact/provider-states",
        teardown=False,
        body=True,
    )


@pytest.mark.skipif(
    not PACT_BROKER_URL and not PRE_PROCESSOR_PACT.exists(),
    reason=f"No Broker URL and pact file not found: {PRE_PROCESSOR_PACT}",
)
def test_verify_pre_processor_contract(provider_url: tuple[str, int]):
    """Verify news-creator satisfies pre-processor's contract."""
    base_url, port = provider_url

    verifier = Verifier("news-creator")
    verifier.add_transport(protocol="http", port=port)
    _configure_verifier(
        verifier,
        base_url,
        consumer_name="pre-processor",
        local_pact_path=PRE_PROCESSOR_PACT,
    )

    verifier.verify()


@pytest.mark.skipif(
    not PACT_BROKER_URL and not RAG_ORCHESTRATOR_PACT.exists(),
    reason=f"No Broker URL and pact file not found: {RAG_ORCHESTRATOR_PACT}",
)
def test_verify_rag_orchestrator_contract(provider_url: tuple[str, int]):
    """Verify news-creator satisfies rag-orchestrator's contract."""
    base_url, port = provider_url

    verifier = Verifier("news-creator")
    verifier.add_transport(protocol="http", port=port)
    _configure_verifier(
        verifier,
        base_url,
        consumer_name="rag-orchestrator",
        local_pact_path=RAG_ORCHESTRATOR_PACT,
    )

    verifier.verify()
