"""Provider verification tests for recap-subworker.

Verifies that recap-subworker fulfills the contracts defined by its consumers:
- recap-worker (via /v1/classify-runs, /v1/classify-runs/{run_id},
  /v1/classify/coarse, /v1/clustering/{run_id})

These tests start a real FastAPI app with mocked dependencies
and verify it against pact contracts. Contracts are loaded from either:
- Pact Broker (when PACT_BROKER_BASE_URL is set) -- used in CI
- Local filesystem (fallback) -- used in local development
"""

import logging
import os
import socket
import threading
import time
import urllib.request
from pathlib import Path

import pytest
import uvicorn
from fastapi import FastAPI
from pact import Verifier
from pydantic import BaseModel

logger = logging.getLogger(__name__)

# Pact Broker configuration (set in CI via environment variables)
PACT_BROKER_URL = os.environ.get("PACT_BROKER_BASE_URL")
PACT_BROKER_USERNAME = os.environ.get("PACT_BROKER_USERNAME")
PACT_BROKER_PASSWORD = os.environ.get("PACT_BROKER_PASSWORD")
PACT_PROVIDER_VERSION = os.environ.get("PACT_PROVIDER_VERSION")
PACT_PROVIDER_BRANCH = os.environ.get("PACT_PROVIDER_BRANCH")

# Pact files generated by Rust consumer tests (local fallback)
PACT_DIR = Path(__file__).resolve().parent.parent.parent.parent / "pacts"
RECAP_WORKER_PACT = PACT_DIR / "recap-worker-recap-subworker.json"


def _get_free_port() -> int:
    """Get a free port from the OS."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _create_provider_app() -> FastAPI:
    """Create a FastAPI app with mocked dependencies for provider verification.

    Registers lightweight stub endpoints matching the contract surface:
    - POST /v1/classify-runs          (classification job submission)
    - GET  /v1/classify-runs/{run_id} (polling a completed classification job)
    - POST /v1/classify/coarse        (coarse classification request)
    - POST /v1/clustering/{run_id}    (clustering execution request)
    """
    app = FastAPI()

    # Track provider state to switch mock behavior
    provider_state = {"current": "default"}

    # ---- POST /v1/classify-runs ----
    class ClassifyRunsRequest(BaseModel):
        texts: list[str]

    @app.post("/v1/classify-runs")
    async def create_classification_run(payload: ClassifyRunsRequest) -> dict:
        return {
            "run_id": 1,
            "job_id": "00000000-0000-0000-0000-000000000001",
            "status": "running",
            "result_count": 0,
        }

    # ---- GET /v1/classify-runs/{run_id} ----
    @app.get("/v1/classify-runs/{run_id}")
    async def get_classification_run(run_id: int) -> dict:
        return {
            "run_id": run_id,
            "job_id": "00000000-0000-0000-0000-000000000001",
            "status": "succeeded",
            "result_count": 5,
            "results": [
                {
                    "top_genre": "technology",
                    "confidence": 0.85,
                    "scores": {"technology": 0.85, "science": 0.1},
                }
            ],
        }

    # ---- POST /v1/classify/coarse ----
    class CoarseClassifyRequest(BaseModel):
        text: str

    @app.post("/v1/classify/coarse")
    async def classify_coarse(request: CoarseClassifyRequest) -> dict:
        return {
            "scores": {"technology": 0.8, "science": 0.15},
        }

    # ---- POST /v1/clustering/{run_id} ----
    @app.post("/v1/clustering/{run_id}")
    async def execute_clustering(run_id: int) -> dict:
        return {
            "run_id": run_id,
            "job_id": "00000000-0000-0000-0000-000000000001",
            "genre": "technology",
            "status": "succeeded",
            "cluster_count": 3,
            "clusters": [
                {
                    "cluster_id": 0,
                    "size": 5,
                    "top_terms": ["AI"],
                    "representatives": [
                        {"sentence_text": "AI is transforming industries."}
                    ],
                }
            ],
        }

    # ---- Provider state handler ----
    class ProviderStateRequest(BaseModel):
        state: str = ""
        action: str = "setup"

    @app.post("/_pact/provider-states")
    async def provider_states(req: ProviderStateRequest) -> dict:
        """Handle provider state setup for Pact verification."""
        logger.info("Setting up provider state: %s (action=%s)", req.state, req.action)
        provider_state["current"] = req.state
        return {"status": "ok"}

    return app


@pytest.fixture(scope="module")
def provider_url():
    """Start the provider server on a free port for all tests in this module."""
    port = _get_free_port()
    app = _create_provider_app()

    config = uvicorn.Config(app, host="127.0.0.1", port=port, log_level="warning")
    server = uvicorn.Server(config)

    thread = threading.Thread(target=server.run, daemon=True)
    thread.start()

    # Wait for server to be ready
    base_url = f"http://127.0.0.1:{port}"
    for _ in range(100):
        try:
            urllib.request.urlopen(f"{base_url}/openapi.json")
            break
        except Exception:
            time.sleep(0.05)
    else:
        pytest.fail("Provider server did not start")

    yield base_url, port


def _configure_verifier(
    verifier: Verifier,
    base_url: str,
    *,
    consumer_name: str | None = None,
    local_pact_path: Path | None = None,
) -> None:
    """Configure verifier with Broker or local file source.

    When PACT_BROKER_BASE_URL is set, loads contracts from Broker.
    Otherwise falls back to local pact files.
    """
    if PACT_BROKER_URL:
        builder = verifier.broker_source(
            url=PACT_BROKER_URL,
            username=PACT_BROKER_USERNAME,
            password=PACT_BROKER_PASSWORD,
            selector=True,
        )
        if consumer_name:
            builder = builder.consumer_version(consumer=consumer_name, latest=True)
        else:
            builder = builder.consumer_version(latest=True)
        builder.build()

        if PACT_PROVIDER_VERSION:
            verifier.set_publish_options(
                version=PACT_PROVIDER_VERSION,
                url=PACT_BROKER_URL,
                branch=PACT_PROVIDER_BRANCH,
            )
    elif local_pact_path and local_pact_path.exists():
        verifier.add_source(str(local_pact_path))
    else:
        pytest.skip(
            f"No Broker URL set and pact file not found: {local_pact_path}. "
            "Set PACT_BROKER_BASE_URL or run Rust consumer tests first."
        )

    verifier.state_handler(
        f"{base_url}/_pact/provider-states",
        teardown=False,
        body=True,
    )


@pytest.mark.skipif(
    not PACT_BROKER_URL and not RECAP_WORKER_PACT.exists(),
    reason=f"No Broker URL and pact file not found: {RECAP_WORKER_PACT}",
)
def test_verify_recap_worker_contract(provider_url: tuple[str, int]):
    """Verify recap-subworker satisfies recap-worker's contract."""
    base_url, port = provider_url

    verifier = Verifier("recap-subworker")
    verifier.add_transport(protocol="http", port=port)
    _configure_verifier(
        verifier,
        base_url,
        consumer_name="recap-worker",
        local_pact_path=RECAP_WORKER_PACT,
    )

    verifier.verify()
