// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// AnswerCitation defines model for AnswerCitation.
type AnswerCitation struct {
	ChunkId         *string  `json:"chunk_id,omitempty"`
	ChunkText       *string  `json:"chunk_text,omitempty"`
	DocumentVersion *int64   `json:"document_version,omitempty"`
	Score           *float32 `json:"score,omitempty"`
	Title           *string  `json:"title,omitempty"`
	Url             *string  `json:"url,omitempty"`
}

// AnswerDebug defines model for AnswerDebug.
type AnswerDebug struct {
	PromptVersion  *string `json:"prompt_version,omitempty"`
	RetrievalSetId *string `json:"retrieval_set_id,omitempty"`
}

// AnswerRequest defines model for AnswerRequest.
type AnswerRequest struct {
	CandidateArticleIds *[]string `json:"candidate_article_ids,omitempty"`
	Locale              *string   `json:"locale,omitempty"`
	MaxChunks           *int32    `json:"max_chunks,omitempty"`
	MaxTokens           *int32    `json:"max_tokens,omitempty"`
	Query               string    `json:"query"`
	UserId              *string   `json:"user_id,omitempty"`
}

// AnswerResponse defines model for AnswerResponse.
type AnswerResponse struct {
	Answer    *string           `json:"answer,omitempty"`
	Citations *[]AnswerCitation `json:"citations,omitempty"`
	Contexts  *[]Context        `json:"contexts,omitempty"`
	Debug     *AnswerDebug      `json:"debug,omitempty"`
	Fallback  *bool             `json:"fallback,omitempty"`
	Reason    *string           `json:"reason,omitempty"`
}

// Context defines model for Context.
type Context struct {
	ChunkId   *string `json:"chunk_id,omitempty"`
	ChunkText *string `json:"chunk_text,omitempty"`

	// DocumentVersion Version of the document this chunk belongs to
	DocumentVersion *int64     `json:"document_version,omitempty"`
	PublishedAt     *time.Time `json:"published_at,omitempty"`

	// Score Similarity score
	Score *float32 `json:"score,omitempty"`
	Title *string  `json:"title,omitempty"`
	Url   *string  `json:"url,omitempty"`
}

// DeleteIndexRequest defines model for DeleteIndexRequest.
type DeleteIndexRequest struct {
	ArticleId string `json:"article_id"`
	UserId    string `json:"user_id"`
}

// RetrieveRequest defines model for RetrieveRequest.
type RetrieveRequest struct {
	// CandidateArticleIds Optional list of article IDs to restrict search to
	CandidateArticleIds *[]string `json:"candidate_article_ids,omitempty"`
	Query               string    `json:"query"`
}

// RetrieveResponse defines model for RetrieveResponse.
type RetrieveResponse struct {
	Contexts *[]Context `json:"contexts,omitempty"`
}

// UpsertIndexRequest defines model for UpsertIndexRequest.
type UpsertIndexRequest struct {
	// ArticleId Unique identifier of the article (UUID or string)
	ArticleId string `json:"article_id"`

	// Body Full text content of the article
	Body        string     `json:"body"`
	PublishedAt time.Time  `json:"published_at"`
	Title       string     `json:"title"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty"`
	Url         string     `json:"url"`

	// UserId User ID owning the article
	UserId string `json:"user_id"`
}

// DeleteIndexJSONRequestBody defines body for DeleteIndex for application/json ContentType.
type DeleteIndexJSONRequestBody = DeleteIndexRequest

// UpsertIndexJSONRequestBody defines body for UpsertIndex for application/json ContentType.
type UpsertIndexJSONRequestBody = UpsertIndexRequest

// AnswerWithRAGJSONRequestBody defines body for AnswerWithRAG for application/json ContentType.
type AnswerWithRAGJSONRequestBody = AnswerRequest

// AnswerWithRAGStreamJSONRequestBody defines body for AnswerWithRAGStream for application/json ContentType.
type AnswerWithRAGStreamJSONRequestBody = AnswerRequest

// RetrieveContextJSONRequestBody defines body for RetrieveContext for application/json ContentType.
type RetrieveContextJSONRequestBody = RetrieveRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Delete or tombstone an article from the index
	// (POST /internal/rag/index/delete)
	DeleteIndex(ctx echo.Context) error
	// Upsert an article to the RAG index
	// (POST /internal/rag/index/upsert)
	UpsertIndex(ctx echo.Context) error
	// Answer a query using RAG (with LLM generation)
	// (POST /v1/rag/answer)
	AnswerWithRAG(ctx echo.Context) error
	// Stream a RAG answer using Server-Sent Events
	// (POST /v1/rag/answer/stream)
	AnswerWithRAGStream(ctx echo.Context) error
	// Retrieve context for a query (Retrieve-Only)
	// (POST /v1/rag/retrieve)
	RetrieveContext(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DeleteIndex converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteIndex(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteIndex(ctx)
	return err
}

// UpsertIndex converts echo context to params.
func (w *ServerInterfaceWrapper) UpsertIndex(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpsertIndex(ctx)
	return err
}

// AnswerWithRAG converts echo context to params.
func (w *ServerInterfaceWrapper) AnswerWithRAG(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AnswerWithRAG(ctx)
	return err
}

// AnswerWithRAGStream converts echo context to params.
func (w *ServerInterfaceWrapper) AnswerWithRAGStream(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AnswerWithRAGStream(ctx)
	return err
}

// RetrieveContext converts echo context to params.
func (w *ServerInterfaceWrapper) RetrieveContext(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RetrieveContext(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/internal/rag/index/delete", wrapper.DeleteIndex)
	router.POST(baseURL+"/internal/rag/index/upsert", wrapper.UpsertIndex)
	router.POST(baseURL+"/v1/rag/answer", wrapper.AnswerWithRAG)
	router.POST(baseURL+"/v1/rag/answer/stream", wrapper.AnswerWithRAGStream)
	router.POST(baseURL+"/v1/rag/retrieve", wrapper.RetrieveContext)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xY224bNxD9lQHbBxuQLeXSItCbG6eBirQOLLh9SAKBIme1TLjkmpyVLQT+94Lkrq6U",
	"o9R20DdJ5Fx45pyzXH1lwla1NWjIs+FX5kWJFY8fz4y/QfdaESdlTfildrZGRwrjuigb82WiZPhMixrZ",
	"kHlyyszYXa9dJLyl7LK0oqnQ0GSOzrfZC+sqTmzIlKFfX7JeF6UM4QxdCPPCOtzYW2jLabXXNNU0bSVF",
	"GrO1G6czv98tc9jpZxQUdiYEznHazHaPXztb1RsH2KnkkJzCOdcTj5RHan/ZS7xu0FMGd26kkpxwwh0p",
	"oXGiZFxQhJXPNtL+wJ3ji/BdW8H3oFPx20kcnt+eyYvn2ZmEALJf0BwacN2gW+Qn49HthcnhdaMcSjb8",
	"0Kb4dA92vrbG4y54PK7nKdsyfRPLnx0WbMh+6q900m9F0t9SSAZoYU3QwOEpX6eAXC7Z8fDbLSXK3vVY",
	"wbWecvFl7cBTazVyk/jJfZa6OVZ2nT25D0j0wqk6mQ77Oy2ALYBKhC4AqFQeYnaYorZm5oEs6x3iInUz",
	"1cqXKCecNjgbRHVCqsJV2KrVpfds9jdWldLcKVpA2tH7QeZ0jhoJR0bi7V6rWBnEw/S2lmcVlZPfZXI8",
	"/H7z2kT1In7gGrTyFGbf7obReZgzOAydCgKP3Ikyjf5w/9tnQQfbzOqc+4zm8ZSfG/5V7dHR9wx/E98r",
	"o64bBCXRkCoUuk5fHc5HV1ejc7AOEjTHOUVMrVzspv690RrCSSBCYGgrdS7Tf1PkPSqqQ+D3Zcsrb0Mk",
	"Wxh6dBBAujHKzO4/4iF66g6UWtkCpUV7l4shtTKF3e3v7P0ICuvg8uwtXDhRBslwsg6OIm9Cz9xIuOwu",
	"KcfLDoZsJ+bs/Yj12NKl2bPTwekgwGNrNLxWbMhenA5OX4S+OZWRgP3guc5w3Xd81lehaF9G14pktYm0",
	"gbLx+TmSbLjuaixhhp5+a4nWEiqSu661EjGu/7l9iCUlfUtnGd+825wPuQbjD0nb8SzPB4OM9zdCoPdF",
	"o/UCamfDF5QBlZe57SMz51pJcF3ZHvslvy/BBh7dHB2gc9ZFDvmmqnhwrhanIFCy1dSTNQjcLOVbOFtF",
	"RkbUY2xuGk20kfVpbHZyiQLVfOUKkhPvgeBaNJoTglRFgQ6NQN+LZErCW1WGG0WlbQjsHN2NUxRYh7fK",
	"xw8h3elHM5JY1TZZRUcGOJpyjxKsWdpIyX15fPrRsN4WZ9bM8Ik4k7HbR+EMFwJrQtm/brA5nDlQ84W2",
	"XD6IQelM66QhGwcXtL9Gm/mzSJjVxXkfVdIT0UP75It8mKGJk4peAykHNL79/u7dn7l5pjvsP4rKy7O3",
	"TzTRzXesw4f5qMXbu0Osvo8lLWgPGnWqBxzihabFP4z5KMgzjGE5KGuOM2Pve3LIq/3TH8d1H/njeYUw",
	"c7YxEmU38w5LmCsO4/Eb8BaEVgEWENyAQyPRQR24yHXY3mjyMMXCuuQnQTHwx/jiL1AeohzCI/6b/Emd",
	"/X9ZFKTSxzkaOlmBvKq+fY/YZUrAMgaGe1YYaot4zOkfxJuEHfD1tIk84xh0Mg6+/KYttMaa9o8PPMQu",
	"HGqcc0PpZc7HK8smU+cowhUkXfV7UFvv1VQvoFCaMOAC0wUsXyzWXxVy7Ogqd/ftp2HG9ovQD3aYnfeT",
	"+z1m+UfVg+jSFV0+AdZHedStnlwYvThODaVkng0/bNd7Z8WyWHsjHrKSqB72+/Hfq9J6Gr4avBqwu093",
	"/wYAAP//q4UTlsYUAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
