FROM rust:1.87-slim AS builder

WORKDIR /app

COPY app/ .

RUN cargo build --release --bin rask

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/target/release/rask /usr/local/bin/rask-log-aggregator

CMD ["rask-log-aggregator"]